### ISSUE TITLE
`make test` on 32-bit platforms fails because -race isn't valid

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1075]
I have a script that I use to automate running elvish unit tests on my primary macOS server and several VMs. One of the VMs is a Ubuntu 32-bit distro. After syncing my local elvish repo it runs

```
env TEST_ENV='' TEST_FLAGS='' ELVISH_TEST_TIME_SCALE=$TEST_SCALE make -e test
```

That worked fine up until commit 32328bb4 which removed the `TEST_ENV` and `TEST_FLAGS` vars from the *./Makefile*. I know I can simply change my test runner script to replace the `... make -e test` with `go test ./...`. I'm opening this issue to discuss whether we want `make test` to continue to be the standard way to run the elvish unit tests on all supported platforms. If not perhaps that makefile target should be removed.

**Comment by xiaq** [comment]
The `test` target is mainly useful as part of the default target, which does both testing (`go test`) and installation (`go get`), so I'd rather not remove it.

There doesn't seem to be a simple way to ask `go` whether `-race` is supported, but since there is currently only a handful of platforms where it is (linux/amd64, freebsd/amd64, darwin/amd64 and windows/amd64), I'll hardcode this check in the Makefile. This has the small risk of being out of date when the race detector supports more platforms, but that seems to be the best we can do now.
