### ISSUE TITLE
support stdin in -source builtin

### ISSUE THREAD

**Issue by rsteube** [elves/elvish#1087]
Currently a temporary file must be generated to use the [`-source`](https://github.com/elves/elvish/blob/e5e0446c5a6b089085eaad31491bbd346d1643a7/pkg/eval/builtin_fn_misc.go#L276) builtin.
Would be nice to be able to pipe this in as in fish: `generate_script | source`.

related #230

**Comment by krader1961** [comment]
Ignoring the fact that `-source` is still marked experimental, I agree that there is no good reason to not allow reading from stdin. However, it should be explicit; i.e., `echo put yes | -source -`. That, obviously, has the problem that if you really want to source a file named `-` you can't do so. However, that will never be a problem other than for people deliberately exploring the behavior of corner cases. Also, in the context of Elvish `-source &stdin` could be supported rather than `-source -`. Which would allow `source -` to read a file named `-`.

**Comment by hanche** [comment]
I think `-source &stdin` fits the elvish philosophy rather than special casing `-`. That said, the standard workaround for other programs using this special casing is to specify `./-` as the input file.

**Comment by xiaq** [comment]
I am planning to remove `-source` the command; the new [eval](https://elv.sh/ref/builtin.html#eval) command should be used instead.
