### ISSUE TITLE
WIndows: c

### ISSUE THREAD

**Issue by qazxwecvr** [elves/elvish#1106]
I am using windows 10.
When I run `help`, it says I can list the contents of the directory with `dir`, but when I try I get this error:
`exec: "dir": executable file not found in %PATH%`

**Comment by krader1961** [comment]
The reason is that `dir` is a cmd.exe or powershell builtin. There is no *dir.exe* program. There is, however, a *help.exe* program: 

```
> search-external help
C:\WINDOWS\system32\help.exe
```

That's why elvish can run the (external) `help` command but not `dir`. At least not unless you've install MSYS in which case it provides */c/msys64/usr/bin/dir.exe* which, sort of, acts as a cmd.exe `dir` replacement. In general, if you're trying to use bash or elvish on Windows, you need MSYS or Cygwin.

**Comment by qazxwecvr** [comment]
Thank you, that worked!

**Comment by krader1961** [comment]
@qazxwecvr, Can you please close this issue since it appears my comment resolved the issue?

Also, please note that you are going to run into many such problems since, AFAIK, there are very few, if any, people using Elvish on Windows. So please open a new issue whenever you encounter a problem using Elvish on Windows.
