### ISSUE TITLE
Writing values to an output redirection should fail

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1149]
See #1010 and #600 for background. The short version is that `put x > f` should fail with an exception since Elvish does not allow writing values to files via redirection. Elvish silently discards the value(s) at this time which is suboptimal as it can lead to data corruption.

**Comment by krader1961** [comment]
As best I can tell all existing uses of `BlackholeChan` should be replaced by a method that results in an exception if an attempt is made to write to the value channel. This includes the sole use of `DevNullPorts` in `func (ev *Evaler) Eval(op Op, cfg EvalCfg)`. If the consumer is not known to be able to handle value output any value output should cause an exception.

**Comment by therealpxc** [comment]
It would be good for commands whose output is structured data to behave with an awareness of whether their output is a terminal or a pipeline. Elvish literal syntax makes sense for passing them to other Elvish functions, but for humans, visually reading a list of maps with many keys can be difficult; some kind of automatic pretty-printing for (pseudo-)maps and lists of uniformly structured (pseudo-maps) would be nice.

(For example, shells which share Elvish's emphasis on structured pipelines make generous use of pretty printers for commands that result in structured data. A sensible and widely-used convention for lists of maps which share keys is a table: a row for each map and a column for each key— something like that can make even pretty dense output friendly to human eyes.)

**Comment by krader1961** [comment]
Presumably when you say "output is a terminal" you really mean "output is to anything other than an Elvish value consuming pipeline" (or words to that effect). I mention this because there are a couple of cases:

1) An interactive shell where the last command in a pipeline outputs values to the tty.

2) An interactive shell where the last command in a pipeline outputs values to a file via redirection.

3) A non-interactive shell (this is really just a variation of number two).

4) A command that writes to a pipeline whose RHS is an external command; thus incapable of receiving values.

> shells which share Elvish's emphasis on structured pipelines make generous use of pretty printers for commands that result in structured data.

I have never used Windows PowerShell or nushell. I've only glanced at their documentation. What do you think would be an appropriate method for Elvish to emulate that behavior? An implicit rewriting of values to text? An explicit command the output has to be piped through; e.g., `builtin:ls | pprint`? An option to the command; e.g., `builtin:ls &long`? What happens if the command outputs text and values?

**Comment by therealpxc** [comment]
> Presumably when you say "output is a terminal" you really mean "output is to anything other than an Elvish value consuming pipeline"

I'm not quite sure I want to be that general, but you're right that there are additional cases where some kind of pretty-printing would be in order besides a terminal (which by which I mean a TTY or a GUI terminal emulator window, idrk the technical details of what makes a terminal a terminal). But there are two things that a pretty-printer might reasonably do in an actual terminal that wouldn't make a lot of sense when output is going to a file:
 (a) escape characters used for visual pleasantness in interactive use cases, like for colorization (imagine pretty-printing a single Elvish function, for example), or even [graphics](https://github.com/saitoha/libsixel) for previews or icons that don't depend on a user's font configuration
 (b) automatic paging if the output is taller than the terminal itself, a default behavior of some dedicated pretty-printer commands like [bat](https://github.com/sharkdp/bat)

Throwing an error mostly makes sense to me in case (4), but maybe Elvish should be able to know things about what commands expect from the text pipeline in the same way that it can know things about what they expect in their arguments. In the case of pagers, if it knew that more just expects lines of plain text, it could use the same formatter as for cases (2) and (3) above, and if it knew that bat expects lines of text, including control characters for colorization and other formatting, it could use the same formatter as in case (1). If no stream formatting behavior has been defined for an external command, then it throws an error.

> I have never used Windows PowerShell or nushell. I've only glanced at their documentation. What do you think would be an appropriate method for Elvish to emulate that behavior? An implicit rewriting of values to text? An explicit command the output has to be piped through; e.g., builtin:ls | pprint? An option to the command; e.g., builtin:ls &long? What happens if the command outputs text and values?

In PowerShell, the values output by most commands implicitly invoke Format-Table. But there are also Format-List (whose output looks like a nested list), Format-Wide (which looks like the output of ls -C), as well. If you explicitly pipe output to one of those, that Format-Whatever command will handle the printing instead of Format-Table. Additionally, some commands, by default, have their output printed by Format-List instead of Format-Table.

Not exactly sure how they've implemented this, but I think it makes sense and we could emulate it like this:
  * values can have a key associated with them whose value is a string representation
    - if the value is a string, this key is associated with the very same string
    - if this key is absent, the value effectively defaults to something like what we get with put $somefunc, a type and a hash
  * values can have a key associated with them whose value is a pretty-printing function
    - pretty-printing functions can be
      - given space constraints
      - told whether to print a brief/intermediate/embedded form (like for use in a cell in a table, where the printer itself might choose to impose a maximum width) or an expanded/final/outer form (use as much width as you can, pipe to a pager at the end if you want)
      - told whether to print plain (plain text, for non-interactive cases or outputting to files) or fancy (could include escape characters for colorization or other niceness)
    - if this key is absent, its value effectively defaults to something that always prints plain, prints a table (paging if necessary) in the expanded case, and prints a truncated version of a value's string representation in the brief case
  * pprint-table is a pretty printing function that uses key names for columns, and calls the pretty printing functions of the values associated with those keys to populate the cells

One final consideration is also a bit of a PowerShell-ism: in PowerShell, ordinary values are always callable, but calling them does not invoke other commands— even strings. Instead, strings that are to be run as commands need to be invoked explicitly using the call operator, `&`. This is unlike traditional Unix shells, so idk if it's the right fit for Elvish, but it seems like a good call in general for me. But that kind of mechanism seems like it would be kind of a nice way to automatically invoke a pretty-printing function, and to avoid invoking the pretty printing function when it gets passed down the chain in a pipeline: only the final value of a pipeline gets called at the end of it, otherwise it just gets passed through. This would also be a natural way to allow explicitly piping the output of a command to a non-default pretty-printing function (or one that happens to be the same as the default pretty-printing function, but with different parameters, like explicitly requesting for fancy or plain printing).

PS: Sorry I took so long to get to this— I spent some time thinking through it and writing it out, then decided that I had probably overspecified things a bit, and decided to set it aside to revise later. But it's quite a bit later and I never got to that, so I decided to post it as-is in the hopes that it can be useful anyway.

**Comment by krader1961** [comment]
This appears to be related to issue #1069.

**Comment by xiaq** [comment]
Fixed in ce08c4a7d57a3132194617f05f00696355281acf.
