### ISSUE TITLE
dependency: Use a latest spec compliant TOML implementation package

### ISSUE THREAD

**Issue by qlcom** [elves/elvish#1158]

**Comment by krader1961** [comment]
Is there some reason this change in dependency is needed? The new dependency is considerably larger. Is that increased size and complexity justified? Why use `github.com/pelletier/go-toml` rather than an alternative implementation?

I did verify that making the documentation still produces correct output. All of the generated files are identical with the proposed change.

Also, https://github.com/BurntSushi/toml/issues/265. Mentioning that issue is arguably a case of "[poisoning the well](https://en.wikipedia.org/wiki/Poisoning_the_well)" but I'd like to understand why you feel so strongly about this change.[

**Comment by qlcom** [comment]
> github.com/pelletier/go-toml rather than an alternative implementation?

currently that's the only implementation i know that is latest spec compliant.

> why you feel so strongly about this change.[

so that the toml parsing is latest spec compliant.

**Comment by krader1961** [comment]
> currently that's the only implementation i know that is latest spec compliant.

How does that justify this change given that Elvish doesn't need a TOML reader compliant with the latest spec? The current use of the package does not require any features not supported by the current dependency given that the package is not exposed in the Elvish shell. Also, your response doesn't address other questions such as whether the implementation you favor is superior when support for the latest TOML spec is not the only criteria.

Please understand: I am not opposed to this change. I'm simply wary of changing a dependency without good reason.

**Comment by qlcom** [comment]
> I'm simply wary of changing a dependency without good reason.

i only made this changes because the current package's development has stopped. 

> whether the implementation you favor is superior when support for the latest TOML spec is not the only criteria.

If you don't need latest spec compliance, then it's fine. But why not have that?

**Comment by qlcom** [comment]
I am sorry for wasting your time.

**Comment by krader1961** [comment]
> I am sorry for wasting your time.

You did not waste my time. You do not need to apologize. As I said earlier: I am not opposed to this change. I simply do not understand why you proposed this change. If, for example, you intend to add a `from-toml` command to Elvish then this change probably makes sense.
