### ISSUE TITLE
Should `resolve count` and `resolve builtin:count` produce identical output?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1171]
I was looking at issue #857 and noticed this behavior:

```
> resolve count
▶ '$count~'
> resolve builtin:count
▶ '$builtin:count~'
```

This is closely related to issue #1044. My feeling is that the two `resolve` invocations should produce the same output; i.e., `'$builtin:count~'`. In no small part because the current behavior of the first command is ambiguous. Is `$count~` a function I defined at an interactive prompt or the builtin? This implies that #1044 should be resolved by doing an implicit `use builtin` during elvish initialization.

**Comment by krader1961** [comment]
See also issue #1227.

**Comment by xiaq** [comment]
No. The `resolve` command only emulates the first step in command resolution, which is deciding whether it is a special command, a function, or an external command. If it's determined to be a function, a command head `head` is equivalent to `$head~`. Resolving that variable form to a particular namespace is logically a separate operation (variable resolution).

It could be argued that `resolve` should do variable resolution too, but right now, it is not possible in the general case - how to refer to a namespace is dependent on the lexical environment; there is no globally unambiguous way to refer to, say, the `str:` module because it may be imported under any name in a given lexical environment. The builtin namespace used to be an exception to this rule - which I suppose is the motivation for resolving `$count~` to `$builtin:count~` because the latter did use to be unambiguous; but that exception has been removed.

There is then a deeper question of whether there *should* be a globally unambiguous way to refer to any given namespace. I filed #1284 for this.
