### ISSUE TITLE
`exec` doesn't work on MS Windows

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1195]
Is the `exec` builtin expected to work on MS Windows? If not it probably needs a better error message:

```
~> exec \msys64\usr\bin\bash.exe
Exception: arity mismatch: arguments here must be 0 values, but is 1 value
[tty 9], line 1: exec \msys64\usr\bin\bash.exe
~> \msys64\usr\bin\bash.exe
krader@Windows10 MSYS ~
#
```

**Comment by krader1961** [comment]
I finally took a look at how Elvish handles the `exec` builtin and, not too surprising, it is explicitly not supported on Windows (see *pkg/eval/builtin_fn_cmd_windows.go*). This issue against Go is relevant: https://github.com/golang/go/issues/30662. Using `os.Exec()` on Windows is probably the simplest way to resolve this. Also, it's not clear why the unix support code is using `syscall.Exec()` rather than `os.Exec()`.

**Comment by krader1961** [comment]
There is still the problem that the error message is wrong regardless of whether `exec` is implemented for Windows.

**Comment by krader1961** [comment]
Gah! The documentation states: "This command always raises an exception on Windows." Not sure how I missed that but it should probably be rephrased along these lines:

```
// **Note:** This command only works on UNIX.
```

**Comment by xiaq** [comment]
Ha, the error message is caused by the Windows version of the implementation not actually accepting any arguments. This is now fixed.



> Gah! The documentation states: "This command always raises an exception on Windows." Not sure how I missed that but it should probably be rephrased along these lines:
> 
> ```
> // **Note:** This command only works on UNIX.
> ```

I avoid phrasing like "works" and "doesn't work" since it's unclear what would happen if you use something that doesn't work. Saying that this command raises an exception is better than saying that it doesn't work.

> And the doc string should be in file _pkg/eval/builtin_fn_cmd.go_ rather than _pkg/eval/builtin_fn_cmd_unix.go_

Since there is only an implementation for Unix, putting it in `..._unix.go` keeps the elvdoc closer to the implementation.
