### ISSUE TITLE
Is it possible to support AND-OR list?

### ISSUE THREAD

**Issue by mrlzh** [elves/elvish#1197]
https://pubs.opengroup.org/onlinepubs/9699919799/utilities/V3_chap02.html  2.9.3 Lists
command likes:
```
false ||echo ok
true && echo ok
```

**Comment by SolitudeSF** [comment]
```
or ?(false) (echo ok)
true; echo ok
```
https://elv.sh/ref

**Comment by krader1961** [comment]
FWIW, I recommend not using `||` and `&&` in a script (interactively is ok), and never use them together. See issue #1062 

Also, because Elvish converts a non-zero exit status into an exception if not explicitly trapped it doesn't need the POSIX `&&` list operator. Simply execute the commands in sequence. For example:

```
> /usr/bin/false; echo yes
Exception: /usr/bin/false exited with 1
[tty 29], line 1: /usr/bin/false; echo false
> /usr/bin/true; echo yes
yes
```

**Comment by xiaq** [comment]
This is one part where Elvish will not be POSIX-compatible.

The parallel to `&&` is just the newline or `;`, since Elvish aborts execution on any error.

The parallel to `||` is the try-block: `try { false } except _ { echo ok }`
