### ISSUE TITLE
"slice bounds out of range" in glob.matchElement

### ISSUE THREAD

**Issue by mrlzh** [elves/elvish#1220]
Reappearance：
Decoding tCsrMDMyM9X4pf7r5w== with Base64 as filename and creating a file.

Executing the 'ls *.a' command causes a crash
```
panic: runtime error: slice bounds out of range [14:13]

goroutine 170 [running]:
github.com/elves/elvish/pkg/glob.matchElement(0xc000393960, 0x2, 0x2, 0xc0003bf598, 0xd, 0x0)
        /Users/testingliu/Desktop/elvish-0.14.1/pkg/glob/glob.go:238 +0x716
```

**Comment by xiaq** [comment]
The issue is now fixed, but I thought I'd share some interesting facts I found when trying to test this:
* macOS will not create a file whose name has invalid UTF-8 sequences.
* Windows pretends to, but substitutes the invalid sequence with U+FFFD.
* Linux seems to be the only OS that would happily create a file whose name contains anything but NUL.
