### ISSUE TITLE
Broken namespace resolution

### ISSUE THREAD

**Issue by kolbycrouch** [elves/elvish#1226]
Since commit: 6419f4524a1a5217e5d29fdc9ff0b6d4ca13b1a7

The following no longer works.

`$ cat bug1.elv`
`a = (use-mod ./bug2)`
`b = ($a[-add~])`

`$ cat bug2.elv`
`fn -add { put 3 }`
`a = (use-mod ./bug1)`

`$ elvish bug1.elv`

Since the change in the above commit, this throws an exception complaining that there is no suck key as `-add~`.

I use this sort of functionality in an elvish program I'm working on. I dynamically load a module based on $args and that module might load another module and execute a function from it that loads the first module. This recursive loading worked before, hopefully it's an easy problem. Skimming through the source on namespaces I couldn't quite understand why this is happening now.

**Comment by xiaq** [comment]
This is a consequence of changes in [circular dependencies](https://elv.sh/ref/language.html#circular-dependencies), and the fact that Elvish treats scripts and modules as different entities. So in this case, you have a dependency loop like this:

```
bug1 (script) -> bug2 (module) -> bug1 (module) -> bug2 (module)
```

So when `bug1` imports `bug2`, it only sees an empty namespace.

Circular dependencies is a tricky thing to handle in general, and I'm considering entirely forbidding them some time later What's your use case for circular dependency?

**Comment by xiaq** [comment]
Actually, this behavior is so confusing that I think it's better to already forbid circular dependencies in the next release.

**Comment by kolbycrouch** [comment]
That's too bad. I've unfortunately invested a lot of time on something requiring it. Again this works before the mentioned commit. I'm working on a package manager, where I load module 'a' which might need to use a function from module 'b' which itself loads module `a`. 

I use this extensively in a ~4k line project of mine and cant think of any other way to implement what I'm doing honestly.

I never experienced anything broken about it until said commit.

**Comment by xiaq** [comment]
@kolbycrouch Hmm... I'd like to understand the use case better, it's not clear to me why a package manger would necessarily lead to circular dependencies.

Is your project open source and can you point me to it? If not, can you maybe distill the need for circular dependency into a small example?

**Comment by kolbycrouch** [comment]
It's not open source yet. Mainly because it's not easy to just clone it and get setup yet.

I'll try to give you an idea of what it does.

I have script called `portable.elv` that takes an argument from $args and calls a function from the loaded module `util = (use-mod ./modules/utils)`.

so `$ ./portable.elv install musl` calls `$util[-get-prefix~] musl`

`-get-prefix` then calls `vers = (-get-vers-ns musl)`
`-get-vers` searches for a file with the name of the 1st argument in the project path. Which is ./pkgs/system/musl/musl.elv. It loads this as a namespace to find the variable `latest` which in this case is 1.2.1. It then returns `put (use-mod ./pkgs/system/musl/1_2_1)`

The problem is that in ./pkgs/system/musl/1_2_1.elv, there is a call to `$util[-get-prefix]` so that I can get the right directory prefix for the package for use in the build description.

Hopefully this gives you an idea of what I'm trying to do. Again, this worked before the commit posted in the OP.

**Comment by xiaq** [comment]
So essentially you have a dispatcher module that can call a number of other modules dynamically. These modules might then need to call the dispatcher again for more dynamic dispatch. Is that a fair summary?

> Again, this worked before the commit posted in the OP.

I know, but it's more than a matter of just rolling back the change, or adding back support. The change in question was a step towards making access to namespaced names statically checked. I know it's possible to support circular dependencies and static namespace at the same time (TypeScript does it), but I'm sure it would complicate the implementation. That's why I'd really like to understand your use case of circular dependencies before deciding what's best.

I'll need to think about your use case a bit more. I marked this issue as blocking 0.15.0; in the meanwhile, I'd recommend you to run the old commit as a workaround.

**Comment by kolbycrouch** [comment]
Well sort of. Its a utility module that has a lot of functions dealing with the various phases of building a package etc. The way I get most of the values to work with, like the source url, name, license, revision, configure flags etc. is using a function that loads these package definitions (which are elvish scripts with only variables containing strings, maps, lists, closures etc) and outputs a namespace.

The problem is that sometimes, these package definitions use this utility module to find their own prefix for example. the `-get-prefix` function in the utility module has to take values from the package definition itself, which it loads as a module, causing this circular dependency for the packages that need to do this.

When I said it was working before, I just meant that it didn't exhibit any odd behavior to me. I didn't mean to demand any changes or rollbacks or anything.

Hopefully we can have this behavior in the future. This is the most elegant solution I could come up with, and although it's a niche use-case, I can see other ways this could be useful.

In the meantime I'll try to set my project up so that people can see a real example of it. I don't want to invest too much more time with this design if the behavior changes.

**Comment by krader1961** [comment]
Note that many languages either disallow circular imports (e.g., Go), or make them nominally invalid, at least when using the usual import pattern, but have awkward mechanisms to support them (e.g., C, Python).

The last time I dealt with circular imports was nearly a decade ago on a project written in Python that needed a new feature. The straightforward solution introduced a circular import. At the time the project had ~30K lines, excluding unit tests, and, of course, the new feature had to be implemented ASAP. We couldn't afford to refactor the code to eliminate the circular dependency. Instead we used a weak forward reference that was patched at run time to the correct referent. It was ugly and hard to understand; even by a Python expert. We eventually refactored the code to eliminate the circular dependency.

@kolbycrouch, It may be that your current solution is optimal (assuming Elvish allowed circular imports). However, if you google "circular dependency" you'll find that this (anti-)pattern is typically considered to be undesirable and the code that employs it should be refactored. Is there some reason `-get-prefix` can't be moved into a separate module that both `bug1` and `bug2` use? Another solution would be to require an "init" function in module `bug2` that `bug1` can call after the `use` to pass the value of `$util[-get-prefix~]`.

Also, why do `util = (use-mod ./modules/utils)` rather than `use ./modules/utils util`?

**Comment by kolbycrouch** [comment]
It doesn't matter where the `util` module is. The package module is using `util` to call itself. I've thought of several ways to refactor, but I'd have to sacrifice the flexibility I'm currently getting. At that point, I'd might as well consider using python.

**Comment by xiaq** [comment]
It turned out to be not so difficult to add back support for circular dependency, so I am going to do that.

However, @kolbycrouch, after revisiting your use case, I am actually no longer sure why it would result in a circular import dependency at all. Circular dependency between modules is not problematic per se; only **import-time** circular dependency is. If your code is like this:

```
# util.elv
fn get-prefix [mod]{
  m = (use-mod pkgs/$mod.elv)
  // do something with $m
}
# pkgs/musl.elv
use util
util:get-prefix musl

# REPL
use util
util:get-prefix musl
```

There is no import-time circular dependency. When REPL imports `util`, it does not import `pkgs/musl.elv`. It only imports `pkgs/musl.elv` when `util:get-prefix`, at which point `util` is already loaded, so the `use util` in `pkgs/musl.elv` will just alias the loaded module.

But maybe your use case is more complex than this. It'd be good if you could either publish your code or construct a minimal example that can accurately represent the problem.
