### ISSUE TITLE
Unable to bind Ctrl-J, Ctrl-M

### ISSUE THREAD

**Issue by gergelyk** [elves/elvish#1244]
I would like these to assign Ctrl-J and Ctrl-M to location & navigation dialogs respectively.

If I open clean session of elvish and do:
```
edit:insert:binding[Ctrl-M] = $edit:navigation:start~
```
After hitting Ctrl-M my caret goes to the new line with new prompts (as when we hit ENTER).

If I open clean session of elvish and do:
```
edit:insert:binding[Ctrl-J] = $edit:location:start~
```
Hitting Ctrl-J works as expected. The problem is however that ENTER itself gets mapped to `$edit:location:start~` as well.

Could you help me to understand why these keys cannot be assigned as I would expect?

**Comment by SolitudeSF** [comment]
thats the limitation of terminals. bytes corresponding to Ctrl-M and Ctrl-J are used for carriage return and newline.

**Comment by krader1961** [comment]
In case there is still any confusion I find it's often useful to use the `od` command to understand what particular keys send. In the example below I've pressed the following keys:  Tab, Ctrl-I, Enter, Ctrl-M, Ctrl-D.

```
> od -tx1z


0000000 09 09 0a 0a                                      >....<
0000004
```

Notice that Tab and Ctrl-I send the same character as does Enter and Ctrl-M. You could, in theory bind Ctrl-M to `$edit:navigation:start~` but then you'd need to bind some key other than Enter to the `$edit:smart-enter~` command.

P.S., You generally can't bind Ctrl-J and Ctrl-M to separate functions because of "icrnl" mode being enabled in the tty driver which makes them equivalent.

**Comment by plaukiu** [comment]
elvish could implement Kitty terminal support...

**Comment by xiaq** [comment]
> elvish could implement Kitty keyboard protocol support...

Thanks, I filed #1797 for that.
