### ISSUE TITLE
Redir from values and to variables

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#131]
`pipeline <= values >= variables` is like `variables=`put values | pipeline``.

**Comment by xiaq** [comment]
Redir from values with #737: `[a b c] | ...`

Redir to variables: `... | v = [(all)]`

**Comment by kwshi** [comment]
I am *maybe* in favor of the piping to store to variables, but not as much in favor of piping *from values*, since it doesn't really read naturally.  I've gotten accustomed to reading left-to-right pipelines as a sort of "flow of data" thing, where the `|` reads like an operator that means "passes data to".  Introducing the `<=` operator in this manner breaks that flow, since then data is jumping from right to left (`values` to `pipeline`) and then back over to the right (`variables`).
