### ISSUE TITLE
Too Many Open Files

### ISSUE THREAD

**Issue by fennewald** [elves/elvish#1315]
Another Issue I'm not 100% needs to be a github issue.

Using `aws-cli`, I was trying to match a specific pattern for filenames. I wrote the following snippet that recursively opens aws-cli, and calls an ls request. aws-cli takes a few seconds to authenticate, so this command quickly balloons up to thousands of pipelines (about 200000 total endpoints with average folder depth of 4-5). Should I still be getting the too many open files issue? Is there a local way to resolve?
```
#!/bin/elvish

use re
use str

fn list_path [bucket path]{
    aws s3 ls $bucket'/'$path ^
    | peach [line]{
        if (re:match 'PRE' $line) {
            dir = (str:trim-space (str:trim-prefix (str:trim-space $line) 'PRE'))
            list_path $bucket $path$dir
        } else {
            tokens = [(str:split ' ' $line)]
            date = $tokens[0]
            time = $tokens[1]
            size = $tokens[2]
            file = $tokens[3]
            put [&date=$date &time=$time &size=$size &bucket=$bucket &path='/'$path$file]
        }
    }
}

aws s3 ls ^
| eawk [line _ _ bucket]{ put $bucket } ^
| each [bucket]{ list_path $bucket ''} ^
| each [obj]{
    if (re:match '2021.03.31' $obj[path]) {
        put $obj
    }
}```

**Comment by krader1961** [comment]
> Should I still be getting the too many open files issue?

Yes, given the conditions you described. Each pipe requires a pair of file descriptors. Even if issue #648 were resolved you would probably still experience problems since your program creates pipes in an exponential pattern. A common solution is the worker pool design pattern and a queue (e.g., a Go channel) but that can't currently be expressed in Elvish. At least not without jumping through some hoops (e.g., using the `to-json` and `from-json` builtins) since only byte streams are currently exposed as objects that can be assigned to variables (see the `pipe` builtin).

**Comment by fennewald** [comment]
Closing because relevant issues have their own issue.
