### ISSUE TITLE
We need a "compare" command independent of "order"

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1347]
I have been working on an Elvish way to compare values in order to implement [semantic version](https://semver.org) comparisons. The [default comparison function](https://github.com/elves/elvish/blob/9981b2a777961f3669200e9b890c16cbb6935d3d/pkg/eval/builtin_fn_container.go#L899) used by the `order` command appears to do what I want. It is a shame that I have to reinvent that wheel using Elvish commands.

**Comment by zzamboni** [comment]
In case it's useful, note that I wrote also a module for semantic version
comparisons:
https://github.com/zzamboni/elvish-modules/blob/master/semver.org

**Comment by krader1961** [comment]
@zzamboni, Your implementation is pretty good but doesn't correctly handle prerelease and build metadata. See [the spec](https://semver.org/) and this [solution](https://github.com/maxhauser/semver/blob/master/Semver/SemVersion.cs) which appears to correctly implement the spec.

**Comment by krader1961** [comment]
@zzamboni, Also, your version doesn't correctly handle invalid semver strings. In particular, it is overly permissive by treating strings like "1.0.0" and "1.0" as equal. While at the same time not handling a very common, but incorrect, inclusion of "v" or "V" as a semver prefix. A mistake made by the current elvish implementation: https://github.com/elves/elvish/blob/fc887b246683ef849f17d4070cfca5ba03800af0/pkg/buildinfo/buildinfo.go#L18. I still think your module is awesome but it points out why a solution for the [semver issue](https://github.com/semver/semver/issues/718) I opened is so important. Specifically, the semver project should include a file of test cases so that every implementation can be validated against that implementation agnostic set of test cases.

**Comment by zzamboni** [comment]
@krader1961 I think my implementation correctly handles prerelease strings, e.g. using the example from the SemVer spec:
```
'semver:<' 1.0.0-alpha  1.0.0-alpha.1  1.0.0-alpha.beta  1.0.0-beta 1.0.0-beta.2 1.0.0-beta.11 1.0.0-rc.1 1.0.0
▶ $true
```
See also a whole bunch of other tests at https://github.com/zzamboni/elvish-modules/blob/master/semver.org.

You are correct that a missing trailing numbers (MINOR or PATCH) are considered as zeros. In my defense, this is even documented 😉: https://github.com/zzamboni/elvish-modules/blob/master/semver.org#main-comparison-function. The spec says that all three components MUST be there, so I guess this is a bug. I've opened https://github.com/zzamboni/elvish-modules/issues/17

Build metadata: this is also a bug, it should be ignored. I've created https://github.com/zzamboni/elvish-modules/issues/16

Invalid things like the `v` at the beginning - what do you mean by "doesn't correctly handle"? You mean an error should be produced? At the moment this is allowed because the module uses string comparison when needed, and numeric otherwise. I suggest in https://github.com/zzamboni/elvish-modules/issues/17 that it might make sense to have a `&non-strict` flag or variable which allows/disallows parsing things like that.

Thanks for the feedback. PR's welcome! 😉

**Comment by krader1961** [comment]
> Invalid things like the v at the beginning - what do you mean by "doesn't correctly handle"?

@zzamboni, A "v" (or "V") prefix is technically invalid in a semver string. However, I would argue it should be silently ignored since it is all too common for an otherwise valid semver string to include that prefix. I didn't actually test that your implementation does so. I simply inferred it didn't from the documentation. If (or when) your implementation silently ignores a "v" prefix that is notable enough to warrant a mention in the documentation and why it is different from how every other invalid semver string is treated.

**Comment by zzamboni** [comment]
@krader1961 regarding your original issue, please note that as part of my `semver` module I implemented a compare function like the one you want. I agree this might be useful to have in Elvish:

The `-signed-compare` function compares two values using a function which takes two values and returns -1, 0 or -1 to represent the order of the two values.

```
fn -signed-compare [ltfn v1 v2]{
  util:cond [
    { $ltfn $v1 $v2 }  1
    { $ltfn $v2 $v1 } -1
    :else              0
  ]
}
```

About SemVer comparison, please check out https://github.com/zzamboni/elvish-modules/pull/18, in which I address all the bugs mentioned above.
