### ISSUE TITLE
Go Report Card Grade

### ISSUE THREAD

**Issue by ChiefMateStarbuck** [elves/elvish#1353]
Elvish is currently receiving an **F** on its [go report card](https://goreportcard.com/report/github.com/elves/elvish). Is increasing the grade an interest to the elvish team?

**Comment by ChiefMateStarbuck** [comment]
Apologies. goreportcard just needed a manual refresh. Current report card grade is now A+

**Comment by krader1961** [comment]
@ChiefMateStarbuck, the A+ rating is what I would have expected given my experience with this project over the past three years and a senior SWE. The "Go Report Card" project is great but it really needs to drop the `golint` section of its reports. Or at least move it to a "this might be interesting" section at the bottom of the report and otherwise not include its metric in the overall assessment. The `golint` tool is no longer being actively maintained and its output is highly subjective.
