### ISSUE TITLE
Clarification on licence for elvish

### ISSUE THREAD

**Issue by vendion** [elves/elvish#138]
This really isn't an issue as much as it is a question, I'm working on getting Elvish in Arch Linux's AUR and PacBSD's PUR and need to state which license this project uses.  Looking at the LICENSE.md file it looks like it's under the BSD 2-cause license.  Is this correct?

**Comment by vendion** [comment]
Never mind, looks like you beat me to uploading it to the AUR, and from there you have that it is MIT licensed.  That pretty much clarifies my question.

**Comment by xiaq** [comment]
Ha it's actually BSD-licensed. A friend of mine did that and added me as co-maintainer afterwards. I need to fix that.

Thanks for your interest in elvish though! I am having much fun building it, and I hope you will have much fun playing with it.

**Comment by vendion** [comment]
I've been enjoying using elvish very much, and impressed how far the project has come along.   Hopefully when I can find some free time I could help contribute to it.  One area of interest would be to try and add Vi/Vim keybindings to Elvish.

**Comment by xiaq** [comment]
@vendion vi/vim keybinding is something I would love to have but it's not very high on my priority queue, so helping hands are very welcome! By the way, be sure to start a discussion before you start working on the code since I might refactor the editor in the near future and it's important to be coordinate.
