### ISSUE TITLE
Feature request: command to find location of rc.elv file

### ISSUE THREAD

**Issue by ajeetdsouza** [elves/elvish#1385]
Now that https://github.com/elves/elvish/issues/383 has been fixed, the location of `rc.elv` is less obvious. It would be nice if there was an Elvish command to determine the location of `rc.elv`. Other shells that vary the location of their config files based on OS or environment variables already provide a way to do this:
- PowerShell: `echo $profile`
- Nushell: `config path`

**Comment by krader1961** [comment]
Without commenting on whether or not this should be implemented I'll note that you can capture this information today when *rc.elv* is executed using the [`src`](https://elv.sh/ref/builtin.html#src) builtin. For example, by adding something like this to your *rc.elv*: `var rc-elv-path = (src)[name]`.

**Comment by zzamboni** [comment]
Expanding on this feature request, I think it would be nice to have variables or functions which contain all the different directories of the XDG spec. If the user is still using the `~/.elvish/` directory, then they could all point to the same directory.

This would significantly simplify the work of module authors when there is a need to store data somewhere.

**Comment by krader1961** [comment]
I opened [issue #1420](#1420) when I was surprised that the *~/.config/elvish/rc.elv* I synced from my macOS to Windows 10 system was not read on the latter system. I might have found the problem, without resorting to add a `fmt.Printf()` call to the source, if this issue were resolved. However, in light of the fact that Elvish on MS Windows doesn't (currently) recognize XDG paths is a strong suggestion that the names of the variables to expose this information should be agnostic with regards to the XDG spec. Rather, the names should reflect the use of each value by Elvish.

**Comment by krader1961** [comment]
Note that building elvish from HEAD as I type this will result in this warning if you `use github.com/href/elvish-gitstatus`:

```
Warning: ~/.elvish will be ignored from Elvish 0.20.0.
```

That is because that module has a hardcoded path: `var appdir = ~/.elvish/package-data/gitstatus`. As I discuss in issue #832 third-party modules really need a way to ask Elvish which dir it is using without having to implement the logic documented in https://elv.sh/ref/command.html.

**Comment by krader1961** [comment]
FWIW, I've been working on implementing this feature. I've decided that the var for this issue should be named `platform:config-home`. Also, a companion `platform:state-home` (corresponding to where the Elvish database file is located) also be introduced for use by modules like `github.com/href/elvish-gitstatus` for its data that normally should be private to a particular machine. I intend to leave exposing [module search paths](https://elv.sh/ref/command.html#module-search-directories) for a future change in order to keep the initial change as small as possible.
