### ISSUE TITLE
[FR] provide a way to check if a shell variable exists

### ISSUE THREAD

**Issue by ajeetdsouza** [elves/elvish#1395]
Elvish provides a way to set, get, and check for existence of environment variables (`set-env`, `get-env`, `has-env` respectively), but there's no way to check for existence of shell variables. Trying to catch the exception using `?($x)` doesn't work either, since a missing variable throws a compile error.

Possible implementation: since `edit` already provides `add-var`, we can provide `has-var` as well as a `get-var` that does not throw a compiler error if the variable doesn't exist.

**Comment by krader1961** [comment]
@ajeetdsouza, It is unclear what you are proposing. Elvish is different from POSIX shells like bash. Elvish does not allow using a variable that has not been defined in the current, or an enclosing, scope. The environment variable space, `E:`, is special in that Elvish can't know a priori when compiling an Elvish program whether a particular variable is valid; i.e., has been defined. But that isn't true for other variables; i.e., those that your Elvish program defines. In other words, even if there was a way to test if a non-env var existed it wouldn't be useful since using the var will cause a compile time error.

What you seem to be proposing is something like a hypothetical `has-var` telling the compiler that any subsequent use of the var should not be considered an error even though there was no definition of the var in a reachable scope. I don't see how that would be useful. @ajeetdsouza, Can you provide a concrete example for how such a command would be useful?

**Comment by ajeetdsouza** [comment]
In an REPL, try:

```
$ edit:add-var 'foo' '123'; echo $foo
compilation error: variable $foo not found
```

Alternatively, try:

```
$ eval "edit:add-var 'foo' '123'\necho $foo"
Exception: compilation error: variable $foo not found
```

---

My use case is -- I'm working on [zoxide](https://github.com/ajeetdsouza/zoxide)'s [Elvish plugin](https://github.com/ajeetdsouza/zoxide/blob/main/templates/elvish.txt). The plugin is loaded using `eval (zoxide init elvish | slurp)`, and I'm trying to find a way of detecting if zoxide is being loaded twice by accident.


In other shells, what I typically do is check if a shell variable called `__zoxide_hooked` exists. If it does exist, I don't load anything, otherwise, I load the plugin and set the variable. This is currently not possible with Elvish, since checking for a variable that doesn't exist is an error.

The alternative is to use an environment variable, but that interferes with subshells (a subshell wouldn't load the plugin, since `__zoxide_hooked` is already set in the environment).

**Comment by krader1961** [comment]
> In an REPL, try: ....

Did you try doing that with the two statements on separate lines? This works for me:

```
> edit:add-var 'foo' '123'
> echo $foo
123
```

The reason you're getting a compilation error is because at the time your code block is compiled the `edit:add-var` has not been executed. Thus the reference to the var in the `echo` statement in the same code block was invalid.

> The plugin is loaded using eval (zoxide init elvish | slurp)

Using `eval` is almost always a mistake in Elvish (I recognize it is a necessary evil in POSIX shells).

Note that the `edit:add-var` command is semi-magical in that it aliases a command in the interactive namespace to a function in a different namespace (i.e., a module) loaded via the `use` command.

One solution to your problem would be the resolution to issue #999 to enumerate all known namespaces. If the zoxide module was loaded that mechanism would allow you to detect that fact. A solution that works today is to leverage the `$E:SHLVL` variable. Assign that value to a hypothetical `$E:__zoxide_hooked ` variable and test if it is identical to `$E:SHLVL`. However, I don't understand why such mechanisms are needed. An Elvish "subshell" will, by definition, need to load the zoxide plugin via the relevant `use` or `eval` command in the users *~/.config/elvish/rc.elv* script. And those statements don't need to worry about whether the zoxide support has been initialized unless you want to guard against the user making a mistake by trying to initialize zoxide support more than once (in which case the `$E:SHLVL` solution seems appropriate). Perhaps I don't know what you mean by "subshell".

**Comment by ajeetdsouza** [comment]
> A solution that works today is to leverage the $E:SHLVL variable. Assign that value to a hypothetical $E:__zoxide_hooked variable and test if it is identical to $E:SHLVL.

@krader1961 that's a great idea, thanks! You guessed correctly -- by subshell I meant a shell launched within a shell, `$E:SHLVL` takes care of that for me.

Btw, have you considered deprecating `set-env` and `unset-env`, since you can just use `set` and `del` with the `E:` namespace?

**Comment by krader1961** [comment]
> Btw, have you considered deprecating set-env and unset-env, since you can just use set and del with the E: namespace?

The `set-env` command can be used to set an env var indirectly while `set` cannot:

```
> var v = WTF
> set-env $v hello
> env | grep WTF
WTF=hello
> set E:$v hello
compilation error: 4-8 in [tty]: lvalue may not be composite expressions
compilation error: lvalue may not be composite expressions
[tty 35], line 1: set E:$v = hello
> var v = E:WTF
> set $v = hello
compilation error: 4-6 in [tty]: lvalue must be valid literal variable names
compilation error: lvalue must be valid literal variable names
[tty 38], line 1: set $v = hello
```

Same for `unset-env` and `del`. Again, this reflects the fact that the `E:` namespace is special and independent from the regular variable scopes.

https://github.com/ajeetdsouza/zoxide/blob/ecc64be909fcbc8b0d1733618ad3e96dbd0f7f0a/templates/elvish.txt#L28-L31

You don't need that block of code. Elvish guarantees that `E:SHLVL` will be initialized to an integer. If it isn't set when Elvish starts it is set to one:

```
> env -u SHLVL elvish
> echo $E:SHLVL
1
```

It looks like the reason you're doing this is to ensure these two assignments only occur once:

https://github.com/ajeetdsouza/zoxide/blob/ecc64be909fcbc8b0d1733618ad3e96dbd0f7f0a/templates/elvish.txt#L38-L40

Another way to do that would be to turn your code into a standard Elvish module that the user imports by adding an appropriate `use` command to their *~/.config/elvish/rc.elv*. If the `use` is run a second time it is a no-op. That would be more idiomatic and avoid the problems with `eval`.

**Comment by krader1961** [comment]
The one interesting use case for something like a `has-var` command is testing if a function has been defined. That, however, should instead be implemented by support for additional name spaces to be recognized by commands like `keys` and `has-key`. See, for example, issue #668 and #1028.

**Comment by ajeetdsouza** [comment]
> The `set-env` command can be used to set an env var indirectly while `set` cannot.

I'm able to use `set` and `del` to modify `env`:

```
~> env | grep foo
Exception: grep exited with 1
[tty 10], line 1: env | grep foo
~> set E:foo = "xyz"
~> env | grep foo
foo=xyz
~> del E:foo
~> env | grep foo
Exception: grep exited with 1
[tty 15], line 1: env | grep foo
```

---

> You don't need that block of code. Elvish guarantees that E:SHLVL will be initialized to an integer. If it isn't set when Elvish starts it is set to one:

That's fair enough, I'll remove it.

---

> It looks like the reason you're doing this is to ensure these two assignments only occur once. Another way to do that would be to turn your code into a standard Elvish module.

zoxide has a very small amount of shell code. The shell code is just there to call the binary, where the main work is done. This comes with a lot of advantages -- Rust scales better, runs faster, and integrating new shells is very easy.

However, this also means that the shell code is linked to the binary in a backwards-incompatible way. If the user upgrades the zoxide binary, they must also simultaneously upgrade the shell code to exactly the same version. Rather than leave this up to the user, I found it much simpler to just bundle the shell code within the binary itself.

I considered creating a package that essentially just calls `eval (zoxide init elvish | slurp)`, but the problem with that is the user might have custom options (e.g. `zoxide init elvish --cmd j --hook prompt`). Do let me know if there's still a way to do this that I'm not seeing.

Related: [starship](https://github.com/starship/starship#elvish) also does something very similar.

---

Btw, thanks @krader1961 for reviewing my code, I'm not a full-time Elvish user so I really appreciate it!

**Comment by xiaq** [comment]
> I'm able to use set and del to modify env:

The `set-env` command works with a dynamic environment variable name, `set` does not.

I believe the original request can be closed as a dup of #668 - it should be possible to query the local namespace with `has-key $local: some-variable-name`.

**Comment by krader1961** [comment]
> I'm able to use set and del to modify env

Yes, but not using a variable reference to hold the env var name to be modified as shown in my examples but not yours. That is, an indirect (or dynamic) var name is allowed by `set-env` but not `set`.

@ajeetdsouza, Is there anything about your original request that hasn't been addressed? In particular, note that it looks like this is effectively a duplicate of issue #668.

**Comment by ajeetdsouza** [comment]
Nope, I think #668 would fix it. Thanks a lot for the help!
