### ISSUE TITLE
That `use` does not support absolute paths should be documented or supported

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1400]
@rdw20170120 questions why the `use` builtin does not allow absolute paths. It is also unclear to me why `use` does not support absolute paths. The reason (security?) absolute imports are not supported should be documented or the machanism should be modified to allow absolute paths.

**Comment by krader1961** [comment]
Looking at the relevant source code I don't see any comments that explains why absolute paths are not support by `use`. It looks like a simple oversight. I've already created a patch that supports absolute paths with `use`. Updating the unit tests and documentation is the hardest part of this change. Pull-request forthcoming.

**Comment by krader1961** [comment]
Augmenting the unit tests was straightforward and added coverage of an unrelated statement (when no module specs were matched). As usual for this type of change improving the documentation is the hard part.

**Comment by xiaq** [comment]
Absolute paths are not portable between machines. Module references should always be relative in some sense - relative imports are relative to directory of the module itself, non-relative imports are relative to the module search paths.

**Comment by rdw20170120** [comment]
While @xiaq makes an important point, I would like to describe a crucial use case and practice of which he seems to be unaware.

In my projects and repositories, I solve this portability problem using _**absolute paths anchored to a variable**_, controlled by my project.  In other words, my absolute paths are _**dynamic**_.

For example, when I work on one of my projects, my initial script defines an environment variable to hold the absolute path of the project repository root directory.  This is the first step of my "project activation" script.  This would look something like (in Bash) `export ProjectRoot=${PWD}`.  My projects typically involve a handful of such environment variables to manage _**ALL**_ the file and directory references in my scripts and applications.  So, one of my scripts might call another script as something like (in Bash) `source ${ProjectRoot}/DIR/SCRIPT.bash`.

If a script references another nearby script, I use a dynamic absolute path for the reference.  For example, in the calling script (and all my scripts) I define a local variable holding the absolute path of the script's directory as something like (in Bash) `local MyDir=$(absolute_path_of $(dirname $0))`--where `absolute_path_of` is a function that finds the canonical absolute filesystem reference of the argument.  I reference the called script using that local variable to anchor its absolute path as something like (in Bash) `source ${MyDir}/DIR/SCRIPT.bash`.

As a consequence of these best practices, my projects are completely portable.  Someone can clone the project repository to _**any path on any machine**_, and everything is guaranteed to still work.  On the rare occasion that my project needs to reference something outside the project repository, I handle that explicitly via environment variables defined in machine-specific configuration.

I avoid relative paths religiously.  The Elvish-supported syntax of `use ./DIR/MODULE` or `use ../DIR/MODULE` is almost completely useless to me.  I would never invoke a script that way from within another script.  There are several reasons.

- It can be confusing to the user, since it is not always clear to the user when the path is relative to the calling script and when it is relative to the current working directory.  I avoid such confusions.  I avoid forcing the current working directory just to make the script work because I do not want to limit my scripts or my users.  Therefore, my scripts work as designed regardless of the current working directory.
- When troubleshooting script execution, all my traces and error messages show the absolute paths.  The user is never forced to attempt to interpret relative paths on-the-fly.
- A code base with many relative paths is very fragile, particularly in the face of refactoring.  I prefer the freedom to restructure my code base without manually editing numerous relative paths.  That is wasted labor, and prone to error.
- I observe that absolute paths anchored by a variable communicates my intentions FAR better.  A relative path might get the job done, but it does not tell the reader anything about _**WHY**_ the reference is relative in that particular case.  Using a variable to anchor an absolute path encourages me to communicate the intention with a meaningful variable name.  That facilitates refactoring and extension by clearly showing reasons why some things should move when others should not.  Absolute paths anchored to variables make explicit the relationships that relative paths only imply and therefore leave hidden.

So, if you decline to make `use` work with absolute paths, that would force me to break a fundamental practice and it would affect all of my code.  I might be able to work around it, but it would likely be an ugly hack that I would avoid.  Elvish would then be useless to me.  Of course, it is certainly your right as the author and maintainer to implement as you please.  I would respect your decision, and move on.

**Comment by xiaq** [comment]
I do have a workspace mechanism in mind for the module system. The current module searching behavior is akin to having a single workspace for each user.

**Comment by rdw20170120** [comment]
Ohhh, that could be very cool...

**Comment by krader1961** [comment]
> Absolute paths are not portable between machines.

In the general case that is true. For specific users it is false. It also begs the question why `builtin:cd` allows a string literal or var holding a string. While `use` only supports a string literal. Why should I have to write this:

```
# A bunch of statements that ultimately set `$project-dir` to an absolute path name.
put var cwd = $pwd
cd $project-dir
use ./elv-module
cd $pwd
```

Rather than this:

```
# A bunch of statements that ultimately set `$project-dir` to an absolute path name.
use $project-dir/elv-module
```

In both of the above scenarios I assume we're talking about a project that supports Elvish via its `use` command. Such a project will, by definition, use relative imports for everything other than those imports meant to be performed by the user of the project. Whether the user first does `cd $project-dir` followed by `use ./something` is 100% equivalent to `use $project-dir/something`. Except that the latter is simpler and less error prone.

**Comment by krader1961** [comment]
> Why should I have to write this....

/Face-palm on my part

One scenario is if the `use`'d (i.e., imported) Elvish modules want to use artifacts relative to their own location (by which I **do not mean** the Elvish `use` command). In other words, they want to use filesystem based relative paths rather than absolute paths based on a possibly un-exported `$project-dir` variable. How best to reconcile these scenarios is TBD.

**Comment by rdw20170120** [comment]
@krader1961 said:
> Such a project will, by definition, use relative imports for everything other than those imports meant to be performed by the user of the project.

Before that, I said:
> I avoid relative paths religiously. The Elvish-supported syntax of use ./DIR/MODULE or use ../DIR/MODULE is almost completely useless to me. I would never invoke a script that way from within another script.

So I must wholeheartedly disagree.  Using absolute or relative paths is a _**design decision that should be left to the user**_.  I cannot imagine EVER needing to _**override**_ the user's design decision by specifically writing code that forbids one or the other, with ONE exception:  a relative path should be forbidden if there exists no clear design choice regarding the anchor to which it is relative.  In that case, your code has no anchor against which to resolve a provided relative path, so it must forbid relative paths in favor of an absolute path (resolved by the caller).  In most cases, though, there is a clear "current" SOMETHING (e.g., working directory, executing script) that can serve as the obvious anchor.

_**Why on Earth would you forbid absolute paths?**_  What is the point?  Why would you care?  You need an absolute path to cache the module anyway.  How does _**forbidding**_ absolute paths serve anybody?

As for the question of how a module will reference other filesystem artifacts relative to the imported module, that is trivial.  A module can get its own location via `src[name]`, from which it can compute relative references as desired.  I already do this in my modules as a routine step.  However, I ALWAYS render the result as an absolute path.

If the imported module wants to reference filesystem artifacts relative to some other anchor (e.g., `$project-dir`), well then the anchor needs to be published (exported, or something similar).  That is why my activation script publishes just such an anchor variable as its first step.

**Comment by xiaq** [comment]
@krader1961 the reason for not allowing variables is that `use` will be getting compile-time checks in future - for example, building a list of valid symbols in that module and statically checking access to them (access to symbols in modules are not statically checked today; they should be), and the compiler has no knowledge of the value of variables. The "project root" use case is a valid one and I plan to address it via a dedicated mechanism.

Not responding to every point in detail, but `use` is supposed to be an opinionated mechanism for the module system, not for arbitrary code execution concerns - use `eval` for the latter.

**Comment by rdw20170120** [comment]
Thanks, @xiaq, for sharing your intentions.  A separate dedicated mechanism makes sense.

**Comment by krader1961** [comment]
@xiaq: That this won't work in the future should probably be documented now:

```
cd /tmp
use ./x
```

Assuming */tmp/x.elv* exists. 

Closing since there appears to be a clear vision for how to solve the underlying problem in a different, more Elvish, manner. However, it would still be a good idea to document ASAP that the current semantics of `use` will change in the future.

**Comment by xiaq** [comment]
@krader1961 `cd /tmp; use ./x` only works in interactive mode and is probably a misfeature.

The module system is a bit underdocumented in general; I'll revamp that section of the doc after the work on the workspace/project root mechanism is implemented.
