### ISSUE TITLE
Add command to remove consecutive duplications (like the UNIX `uniq` command)

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1453]
I was creating a pipeline involving `grep` to find all the mentions of `rc.elv` that weren't Go imports and noticed it would have been useful if `builtin:order` had a `&uniq` (or `&unique`) option to eliminate duplicates. Also, for that particular scenario it would have been sufficient if a `builtin:uniq` was available that could filter the value stream since I didn't really need to order (sort) the values since the duplicates would always appear adjacent to each other.

**Comment by xiaq** [comment]
I don't see any substantial advantage in adding an option to `order`. Adding another command after it is simple enough - `order &uniq` isn't any shorter than `order | uniq`.

Also regarding the name - it's better called something different from `uniq` to avoid shadowing the external command. This is why the sorting command is `order`, not `sort`.

I also never liked the name `uniq` - it can mislead people into assuming that it will remove all duplications, whereas it only removes consecutive duplications. Go'e experimental slice package calls the same functionality "compact" (https://pkg.go.dev/golang.org/x/exp@v0.0.0-20220218215828-6cf2b201936e/slices#Compact). This name is a bit vague but at least it's not misleading.

**Comment by krader1961** [comment]
The advantage of a "unique" option to the `order` builtin is better performance, but I'll admit that is a weak argument since it is a micro optimization given the overall performance of a shell like Elvish. Hence why I opened this with a proposal for a new command that could operate on a stream of values to eliminate identical consecutive values similar to how the POSIX `uniq` command handles lines in byte streams. I agree about using a builtin name other than `uniq`; both to avoid clashing with the external command and because the traditional name is misleading (albeit only mildly). I don't like "compact" but I don't have a better suggestion at this time that isn't excessively verbose.

Does a new command to eliminate successive duplicate values have to be in the "builtin" module? Should we consider introducing a new module for such operations that would minimize the likelihood of clashing with an external command of the same name? What would that mean for other, relatively recently introduced, commands added to the "builtin" namespace such as `order`? I'm not really a fan of this idea but think it warrants some discussion since it would minimize future clashes with external commands.

**Comment by xiaq** [comment]
It's fine living in the builtin namespace for now. Most of the commands that operate on streams are in the builtin namespace.

**Comment by krader1961** [comment]
Reading this issue again I am still of the opinion that a `&unique` or `&compact` option should be added to the `builtin:order` command. Yes, it is a micro optimization, but such things accumulate into becoming significant optimizations. There should also be a `compact` command that can be chained in a pipeline.

**Comment by krader1961** [comment]
I'm inclined to prefer `dedupe` rather than `compact` as the name of both a standalone command and the `order` option. Googling "dedupe" returns significantly more relevant matches, such as https://en.wikipedia.org/wiki/Data_deduplication, than the term "compact".

**Comment by xiaq** [comment]
> I'm inclined to prefer dedupe rather than compact as the name of both a standalone command and the order option. Googling "dedupe" returns significantly more relevant matches, such as https://en.wikipedia.org/wiki/Data_deduplication, than the term "compact".

Except that the `dedupe` command does **not** perform data deduplication in its plainest meaning, it only eliminates consecutive duplicates.

If there is a command that does eliminate all duplicates, `dedupe` would be an appripriate name.

**Comment by xiaq** [comment]
Here is a system to judge command names:

- A good name reveal what a command does unambigously to people who've never used it.
- An OK name may not be super enlightening to people who've never used it, but is not actively misleading, and can be easily remembered after they look it up.
- A bad name misleads people to think that the command does something else.

Most Unix commands are in the lower end of the "OK" level. However, the `uniq` command is bad, since it is actively misleading, as is the proposed name of `dedupe`. People who've never used `uniq` and `dedupe` are very unlikely to correctly guess that they only eliminate consecutive duplicate values.

The name `compact` is in the "OK" level, and argubly in the higher end. It's not obvious what it does, but it's also not actively misleading. People will look it up, and the visual image of "compacting" duplicate values makes it easy to remember afterwards.

**Comment by hanche** [comment]
A quick suggestion, similar to `compact` but perhaps marginally better: `tighten`.

**Comment by xiaq** [comment]
> A quick suggestion, similar to `compact` but perhaps marginally better: `tighten`.

I don't have a very strong opinion between them, but since https://pkg.go.dev/golang.org/x/exp/slices#Compact uses "compact", the terminology is likely to gain some popularity among Go programmers, so I'd stick to `compact`.

Digging a bit into the history around the name Go chose, rsc stated [here](https://github.com/golang/go/discussions/47203#discussioncomment-1005187) that "[the name is] *not* in other language's APIs, so we get to define the word without preexisting connotations", and I'd trust rsc's research that there really is nothing else notable that is already called "compact".
