### ISSUE TITLE
Symbols Clobbered by Elvish?

### ISSUE THREAD

**Issue by zQueal** [elves/elvish#1460]
I was following #1456 and just updated elvish to master.

In older versions it was working perfectly fine, but now, icons (from logo-ls) are clobbered when output in elvish after being filtered through another application via pipe;

```elvish-transcript
❯ ls | grep .warp
ï?â ?.warp/
```

Normally using `ls` works perfectly fine;

```elvish-transcript
❯ ls .warp
⠀__LAST_VISITED__  ⠀Downloads  ⠀exe  ⠀scripts  ⠀utilities  ﬒⠀.vim
```

I tried outside of elvish and it seems to work fine. Only environment change was the updating of elvish.

--------------------------

OS: Windows x64
Term: Windows Terminal Preview (1.12.2931.0)
Elvish: a8844a34f83a0360577beab60c3214c27ac09b09

`ls | grep .warp | od -tx1`
```txt
0000000 1b 5b 33 38 3b 32 3b 32 32 34 3b 31 37 37 3b 30
0000020 37 37 6d ef 9d 95 1b 5b 30 6d e2 a0 80 1b 5b 30
0000040 6d 2e 77 61 72 70 2f 20 20 20 20 20 20 20 20 20
0000060 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20 20
*
0000160 20 20 20 20 20 20 20 20 20 20 20 20 20 1b 5b 30
0000200 6d 0a
0000202
```

This _may_ be an issue with windows, but it didn't present itself until I updated Elvish a few hours ago.

**Comment by zzamboni** [comment]
This sounds more like a Terminal or font problem. For me in iTerm2 it works fine.
![image](https://user-images.githubusercontent.com/32876/147792362-fe2e2f2a-5314-4175-9c47-50319db144c2.png)

**Comment by krader1961** [comment]
@zQueal, Are you, by any chance, doing this on MS Windows? In any case it would help if you updated your problem statement to include the Elvish version, `$TERM` value, OS, and terminal you're using.

Your first example looks like either malformed UTF-8 or your terminal isn't correctly rendering UTF-8. Please also show the output of `ls | grep .warp | od -tx1z` (or equivalent so we can see the actual byte values).

Your second example doesn't show the expected emojis as seen in @zzamboni's output. Which is why I'm guessing you're working with Windows.

**Comment by zQueal** [comment]
Updated.

I won't deny it's a Windows issue, however, like I said, it never showed up until I updated Elvish a few hours ago.

**Comment by krader1961** [comment]
On Windows the tty modes are not correctly restored when an external command exits. I'd bet $10 it (or a closely related problem) is the cause of your problem. I started working on a fix a year ago but never got around to finishing it since I don't use Windows except for testing stuff like this. I guess I should dust the cobwebs off the fix I started working on and finish work on it.

**Comment by zQueal** [comment]
It sounds like it affects a really small number of people, so I'm prepared to wait for a fix, but it's nice to know one is in the works.

Appreciate the help!

**Comment by krader1961** [comment]
The reason your copy/paste in the original version of your second example showed weird chars is because the output contains two UTF-8 sequences:

* `ef 9d 95` is code point U+F755 which is in the ["private use area"](https://www.compart.com/en/unicode/U+F755). In other words, it has no fixed meaning which is why my browser showed it as an empty rectangle.

* `e2 a0 80` is code point U+2300 which is "Braille Pattern Blank" which is why my browser displayed it as an arrangement of dots I didn't recognize.

I have no idea why your version of `ls` would output that second codepoint rather than a simple space. Presumably the first codepoint in the private use area is expected to map to an appropriate glyph in the font you're using to display something like the "card" symbol in @zzamboni's comment.

Note that the sequence 0xef 0x9d 0x95 would appear as shown in your first example if the terminal is in a Windows code page similar to [ISO 8859-15](https://en.wikipedia.org/wiki/ISO/IEC_8859-15) rather than a UTF-8 code page (whatever that means on Windows). The ISO 8859 standard and Windows code pages are a white hot mess. 😭

**Comment by krader1961** [comment]
@zQueal, I would recommend reopening this since it is a problem that will likely require changing how Elvish configures the Windows terminal subsystem and I can't guarantee the fix I started working on a year ago will fix this particular issue. Keeping it open also makes it easier to discover.

**Comment by krader1961** [comment]
I see from the prerequisites section of the [logo-ls]() project this statement:

```
Nerd Fonts: Nerd fonts are required to display Icons on screen. Basically Nerd Fonts patches your current font i.e., the last few unicode points (approx 2,824 out of 143,859) in the font are replaced with nerdy icons 🤓. The complete patching process is given here
```

Presumably the phrase "the last few unicode points" means the code points in the Unicode private use area. Personally, I dislike these abuses of the private use area and avoid using public projects that use them. YMMV 😄

**Comment by krader1961** [comment]
@zQueal, Are you using Elvish as a native Windows shell or as a WSL shell? The latter should "just work" while the former requires that Elvish utilize the Windows API to control the state of the tty/terminal.

**Comment by zQueal** [comment]
> See https://en.wikipedia.org/wiki/Private_Use_Areas, among other resources, for why using these code point ranges in a public manner are problematic. The main issue is they lead to code point collisions and problems such as illustrated in this issue when such code points are used outside someone's private environment.

Interesting. I had no idea.

> Are you using Elvish as a native Windows shell or as a WSL shell?

Windows shell via Windows Terminal Preview (1.12.2931.0), although I've just now tested with cmd.exe, and with multiple nerd fonts. The font my terminal uses by default is `Hack Nerd Font Mono`. I've tried several fonts from here: https://github.com/ryanoasis/nerd-fonts/tree/master/patched-fonts

As suggested, I'll re-open.

**Comment by krader1961** [comment]
FYI, in a Windows 10 console, running a current Elvish build, I put the UTF-8 sequence `\xEF\x9D\x95` in *~/x* then ran `cat ~/x | grep .` to simulate the pipeline in the original problem statement. It correctly displayed a single glyph (in my case a box since I don't have a patched font) rather than a glyph for each byte. In other words, I can't reproduce the problem which suggests the problem statement is still missing some crucial information.

@zQueal: Are you starting Elvish from a MSYS2 bash shell or directly from command.exe? What does `locale` output? On my system it shows this:

```
LANG=
LC_CTYPE="C.UTF-8"
LC_NUMERIC="C.UTF-8"
LC_TIME="C.UTF-8"
LC_COLLATE="C.UTF-8"
LC_MONETARY="C.UTF-8"
LC_MESSAGES="C.UTF-8"
LC_ALL=
```

**Comment by krader1961** [comment]
There's a tiny chance the recently merged fix for handling Unicode surrogate pairs on Windows, commit 5bf029074 for issue #1502, also fixes this issue. @zQueal, I'm not going to invest the time to verify whether or not it does so but perhaps you're still interested enough in this issue to test whether [elvish from HEAD](https://elv.sh/get/) resolves this issue.

**Comment by zQueal** [comment]
```cli
~
❯ elvish --version
0.19.0-dev.0.20220612203951-6564b148981a+official

~
❯ ls | grep warp
ï?â ?.warp/
```

It doesn't seem to fix it--but I no longer think this is an elvish issue;

```cli
C:\Users\zqueal\Downloads>ls -la | grep louis
-rw-rw-rw-â ?105.4Mâ ?Sun Jun 21 18:36:43 2020â ?ï-µâ ?louis.mp3
```

It seems to happen in a cmd.exe environment. Not sure why I didn't think to check this last time.

Since It's pretty clearly now not an elvish issue, I'm going to close this.

**Comment by krader1961** [comment]
> It seems to happen in a cmd.exe environment. Not sure why I didn't think to check this last time.

No reason you should have thought to do so, AFAICT. Am I correct in concluding you have installed the MSYS2 (aka Cygwin) environment? It looks so given the commands you are running. The file name in question probably is not valid UTF-8 or may have problems with respect to surrogate pairs, Unicode normalization, and generally not be valid Unicode.
