### ISSUE TITLE
Debugging / Linting Elvish

### ISSUE THREAD

**Issue by zQueal** [elves/elvish#1468]
Feature suggestion, I guess?

Would be great to include a way to test and lint `elv` scripts without having to run them. It currently makes working with elv for those of us with less than stellar understanding of it a bit tedious. Would be great to be able to throw things into a `test.elv` file that I think will work, and be able to lint / eval it for debugging;

> elvish --fmt test.elv > test_fixed.elv | elvish --debug test_fixed.elv

Or something like that, maybe. Elvish is great, but my current workflow is becoming taxing. I'm trying to progress into more complex functions and scripts, but it involves a ton of saving, reloading the environment, and running half scripts just to make sure they work.

**Comment by krader1961** [comment]
Have you tried `elvish -compileonly` to verify the validity of your Elvish programs? It's not exactly a substitute for a linter but it works well enough for me.

**Comment by zQueal** [comment]
Yes, actually! It's the only reason why I've been getting by as well as I have been. I was unaware this flag could be used to debug, and I suppose now it's a bit obvious. I was under the impression it was used to load many variables, etc, into an environment.

I was searching [here](https://elv.sh/ref/command.html#other-command-line-flags), but frankly it's not very well documented.

**Comment by krader1961** [comment]
> I was searching here, but frankly it's not very well documented.

I share your pain. 😄 Which is why I've authored many changes that improve the documentation. Note that the command reference page is relatively new and was added precisely because users like yourself wanted something with more information than provided by the terse output of `elvish -help`.

This project has surprisingly good documentation given that until recently most of the documentation has been written solely by the project owner, @xiaq. Especially since software engineers are notorious for focusing on writing cool code rather than documentation. So it's unsurprising there are omissions and ambiguities. Simply opening issues like this one are of great benefit to the Elvish community. Even better is taking a stab at improving the documentation by creating a pull-request (i.e., proposed change) that does so. 😸

**Comment by krader1961** [comment]
@zQueal, Since we now have https://elv.sh/ref/command.html#command-line-flags should this be closed? If not what would you like to see changed?

**Comment by zQueal** [comment]
`-compileonly` has been a great stopgap, but only works non-interactively, which at least IMO is still a hurdle. Elvish has been easy for me to get to know for the most part, but some friends that I've turned to Elvish have used it, found it great, but have difficulty using it full time because it lacks some common features that you see with other shells/languages. Like great debugging tools built-in.

At this point, this is more food for thought than anything. Although it only works non-interactively, compileonly has been working just fine for me.
