### ISSUE TITLE
Suggestions about edit:small-word-abbr behavior

### ISSUE THREAD

**Issue by aca** [elves/elvish#1472]
Hi @krader1961 
I'm trying to replace fish `abbr` with `edit:small-word-abbr`.

Current implementation seems to be  

> Skip an abbreviation if it begins with an alphanum and the previous
char in the insert buffer is also an alphanum or there is no
preceding char.
https://github.com/elves/elvish/pull/980

But can we also skip an abbreviation if it begins with symbols like `-`, `_` if it doesn't have matching abbr using it ?

If i set something like this.
```
set edit:small-word-abbr['k'] = 'kubectl'
```

`ls -k<space>` expands to `ls -kubectl` and it is obviously not intended.

**Comment by krader1961** [comment]
FWIW, The `edit:small-word-abbr` behavior is based on, but not identical to, the Fish shell `abbr` behavior. It was a compromise between myself and the Elvish project owner; especially with regard to not treating pressing Enter the same as Space. Having said that, it does seem like the expansion should only occur if the prefix is whitespace (or start of line); not just the definition of a "small word". That would fix another annoyance I experience with this abbreviation:

```
set edit:small-word-abbr['l'] = 'less'
```

If I type `ls -l` then press Space the `l` is converted to `less` which is incredibly annoying and not how Fish handles that situation. I've just been living with that unwanted behavior. It's probably long past time to fix it.

**Comment by aca** [comment]
> expansion should only occur if the prefix is whitespace (or start of line)

I thought it was what `edit:small-word-abbr` intended to achieve (which was not with `edit:abbr`),

Fish abbr seems to expand only at "start of command" and it is quite nice. (Haven't looked at implementation details yet)
 
![image](https://user-images.githubusercontent.com/50316549/149073980-51496890-3c55-4b42-ac54-de97c8a337bd.png)

1, 3 expands 2 not.

**Comment by mredaelli** [comment]
> If I type ls -l then press Space the l is converted to less which is incredibly annoying and not how Fish handles that situation. I've just been living with that unwanted behavior. It's probably long past time to fix it.

+1

Can we at least make it a configuration option? I wouldn't mind trying my hands at a PR if the solution would be accepted.

**Comment by krader1961** [comment]
From my comment in issue #1540 for anyone who stumbles upon this issue and wants to look at the implementation to understand why small word abbreviations behave like they do:

> expanded upon typing a trigger character, which is currently a space or semicolon

Close, but not correct. See the [implementation](https://github.com/elves/elvish/blob/9f2d5a86800c902e4f0ac7af136d411fb522b6cc/pkg/cli/tk/codearea.go#L231-L283), but the short answer is that the trigger char simply has to be in a different category than the last character of the abbreviation; see the definition of [`CategorizeSmallWord`](https://github.com/elves/elvish/blob/9f2d5a86800c902e4f0ac7af136d411fb522b6cc/pkg/cli/tk/codearea.go#L347-L358). Consider this abbreviation: `set edit:small-word-abbr['l'] = 'less'`. If you type `echo -l-` the ell will be expanded to `less` because `s` is an alphanum and `-` is not.

**Comment by adamchristiansen** [comment]
I'm coming over from #1540, which does not seem like a great idea upon seeing the [implementation](https://github.com/elves/elvish/blob/9f2d5a86800c902e4f0ac7af136d411fb522b6cc/pkg/cli/tk/codearea.go#L231-L283) (thanks @krader1961).

I see two potential changes/features in this thread:

> If I type `ls -l` then press Space the `l` is converted to `less` which is incredibly annoying

> Fish abbr seems to expand only at "start of command" and it is quite nice

As I see it there are really 3 options for a "fix":

1. Introduce configuration options somewhere under `$edit:...` that allow these two behaviours.
2. Change the behaviour of small-word abbreviations.
3. Add a third type of abbreviation that behaves this way.

Option 3 in interesting as [simple abbreviations](https://elv.sh/ref/edit.html#edit:abbr) and [small-word abbreviations](https://elv.sh/ref/edit.html#edit:small-word-abbr) have a behaviour that is orthogonal to what we are describing here, which are really abbreviations that behave the same way as [Fish abbreviations](https://fishshell.com/docs/current/cmds/abbr.html). We likely do not want 3 different kinds of abbreviations, so that may not be the best solution. I also agree with the following, which is a solution more like option 2:

> If I type `ls -l` then press Space the `l` is converted to `less` which is incredibly annoying and not how Fish handles that situation. I've just been living with that unwanted behavior. It's probably long past time to fix it.

Is the intention of small-word abbreviations not to handle abbreviations in the same way as Fish? What is a use case for how Elvish handles small-word abbreviations where they are expanded like this?
