### ISSUE TITLE
On windows, "$XDG_" folders are ignored.

### ISSUE THREAD

**Issue by dartacao** [elves/elvish#1481]
Despite being on windows, I use `$XDG_CONFIG_HOME` and `$XDG_DATA_HOME` to keep my dotfiles and application data. However, the elvish interpreter can only read from the `%appdata%` environment variable if the OS is Windows.

Is it possible to make it read from the `XDG_...` variables by default?

Thank you for working on Elvish, it looks like an extremely interesting (and useful) project!

EDIT: I am aware of the -rc setting and am using it. I'm asking if this can be done by default.

**Comment by krader1961** [comment]
I know I've made the same request in the past (presumably on an IM channel since I can't find an issue or pull-request mentioning it). I recognize that Windows isn't UNIX and has its own standards for such things. However, I use a simple script that uses `rsync` to sync things like my home and Elvish source directories from my primary server to the VMs I use to verify Elvish behavior. That script is needlessly complicated by the need to treat Windows specially by syncing my *~/.config/elvish* and *~/.local/share/elvish* directories to *~/AppData/Roaming/elvish*. Not to mention my always being momentarily confused by the different locations of that data on Windows.

So I'm a strong thumbs up for recognizing the XDG locations on Windows. The question is whether those locations should be the default, falling back to *~/AppData/Roaming/elvish* if the env vars are not set, or vice-versa.

**Comment by krader1961** [comment]
FYI, @xiaq, I just built elvish from commit 49115db and it does not work as I expected. Specifically, in the Msys2 bash shell I did `export XDG_CONFIG_HOME=$HOME/.config/elvish`, removed the *~/AppData/Roaming/elvish* directory, verified that `$HOME/.config/elvish` had the expected content, and spawned a new elvish shell. It failed to read `$HOME/.config/elvish/rc.elv`. It does not appear that this issue is resolved.

**Comment by xiaq** [comment]
@krader1961 You should use `export XDG_CONFIG_HOME=$HOME/.config` instead.

**Comment by krader1961** [comment]
> You should use export XDG_CONFIG_HOME=$HOME/.config instead.

D'oh, of course. PEBKAC.
