### ISSUE TITLE
Interactive prompt doesn't support surrogate pairs on Windows

### ISSUE THREAD

**Issue by 89z** [elves/elvish#1502]
I can enter a two byte character, for example:

# Ç (U+00C7)

Using any of these paste or input methods:

- right click
- Ctrl + V
- Alt + 128

However a three byte character:

# ∞ (U+221E) (Alt + 236)

fails with those same methods.

**Comment by 89z** [comment]
My mistake, this does fail with "Console Host", but works with "Windows Terminal"

**Comment by 89z** [comment]
So the above does work if you use "Windows Terminal" instead of "Console Host", but with this character:

# 😀 (U+1F600)

It fails regardless of terminal.

**Comment by krader1961** [comment]
Define "it fails." It's hard to believe that Elvish "fails" with one Unicode printable code point and not another given that it is implemented in Go which has excellent Unicode support. In all likelihood the problem is that the font you're using simply doesn't have a glyph for that code point. Or it's a quirk of Windows that you can't enter that code point. What happens if you execute `echo "\U0001F600"`?

**Comment by 89z** [comment]
> Define "it fails."

As "pass" would be, if I can copy a character from somewhere (like this page), and paste it into the terminal using right click, or Ctrl+V. With the characters in the original comment, I can do that. With the character in the later comment, I cannot.

> It's hard to believe that Elvish "fails" with one Unicode printable code point and not another given that it is implemented in Go which has excellent Unicode support.

Yes that true. Trust me, I am not happy about this. Currently I am using PowerShell, which has plenty of its own problems, but its Unicode support is pretty good at least. However because of other issues, I am trying to find a new shell. Unfortunately most other shells Unicode support is not good.

> In all likelihood the problem is that the font you're using simply doesn't have a glyph for that code point.

I dont think thats the case. As I just mentioned, all the characters on this page work just fine with PowerShell.

> Or it's a quirk of Windows that you can't enter that code point. What happens if you execute `echo "\U0001F600"`?

That does work:

~~~
D:\Desktop\elvish-master\cmd\elvish> echo "\U0001F600"
😀
~~~

which is promising, but pasting is also important.

**Comment by krader1961** [comment]
Note that Windows uses UTF-16 and the code point you're trying to use is larger than can be represented by UTF-16. I'm quite confident this has nothing to do with Elvish and everything to do with Windows. 😄 

P.S., Elvish isn't responsible for pasting text in the terminal. That's handled by the OS and terminal which then pass the corresponding sequence of UTF-8 bytes to Elvish.

**Comment by krader1961** [comment]
Having said the above it's possible that Elvish needs to enable a feature of the Windows terminal that isn't enabled by default. I don't think there is anyone working on Elvish who would consider themselves a Windows API expert so fixing this (assuming it can be fixed) may take a long time.

**Comment by 89z** [comment]
> P.S., Elvish isn't responsible for pasting text in the terminal. That's handled by the OS and terminal which then pass the corresponding sequence of UTF-8 bytes to Elvish.

I dont think this is true.

Windows comes with two shells of its own, "Command Prompt" and "PowerShell". If I repeat this test with both of these, I get different results. "Command Prompt" is the older shell, so it produces some garbage when you try to paste, similar to Elvish. However PowerShell pastes the character just fine.

So as long as the terminal supports the action (I am using Windows Terminal, which does), when the problem falls onto the shell, which is evidenced by the differing behavior of "Command Prompt", "PowerShell" and Elvish.

**Comment by 89z** [comment]
Note further, that at least one third party shell does do pasting as expected:

https://github.com/nushell/nushell

so its also not an issue of using a builtin shell versus a third party shell.

**Comment by krader1961** [comment]
What do you see if you run this and paste the problem code point then press Ctrl-D: `str:to-utf8-bytes (slurp)`? Note that Ctrl-D generates an EOF condition on UNIX systems. Not sure if that works on Windows. I have a vague memory that it may be Ctrl-Z on Windows.

**Comment by 89z** [comment]
~~~
D:\Desktop\elvish-master\cmd\elvish> str:to-utf8-bytes (slurp)
��^Z
Exception: exec: "str:to-utf8-bytes": file does not exist
[tty 5], line 1: str:to-utf8-bytes (slurp)
~~~

**Comment by krader1961** [comment]
You'll need to first do `use str`. I never remember to say that because I have `use` commands for all the embedded modules in my *rc.elv*. That two glyphs are displayed suggests the code point is being encoded as two UTF-16 code points. Which makes sense given that pretty much everything in Windows (but not Elvish) works with UTF-16.

**Comment by 89z** [comment]
~~~
D:\Desktop\elvish-master\cmd\elvish> use str
D:\Desktop\elvish-master\cmd\elvish> str:to-utf8-bytes (slurp)
��^Z
▶ 0xf0
▶ 0x9f
▶ 0x98
▶ 0x80
~~~

**Comment by krader1961** [comment]
Hmm, that sequence of UTF-8 is U+1F600; i.e., the code point you're pasting:

```
> str:from-utf8-bytes 0xf0 0x9f 0x98 0x80
▶ 😀
> str:to-codepoints (str:from-utf8-bytes 0xf0 0x9f 0x98 0x80)
▶ 0x1f600
```

So it looks like Elvish is getting the correct character.  What happens if you type `str:to-codepoints `, paste the emoji, then press Enter? You should see `0x1f600`.

**Comment by 89z** [comment]
Elvish does not allow me to paste the character, thats the whole impetus of this issue. With PowerShell, I can paste no problem, with "Command Prompt", pasting outputs ��. With Elvish, pasting is simply ignored, like I never gave any input, both with right click or Ctrl+V.

The exception to this is some of the examples youve had me do. But this latest test is not possible, but its me just doing a "normal paste" which doesnt currently work with Elvish on Windows.

**Comment by krader1961** [comment]
> Elvish does not allow me to paste the character

Actually, the earlier experiment using `slurp` shows that Elvish does allow you to paste that character. What's unclear is why it works when reading from stdin but doesn't let you directly inject the char on the command line.

**Comment by 89z** [comment]
Im sorry, but I do not wish to have argument over which word is the correct word. All I know, is that as distasteful as it might be to you, that Elvish does in fact current have a problem with Unicode on Windows. Here is a working example with another shell (NuShell):

~~~
PS D:\Desktop\nushell-0.44.0> .\nu.exe
Welcome to Nushell 0.44.0 (type 'help' for more info)
D:\Desktop\nushell-0.44.0> 😀
error: Command not found
  ┌─ shell:1:1
  │
1 │ 😀
  │ ^^ command 😀 not found
~~~

I can use right click, or Ctrl+V and everything just works as expected. If Elvish doesnt want to support Unicode on Windows, thats up to the maintainers, but if thats the case, I think it should at least be documented that Unicode on Windows isnt support, and wont be implemented. I wouldnt blame you if thats the decision, as it seems tough to get right. But I think pretending thats its not a problem is not the right solution.

**Comment by 89z** [comment]
I appreciate your responses, but honestly I don't think "back seat troubleshooting" is the way to solve this. Correct me if I'm wrong, but it seems you personally don't have a way currently to test on Windows, or aren't interesting in setting one up. I don't blame you if that's your situation, but it makes it ten times harder if you're trying to fix a Windows issue. Id rather work with someone "on my team", so to speak. As you can probably tell, I am run out of patience on this matter. So I think the best thing would be for me to unsubscribe from this issue.

If you or someone else has a Windows machine, then I am willing to continue troubleshooting. You'll just need to mention me, otherwise I wont get the notification.

**Comment by krader1961** [comment]
@89z: I do have a Windows system. But it isn't my primary system (I'm on a Mac laptop at the moment) and I won't have access to it till later today. I was simply trying to get some clarity on what works and what doesn't. When you opened the issue you didn't even tell us you were using Windows. As I said earlier we definitely want Elvish to work well on Windows but I don't think any of the contributors would consider themselves Windows API experts.

**Comment by 89z** [comment]
Right, but you also repeated tried to assert that this wasnt an Elvish issue, even without being in a situation to actually verify that fact (not able to currently use a Windows machine):

> It's hard to believe that Elvish "fails" with one Unicode printable code point and not another given that it is implemented in Go which has excellent Unicode support.

and:

> I'm quite confident this has nothing to do with Elvish and everything to do with Windows. 😄

and:

> Elvish isn't responsible for pasting text in the terminal. 

That was the main source of my frustration. You were speaking on Windows authoritatively, while the truth was that not only is Windows not your main system, but at the time you didnt even have access to a Windows machine.

**Comment by 89z** [comment]
If it helps, I found another Go shell that works:

~~~
PS D:\Desktop\murex-windows-amd64.exe\bin> .\murex-2.6-windows-amd64.exe
Loading profile `.murex_preload`
Loading profile `.murex_profile`
murex » ∞
Error in `∞` (1,1): exec: "cmd": executable file not found in %PATH%
murex » ∞
Error in `∞` (1,1): exec: "cmd": executable file not found in %PATH%
murex » ∞
Error in `∞` (1,1): exec: "cmd": executable file not found in %PATH%
murex » 😀
Error in `😀` (1,1): exec: "cmd": executable file not found in %PATH%
murex » 😀
Error in `😀` (1,1): exec: "cmd": executable file not found in %PATH%
murex » 😀
Error in `😀` (1,1): exec: "cmd": executable file not found in %PATH%
~~~

Although when I tried to build it, I noticed that it requires GCC, so it might be using C code to handle Unicode. I dont know.

**Comment by krader1961** [comment]
@89z: I do 99% of my testing of Elvish on Windows over an SSH connection from iTerm2 on macOS. I verified that the "slurp" test works:

```
> str:to-codepoints (slurp)
��
^Z
▶ 0x1f600
```

But I **cannot** paste the same code point into the Elvish command line! That slightly surprised me because I was hypothesizing the problem was somehow due to running Elvish inside a Windows terminal emulator and therefore I wouldn't observe the problem when interacting with Elvish on Windows over an SSH connection. However, it's sort of good news because it makes reproducing the problem, and testing fixes, easier for someone who doesn't normally use the Windows GUI for testing how Elvish behaves on Windows. However, it could still be due to how the Windows "console" is configured since that logic is operative even when interacting with Elvish over an SSH connection.

The Murex shell has this code:

```
func makeRaw(fd int) (*State, error) {
    var st uint32
    if err := windows.GetConsoleMode(windows.Handle(fd), &st); err != nil {
        return nil, err
    }
    raw := st &^ (windows.ENABLE_ECHO_INPUT | windows.ENABLE_PROCESSED_INPUT | windows.ENABLE_LINE_INPUT
| windows.ENABLE_PROCESSED_OUTPUT)
    if err := windows.SetConsoleMode(windows.Handle(fd), raw); err != nil {
        return nil, err
    }
    return &State{state{st}}, nil
}
```

Note that it is disabling `windows.ENABLE_PROCESSED_INPUT` whereas Elvish enables it. That seems unlikely to be the cause of this issue (although I have yet to test it) but it does suggest avenues for exploration. A more significant difference between the two shells is that Elvish sets the console input mode mask without regard to the current value. Whereas Murex modifies the current input mode mask by add/removing bits.

**Comment by krader1961** [comment]
I did some more debugging today. This has nothing to do with the console mode being wrong. The problem is that Windows encodes characters like U+1F600 in a manner not currently handled by Elvish. See https://docs.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes and https://github.com/elves/elvish/blob/7cf4b94c5f00f0a75cdad4cc215cab8fb1d08296/pkg/cli/term/reader_windows.go#L123-L133. Note there is already a "TODO" comment indicating this is a known deficiency -- just not a high priority to address. I'll see if I can get it to work as a learning exercise even though I am no fan of the Windows API.

P.S., I'm still slightly perplexed how the `echo (slurp)` example manages to correctly handle code points involving surrogate pairs but not perplexed enough to dig deeper. 😄

**Comment by xiaq** [comment]
> P.S., I'm still slightly perplexed how the echo (slurp) example manages to correctly handle code points involving surrogate pairs but not perplexed enough to dig deeper. 😄

The I/O when running commands do not go through the `cli/term` layer.
