### ISSUE TITLE
How to migrate the history of other shells

### ISSUE THREAD

**Issue by guidao** [elves/elvish#1525]
How to migrate the history of other shells

**Comment by krader1961** [comment]
> How to migrate the history of other shells

Presumably you mean the interactive command history. That's certainly possible for trivial commands such as `cd /some/path` using the commands in the [store module](https://elv.sh/ref/store.html). The problem is how to do it for non-trivial commands such as `ls -l $(which elvish)` that is valid for a POSIX shell like Bash but not Elvish? Do you want those Elvish incompatible commands to be added to the Elvish command history without translation or translated to the Elvish equivalent? What about support for other non-POSIX shells such as Fish?

**Comment by guidao** [comment]
Thanks. store api is exactly what I need. For incompatible commands it's not a problem for me, I can adjust it during execution.
