### ISSUE TITLE
Error: db error: file size too small

### ISSUE THREAD

**Issue by ErickHoward** [elves/elvish#1527]
Just installed Elvish from the website using the official images. When I try to run ```Ctrl+L``` i get the following error: 
```
error: db error: file size too small
```
I am using Fedora Linux 36.

**Comment by krader1961** [comment]
That error is reported when the BoltDB file is smaller than two times your system page size. On Linux it's normally 4KB which means the database was smaller than 8KB. You can check the current page size by running `sysctl vm.pagesize`. Assuming you haven't set any `XDG_*` env vars the database file should be found at *~/.local/state/elvish/db.bolt*.

Since I believe you first tried using the ancient version of Elvish that ships with Fedora it's possible you've got an Elvish daemon running from that version. You should make sure one isn't running. If `ps waux | grep elvish | grep daemon` reports a process kill it then start a new Elvish shell.

P.S., This error has only been reported once before, issue #466, and that person "fixed" the problem by upgrading their OS. I used scare quotes because I suspect the OS upgrade fixed the problem only indirectly. For example, by freeing up disk space of correcting permissions on their home directory.

**Comment by krader1961** [comment]
Also, the database used to be stored in the *~/.elvish* directory so check that as well. If the DB is there remove it before killing any existing Elvish daemon.

**Comment by krader1961** [comment]
> I don't know what you mean by 'the ancient version of Elvish that ships with Fedora'.

That comment was based on your earlier questions about Elvish on Fedora where it seemed you were using an old version of Elvish. I might have jumped to the wrong conclusion because you didn't, in the IM channel, state what version of Elvish was being installed or what you meant by "fedora repo isn't working". The project owner and myself assumed you were able to install Elvish using the Fedora repo but it wasn't working as expected.

> Concerning your help, thanks. It worked and I can now use Elvish.

For the benefit of future users who might run into this problem and search for "file size too small" it would be helpful if you explained how you resolved the problem.

**Comment by ErickHoward** [comment]
> For the benefit of future users who might run into this problem and search for "file size too small" it would be helpful if you explained how you resolved the problem.

I simply removed the ```~/.local/state/elvish/``` and ```~/.elvish folder```

**Comment by krader1961** [comment]
> I simply removed the ~/.local/state/elvish/ and ~/.elvish folder

Okay, that doesn't provide enough information to know why you got the "file size too small" error but it is probably because you initially used an old version of Elvish (before XDG support was added) provided by your distro then attempted to use the current version you downloaded from https://elv.sh/get/.
