### ISSUE TITLE
Completion behavior on filenames with non-printable characters

### ISSUE THREAD

**Issue by LdBeth** [elves/elvish#1528]
```
$ e:ls
å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent
$ e:ls "å¤§è°·å\x92\x8cå¤« - ã\x81¨ã\x81\x8dã\x82\x81ã\x81\x8dã\x83\x88ã\x82¥ã\x83\x8aã\x82¤ã\x83\x88 O.S.T.torrent" 
ls: å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent: No such file or directory
Exception: ls exited with 1
[tty 27], line 1: e:ls "å¤§è°·å\x92\x8cå¤« - ã\x81¨ã\x81\x8dã\x82\x81ã\x81\x8dã\x83\x88ã\x82¥ã\x83\x8aã\x82¤ã\x83\x88 O.S.T.torrent" 
$ e:ls -B
å¤§è°·å\302\222\302\214å¤« - ã\302\201¨ã\302\201\302\215ã\302\202\302\201ã\302\201\302\215ã\302\203\302\210ã\302\202¥ã\302\203\302\212ã\302\202¤ã\302\203\302\210 O.S.T.torrent
$ e:ls "å¤§è°·å\302\222\302\214å¤« - ã\302\201¨ã\302\201\302\215ã\302\202\302\201ã\302\201\302\215ã\302\203\302\210ã\302\202¥ã\302\203
                      \302\212ã\302\202¤ã\302\203\302\210 O.S.T.torrent"
å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent
```

The filename is wrongly decoded thus contains unprintable chars. The second line is completed by default tab completion, and not recognized by `ls` (and other programs). However the filename printed with `ls -B` can be recognized.

 `-B` is

> Force printing of non-printable characters (as defined by ctype(3) and current locale settings) in file names as \xxx, where
> xxx is the numeric value of the character in octal.  This option is not defined in IEEE Std 1003.1-2008 (“POSIX.1”).

Right now I'm not going to request changes on the default completion behavior, because Windows might have different behavior on handling pathname with unprintable chars, and this is really an edge case. However, I'd like to know is there a way to config the default filename completion to handle unprintable chars in the same fashion of `ls -B`?

**Comment by krader1961** [comment]
What version of Elvish (`elvish -buildinfo`)?

Note that the problem bytes all have the high bit set but are not part of a valid UTF-8 sequence. For example, \x92 which `ls -b` UTF-8 encodes as \302\222. So the problem isn't that the chars are non-printable, it's that they are invalid UTF-8. Presumably the filename is in a locale such as ISO 8859-15. It's not obvious what the "correct" behavior is.  UNIX filenames are a sequence of bytes, not characters. I would argue that the current Elvish behavior is more "correct".

**Comment by LdBeth** [comment]
```
$ elvish -buildinfo
Version: 0.18.0
Go version: go1.17.2
Reproducible build: true
$ put $E:LANG
▶ en_US.UTF-8
```

The filename is not valid UTF-8 indeed. It could be encountered by unarchiving a ZIP file made from Windows that is not using UTF-8, or downloading file with a browser that cannot correctly decide the encoding of filename.

```
$ ksh
$ ls å¤§è°·å^Ò^Ìå¤«\ -\ ã^Á¨ã^Á^Íã^Â^Áã^Á^Íã^Ã^Èã^Â¥ã^Ã^Êã^Â¤ã^Ã^È\ O.S.T.torrent 
å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent
$ bash
bash-3.2$ ls å¤§è°·åå¤«\ -\ ã¨ããããã¥ãã¤ã\ O.S.T.torrent 
å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent
$ tcsh
[Costume-Party:~/Downloads] ldbeth% ls å¤§è°·å^Ò^Ìå¤«\ -\ ã^Á¨ã^Á^Íã^Â^Áã^Á^Íã^Ã^Èã^Â¥ã^Ã^Êã^Â¤ã^Ã^È\ O.S.T.torrent 
å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent
$ zsh
ldbeth@Costume-Party Downloads % ls å¤§è°·å$'\302\222'$'\302\214'å¤«\ -\ ã$'\302\201'¨ã$'\302\201'$'\302\215'ã$'\302\202'$'\302\201'ã$'\302\201'$'\302\215'ã$'\302\203'$'\302\210'ã$'\302\202'¥ã$'\302\203'$'\302\212'ã$'\302\202'¤ã$'\302\203'$'\302\210'\ O.S.T.torrent
å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent
```

Regardless of differences in display behavior, all the typical shells are able to have the programs like `ls` recognize the filename provided by tab completion even when the filename is not supported by current locale.

And I'm trying to make sense the behavior of `put`:

```
$ put "\302\222\302\214"
▶ "\x92\x8c"
$ put (eq "\302\222\302\214" "\x92\x8c")
▶ $false
```

This behavior seems to be what makes working with none UTF-8 encodings in with completion a problem.

**Comment by krader1961** [comment]
> And I'm trying to make sense the behavior of printing in elvish:

Your second command, involving `eq`, outputs `$false` because an explicit byte using something like `\302` or `x92` is just that: a byte, not a char that is converted to UTF-8. That, in fact, is a somewhat recent change (commit fb1e8077) because I complained it wasn't possible to construct a string consisting of a sequence of bytes that did not represent a valid UTF-8 sequence. That is, until recently typing `echo "\x92"` would output this

```
> echo "\x92" | god -tx1z
0000000 c2 92 0a                                         >..<
0000003
```

rather than this

```
> echo "\x92" | god -tx1z
0000000 92 0a                                            >..<
0000002
```

> Regardless of differences in display behavior, all the typical shells are able to have the programs like ls recognize the filename provided by tab completion even when the filename is not supported by current locale.

I think you are incorrectly generalizing from your specific situation rather than from first principles. It appears to me that programs like `ls` are incorrectly handling strings that are invalid UTF-8.

**Comment by krader1961** [comment]
> Regardless of differences in display behavior, all the typical shells are able to have the programs like ls recognize the filename provided by tab completion even when the filename is not supported by current locale.

I don't think you have demonstrated that assertion. I suspect that those shells are, incorrectly, interpreting file names using their locale. What happens if you change the locale to something that changes how the bytes in the file name are interpreted? This is the fundamental problem with the ISO 8859 standard (the UNIX equivalent of Windows "code pages").

Please note that I am not saying the current Elvish behavior should not be changed. I am simply pointing out that the pre-Unicode standards make this a really hard problem to solve. Especially since UNIX file names consist of bytes rather than "characters". That is, UNIX file names do not have a character encoding.

**Comment by LdBeth** [comment]
>  It appears to me that programs like ls are incorrectly handling strings that are invalid UTF-8.

Something like `ls | ls (take 1)` or `var v = [*]; ls $v[0]` can still pickup the file.

> What happens if you change the locale to something that changes how the bytes in the file name are interpreted?

When `LANG=C`:

```
$ ksh
$ ls å¤§è°·åå¤«\ -\ ã¨ããããã¥ãã¤ã\ O.S.T.torrent 
a??????e??????a??????a?????? - a??????a??????a??????a??????a??????a??????a??????a??????a?????? O.S.T.torrent
$ bash
bash-3.2$ ls a\314\212\302\244\302\247e\314\200\302\260\302\267a\314\212\302\222\302\214a\314\212\302\244\302\253\ -\ a\314\203\302\201\302\250a\314\203\302\201\302\215a\314\203\302\202\302\201a\314\203\302\201\302\215a\314\203\302\203\302\210a\314\203\302\202\302\245a\314\203\302\203\302\212a\314\203\302\202\302\244a\314\203\302\203\302\210\ O.S.T.torrent 
a??????e??????a??????a?????? - a??????a??????a??????a??????a??????a??????a??????a??????a?????? O.S.T.torrent
$ zsh
ldbeth@Costume-Party test % ls å¤§è°·å?$'\222'?$'\214'å¤«\ -\ ã?$'\201'¨ã?$'\201'?$'\215'ã?$'\202'?$'\201'ã?$'\201'?$'\215'ã?$'\203'?$'\210'ã?$'\202'¥ã?$'\203'?$'\212'ã?$'\202'¤ã?$'\203'?$'\210'\ O.S.T.torrent
???????????????????????? - ?????????????????????????????????????????????????????? O.S.T.torrent
$ tcsh
[Costume-Party:~/test] ldbeth% ls a\314\212\302\244\302\247e\314\200\302\260\302\267a\314\212\302\222\302\214a\314\212\302\244\302\253\ -\ a\314\203\302\201\302\250a\314\203\302\201\302\215a\314\203\302\202\302\201a\314\203\302\201\302\215a\314\203\302\203\302\210a\314\203\302\202\302\245a\314\203\302\203\302\212a\314\203\302\202\302\244a\314\203\302\203\302\210\ O.S.T.torrent 
a??????e??????a??????a?????? - a??????a??????a??????a??????a??????a??????a??????a??????a?????? O.S.T.torrent
[Costume-Party:~/test] ldbeth% exit
$ elvish
>> ~/test $ ls "å¤§è°·å\x92\x8cå¤« - ã\x81¨ã\x81\x8dã\x82\x81ã\x81\x8dã\x83\x88ã\x82¥ã\x83\x8aã\x82¤ã\x83\x88 O.S.T.torrent" 
ls: å¤§è°·å??å¤« - ã?¨ã??ã??ã??ã??ã?¥ã??ã?¤ã?? O.S.T.torrent: No such file or directory
Exception: ls exited with 1
```

Seems only the visual display has been changes. The completion still "works" for these shells.

**Comment by LdBeth** [comment]
> That, in fact, is a somewhat recent change (commit https://github.com/elves/elvish/commit/fb1e8077355325cbe2e6891d2fc218a783f6b5a4) because I complained it wasn't possible to construct a string consisting of a sequence of bytes that did not represent a valid UTF-8 sequence. That is, until recently typing echo "\x92" would output this

If this have been the case, I think I'd be satisfied with the completion behavior. I'll try from the HEAD to see if this would also fix completion.

**Comment by krader1961** [comment]
I can't reproduce this problem using Elvish built from head or prior to commit fb1e807. Specifically, by running, on Linux with a UTF-8 locale, `touch a\x92b` then doing `ls a` followed by pressing Tab followed by pressing Enter. @LdBeth, If you do the same sequence does it "work"? If it does then something other than my hypothesis is occurring on your system. If it doesn't work then there is a, as yet unidentified, characteristic of your system that is important.

**Comment by krader1961** [comment]
> elvish does not translate backslash if it is not inside double quotes. 

/Face-palm 😄  I thought I had tested the double-quoted variant and gotten the same result. Note that my locale is also en_US.UTF-8; but that probably doesn't matter -- I'm simply too lazy to test other locale variants since anyone not using a Unicode locale deserves weird behavior. 😺 

The basic problem is that Elvish (or the Go stdlib code it uses) translates file name bytes in the range \x80 to \xFF  to Unicode chars when doing file name expansion. The question is where the bug lies. File names should be treated as arbitrary byte sequences rather than UTF-8 or any other (e.g., ISO 8859) encoding.

**Comment by krader1961** [comment]
Ugh! I've fixed the three places in *pkg/parse/quote.go* that incorrectly assumed every string was valid UTF-8 and added unit tests for those cases. However, the glob matching code still does the wrong thing when applying character matchers (e.g., `*[print]`) to file names that are not valid UTF-8. Since that is a different problem than documented by this issue I'm going to ignore it. Note that macOS and some other Unix file systems don't allow, or can optionally be configured to disallow, invalid UTF-8 file names. And, honestly, if you create a file name that isn't valid UTF-8 in the year 2022 you deserve any behavior short of Elvish panicing. 😸 

See https://news.ycombinator.com/item?id=16991263 for an interesting read related to this problem. The bottom line is that 99.9999% of this problem is caused by the obsolete concept of "code pages"; whether Windows or ISO 8859 on Unix. If you still have file names encoded in a non-ASCII "code page" that isn't valid UTF-8 you deserve a bit of pain. 😺
