### ISSUE TITLE
Custom small word abbreviation triggers

### ISSUE THREAD

**Issue by adamchristiansen** [elves/elvish#1540]
### Problem

Abbreviations defined in [`$edit:small-word-abbr`](https://elv.sh/ref/edit.html#edit:small-word-abbr) are expanded upon typing a _trigger_ character, which is currently a space or semicolon. As far as I can tell there is no way to change the set of trigger characters. Other shells with abbreviations, such as Fish, also expand abbreviations when the enter/return key is pressed. For example, suppose I define an abbreviation `gs` to expand to `git status`:

- In Fish, when I type `gs` followed by return, the input is expanded into `git status` and the command `git status` is executed.
- In Elvish, when I type `gs` followed by return, the input is not expanded, and the command `gs` is executed (which launches GhostScript).

### Solution 1: Use `$edit:abbr`

An obvious solution may be to use [`$edit:abbr`](https://elv.sh/ref/edit.html#edit:abbr), but this may have unintended side effects. Let's consider the `gs` &rarr; `git status` example. Now if you want to use the `xargs` program, when you type `xargs`, Elvish will immediately expand it to `xargit status` as soon as the `s` is entered, which is obviously not the desired behaviour.

### Solution 2: User Defined Trigger Characters

Perhaps there could be a variable, like `$edit:small-word-abbr-triggers`, which is a list of trigger characters. By default it could be defined as `[' ' ';']` so that the existing behaviour is preserved. If a user wants, they could edit the list to include `"\n"` (or some other appropriate value) to enable expanding small word abbreviations when enter/return is pressed. This has the benefit of letting users add _and_ remove triggers to their liking.

**Comment by krader1961** [comment]
This is essentially a duplicate of #1472.

> expanded upon typing a trigger character, which is currently a space or semicolon

Close, but not correct. See the [implementation](https://github.com/elves/elvish/blob/9f2d5a86800c902e4f0ac7af136d411fb522b6cc/pkg/cli/tk/codearea.go#L231-L283), but the short answer is that the trigger char simply has to be in a different category than the last character of the abbreviation; see the definition of [`CategorizeSmallWord`](https://github.com/elves/elvish/blob/9f2d5a86800c902e4f0ac7af136d411fb522b6cc/pkg/cli/tk/codearea.go#L347-L358). Consider this abbreviation: `set edit:small-word-abbr['l'] = 'less'`. If you type `echo -l-` the ell will be expanded to `less` because `s` is an alphanum and `-` is not.

> expand abbreviations when the enter/return key is pressed

My original implementation did that. The project owner rejected that behavior because they felt Enter shouldn't both trigger expansion and execution. It should only do the latter. Personally, I've gotten used to Enter not triggering expansion so I don't feel any need to change that behavior. However, the "small word" behavior has proven problematic. I can't tell you how often I type `ls -l ...` and find myself annoyed that is transformed into `ls -less ...`. I do feel that should be changed.

Let's continue this discussion in issue #1472 since that's the older issue.

**Comment by adamchristiansen** [comment]
Thank you for this information and good call on #1472 - I missed that issue somehow. I'll close this issue and we can move the discussion there.
