### ISSUE TITLE
Multi-line Commands

### ISSUE THREAD

**Issue by spitfire94** [elves/elvish#1552]
My belief is that The Oil Shell is the best replacement for Bash. However, Elvish is definitely better for interactive purposes. I'd like to have Oil style multi-line commands within Elvish.

```
... doas cryptsetup
    --batch-mode --type=luks2
    --key-file=/run/keys/misc.key
    luksOpen /dev/sdx1
;
```

**Comment by krader1961** [comment]
It's easy enough using the [line continuation](https://elv.sh/ref/language.html#whitespace) token:

```
doas crypsetup ^
    --batch-mode --type=luks2
```

I can't see a good justification for introducing a triple-dot sequence as an indicator that newlines should be elided until a semicolon is seen.

**Comment by krader1961** [comment]
I don't track the development of the Oil shell but was wondering about this feature. A blog post describing it can be found [here](https://www.oilshell.org/blog/2021/09/multiline.html). It seems like the only justification for the triple-dot prefix is to allow using line comments with a multi-line command; for example:

```
... doas cryptsetup # comment 1
    --batch-mode --type=luks2 # comment 2
    some-other-arg
;
```

That seems like a lot of added complexity to the language spec and implementation for a feature I, personally, would rarely (probably never) use. If I need to comment parts of a command it's easy enough to place them as a block comment immediately preceding the command with no loss of readability.

**Comment by hanche** [comment]
One can always write

```
doas {cryptsetup # comment 1
    --batch-mode --type=luks2 # comment 2
    some-other-arg}
```

You just have to be careful not to put a space after the opening brace.

**Comment by krader1961** [comment]
For those wondering why @hanche's suggestion works see https://elv.sh/ref/language.html#braced-list. While it works I'm not a fan of using (or abusing) that mechanism for this issue. If someone asked me to review a change that used that pattern I would demand it be changed to not use a braced-list because it isn't idiomatic Elvish, far too subtle, and will be broken if someone introduces whitespace after the opening brace because they think it improves readability. Braced lists should be limited to simple examples of composing values for commands such as those in the documentation -- not composing multi-line commands.

If there is a consensus that line comments should be supported for multiline commands I think a mechanism separate from braced-list syntax should be introduced. Having said that, I hope it is clear I **do not** think we should introduce syntax for in-line comments of multiline commands. A simple block comment preceding the multiline command should be adequate.

**Comment by hanche** [comment]
@krader1961 You have a point there. (I just can't resist being a smartass sometimes.) I do resort to this trick on occassion, though mostly interactively, where I wish to paste in some multiline list of stuff on the command line. Or the same, in an ad hoc, throw-away script.

The trick comes with a big footgun too, due to the deviant parsing rules for braced lists (for which, see #995).

**Comment by krader1961** [comment]
Also, I should have pointed out that braced-list expansion only works for arguments to a command. You can't use it like this:

```
{doas # run as root
 cryptsetup # comment 1
 --batch-mode --type=luks2 # comment 2
}
```

That would be legal using the Oil shell triple-dot syntax. Again, I don't really see the point. I would just put all three comments in a block comment preceding the command and use the line continuation token, `^`, to split the long command into smaller units that make it easier to read.

**Comment by xiaq** [comment]
@spitfire94 Thanks for the interest in Elvish. I am not interested in supporting this feature, so I'll close this now.
