### ISSUE TITLE
Misleading error message with an empty variable name

### ISSUE THREAD

**Issue by hanche** [elves/elvish#1560]
This error message is rather misleading:

```
⬥ var '' = foo                                                                                              ~
compilation error: 4-6 in [tty]: cannot create variable $; new variables can only be created in the local sco
pe
```

Now there are good reasons not to allow empty variable names. But the error message could be improved upon.

**Comment by krader1961** [comment]
FWIW, this behavior is due to the Go stdlib `strings.SplitAfter()` function when invoked with an empty string. We could modify the Elvish `SplitQNameSegs()` function to handle empty strings if we decide it makes sense to allow a quoted var name that is the empty string. Personally, I don't think the empty string makes sense as a var name and allowing it invites mischief. So it makes more sense to modify the error message to make the var name clearer. Specifically, this is the current code that produces the confusing output:

```
cp.errorpf(n, "cannot create variable $%s; new variables can only be created in the local scope", qname)
```

The use of the `%s` formatting option is the primary cause of the confusing error message. You'll get a similarly confusing message for a similar case:

```
> var 'x: y' = z
compilation error: 4-10 in [interactive]: cannot create variable $x: y; new variables can only be created in the local scope
```

The use of the raw `qname` variable should be replaced by a function that returns a string representation of the var name that includes appropriate quoting if it isn't a valid Elvish bare word.

**Comment by krader1961** [comment]
I have a fix for this issue but there aren't any relevant unit tests. I'm debating whether to add unit tests or just submit a PR that fixes the issue empirically without unit tests.

**Comment by krader1961** [comment]
It turns out most of those compilation failures do have unit tests but they use `DoesNotCompile()` for verification which makes discovering the relevant tests difficult, and makes it unclear the tests are verifying what they claim. This seems like a good time to do to `DoesNotCompile` what I did over a year ago (in commit 87656c99) to replace `AnyError` with checks for a specific error.

**Comment by xiaq** [comment]
Reopening since #1617 doesn't actually fix this.
