### ISSUE TITLE
Why require `prettier` version 2.3.1?

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1561]
The https://github.com/elves/elvish/blob/master/CONTRIBUTING.md file says that `prettier` version 2.3.1 should be used. Why? I just created a pull-request to update https://github.com/elves/awesome-elvish/blob/master/README.md and found that version and the current (2.6.2) version resized the Markdown table cells to include additional padding unless I prefixed each table with this line: `<!-- prettier-ignore -->`. If a specific version of `prettier` is required there should probably be an explanation why that is the case. AFAICT there is no reason to lock `prettier` to that old version.

Also, I've been using this `prettier` invocation in my *~/.vim/vimrc* for a very long time:

```
" Ensure Markdown source files are properly formatted.
autocmd BufWritePost *.md silent !prettier --tab-width 4 --prose-wrap always --write <afile>
```

I don't know why I am using those options since they aren't currently documented at https://github.com/elves/elvish/blob/master/CONTRIBUTING.md or used in the *Makefile* `style` target . Perhaps they were documented or included in the *Makefile* in the past? Regardless, I think the existing *CONTRIBUTING* documentation would benefit from some additional verbiage regarding how to invoke `prettier` in a manner consistent with the style of this project.

**Comment by krader1961** [comment]
Also, it seems to me that lists, rather than tables, are more appropriate in the [Awesome Elvish](https://github.com/elves/awesome-elvish/blob/master/README.md) document for the *lists* of packages and modules.

**Comment by xiaq** [comment]
The awesome-elvish repo is not subject to formatting requirements since that'd create an obstacle for casual contributors. The main repo is a bit more "serious" in that aspect.

There is no significance in the particular version, it was the latest version at some point. The version is pinned for reproducibility. https://github.com/elves/elvish/commit/bc4193122fcb89ea9de37ae0a3226ba44092b87f upgraded it to the latest 2.7.1.

The manual options used to be required and documented in CONTRIBUTING, until I found out that prettier supports an RC file. Those options are now in https://github.com/elves/elvish/blob/master/.prettierrc and it's no longer necessary to specify manually.

The reason awesome-elvish uses tables is purely aesthetic.
