### ISSUE TITLE
will open Discussions ?

### ISSUE THREAD

**Issue by WingDust** [elves/elvish#1655]

**Comment by krader1961** [comment]
@WingDust, what is the point of this issue? Anyone can create an issue to discuss anything related to this project. You need to provide more information about whatever concern you have vis-a-vis the Elvish project.

**Comment by xiaq** [comment]
> @WingDust, what is the point of this issue? Anyone can create an issue to discuss anything related to this project. You need to provide more information about whatever concern you have vis-a-vis the Elvish project.

"Discussion" is capitalized so I guess this means https://docs.github.com/en/discussions. You can find a lot of other open source projects on GitHub that use this new feature now.

---

I've played with discussions a while ago. I find it a somewhat confused product. Its name suggests a forum-like software, but it isn't a particularly good forum like Reddit or Discourse. Its data model resembles StackOverflow - for each discussion, you can have answers and comments on answers, and you can have accepted answers. But then I don't know why I would use it instead of just using StackOverflow.

To me, it really feels like the product managers at GitHub didn't make up their mind on what they want this product to be, so I wouldn't know how to actually use it.

If you have ideas on what values discussions add (I'm familiar with its _features_, but I just don't know how they translate into _values_) I would be happy to consider. But if it's not clear what it can be used for, there's no point in enabling it.

**Comment by krader1961** [comment]
@xiaq, You're probably correct that the O.P. is asking if this project will enable the [GitHub Discussions](https://docs.github.com/en/discussions) feature. Something I vaguely remember noticing when it was announced but immediately forgot about because it seemed pointless (at least as implemented when it was announced). I wish the O.P. had been less cryptic so we wouldn't have to guess what they meant. I love GitHub but am ambivalent about its "Discussions" feature. Like you I don't really see the point in its current implementation.

@WingDust: Can you expand on how you think using the "GitHub Discussions" feature would improve the evolution of this project? I know I'm a bit of a dinosaur but, like the suggestion to create an Elvish Discord channel, it is not clear that enabling "GitHub Discussions" for this project is a net benefit.

**Comment by krader1961** [comment]
> You can find a lot of other open source projects on GitHub that use this new feature now.

It is my experience that a lot of open source projects simply enable things like Github "Discussions", or merge new features, without a lot of thought as to whether the capability is a net benefit. See, for example, some of the issues with Zsh variable expansion syntax that I documented in this [article](https://www.skepticism.us/posts/2015/10/its-time-to-replace-zsh-with-a-saner-shell-because-unsetopt-multifuncdef-breaks-tab-completion/) I wrote.  These are actual examples of code that Zsh users rely on:

```
_comp_colors+=( "=(#i)${prefix[1,-2]//?/(}${prefix[1,-2]//(#m)?/${MATCH/$~toquote/\\$MATCH}|)}${prefix[-1]//(#m)$~toquote/\\$MATCH}(#b)(?|)*==$tmp" )
list=(${${${(0)"$(git config -z --get-regexp '^alias\.')"}#alias.}%$'\n'*})
```

Just because a single user thinks some feature is useful does not mean it should be enabled or merged. That a lot of Github hosted projects have enabled "Discussions" does not impress me in the slightest. Most people are happy to chase a new shiny object; e.g., enable Github "Discussions". Without considering whether it actually adds value for their project simply because it is a "new shiny object".

**Comment by WingDust** [comment]
@krader1961  use  "Discussions"  represent  [GitHub Discussions](https://docs.github.com/en/discussions) is my fault 

but i think  enable GitHub Discussions still helpful,
In some projects, only Github Issues are treated as bugs, feature ...

GitHub Discussions as a project usage issues, such as: syntax issues,

I think GitHub Discussions can be used to make Github Issues more pure

Just in my opinion, it may be wrong

**Comment by krader1961** [comment]
@WingDust, I appreciate that English is probably not your primary language. Nonetheless, I could not understand the points you were trying to make with your prior comment. Can you answer this question by @xiaq regarding Github "Discussions":

> If you have ideas on what values discussions add (I'm familiar with its features, but I just don't know how they translate into values) I would be happy to consider. But if it's not clear what it can be used for, there's no point in enabling it.

I don't understand, for example, what you mean by "make Github issues more pure". While tools like [Google Translate](https://translate.google.com/) have limitations it might be helpful if you typed your thoughts into that tool and copied its English translation here.

**Comment by xiaq** [comment]
@WingDust Regarding "project usage issues": there are two places for people to ask them now:

- On IM (in one of the user groups listed on https://elv.sh)
- On StackOverflow

I don't mind it when people post questions on issues either - I assume this is what you meant by making issues more pure. Those issues end up getting closed pretty quickly when the questions are answered, and regulating where people say things is something I've given up upon.

**Comment by xiaq** [comment]
I'll close this for now. I can revisit when GitHub Discussions becomes more compelling, for as I said right now it's a very confused product.
