### ISSUE TITLE
Modify `eq`, `not-eq`, `==`, et. al. to require at least two values

### ISSUE THREAD

**Issue by krader1961** [elves/elvish#1662]
I was modifying a moderately complex Elvish program and made a copy/paste error because I had written this and then copied it several times:

```
} elif (eq $w) {
```

The intent was to add a string literal to be compared for equality against the `$w` variable in each copy of that line. I missed adding the literal to one copy of that line which resulted in a bug.

Today the `eq` command (and its related commands) allow zero, one, or multiple values. I appreciate why these commands allow comparing more than two values. However, I think it is a mistake, an over generalization, that they allow zero or one value. Perhaps my imagination is lacking but I can't see any valid use case for `eq` (no values) or `eq one-value`. It seems to me such instances are always a mistake; i.e., a bug.

**Comment by krader1961** [comment]
Also, I appreciate one the reason for the current behavior is to support examples like these:

```
elvish> var l = []
elvish> eq $@l
▶ $true
elvish> var l = [1]
elvish> eq $@l
▶ $true
elvish> var l = [1 2]
elvish> eq $@l
▶ $false
```

I still feel like the current behavior is far more likely to make bugs hard to identify than provide useful behavior.

**Comment by xiaq** [comment]
I don't feel too strongly about this, but guarding against _unintentional_ typos seems to be a good job for linters, and that would make this change unnecessary.

**Comment by hanche** [comment]
I admit to being somewhat bemused by this proposal. Surely, there are lots of ways to write syntactically correct but semantically wrong software, and I fail to see why this case is serious enough to warrant changing the language. After all tests like `== $@xs` or `< $@xs` seem quite useful, and having them raise an exception if the list is too short does not seem reasonable.

Furthermore, if zero or one arguments is problematic, wouldn't three or more arguments also be a likely source of bugs?

One way to resolve this is to for all the comparison operators take an option, say `&all`, to allow an arbitrary number of arguments. By default, they could then only accept two arguments, neither more or less. (But this is tricky, as a three argument usage `< $a $x $b` has a natural interpretation as “`$x` is between `$a` and `$b`.)

That said, upon rereading the documentation, it struck me that for the _negated_ comparison operators `!=`, `!=s`, and `not-eq` are not well suited for any number of arguments other than two. To explain why, consider the other operators: Ordering and equality operators being associative, it often makes sense to compare a group of them in one fell swoop. And then, the zero- and single-argument versions fall naturally into place: It is the coherent option, IMO. But how often do you need to check whether a list never has equal neighbours? I think rarely, and besides, my natural inclination is to read `not-eq $@xs` as `(not (eq $@xs))`, contrary to the present state of affairs. So indeed, for the _negated_ equality operators, I whole-heartedly support limiting them to two arguments. As for the others, I am (much) more skeptical.

**Comment by krader1961** [comment]
> Furthermore, if zero or one arguments is problematic, wouldn't three or more arguments also be a likely source of bugs?

I don't think so since three or more arguments has an obvious interpretation. Whereas zero or one argument does not.

> That said, upon rereading the documentation, it struck me that for the negated comparison operators !=, !=s, and not-eq are not well suited for any number of arguments other than two.

Right, and consistency argues that the equal and not-equal variants should behave the same when handed zero or one argument.

> One way to resolve this is to for all the comparison operators take an option, say &all, to allow an arbitrary number of arguments.

I'm ambivalent about adding an option. First because, as you say, all of `eq`, `not-eq`, `<` and friends have a natural interpretation when handed three or more arguments. If we decide to go this route I'd prefer naming it `&any` (that defaults to false) and setting it true means to allow zero or one arguments.

> I don't feel too strongly about this, but guarding against unintentional typos seems to be a good job for linters, and that would make this change unnecessary.

It seems to me the problem with this idea is it violates an important idea from the Go project. Namely that its official linter (run by `go vet`) only reports on verifiable bugs; e.g., mismatches between a `fmt.Printf` format string and the corresponding arguments. It explicitly does not include "warnings" such as you'll find emitted by other linters such as [`oclint`](https://oclint.org/). If invoking `eq` with zero or one argument is an error then it should be a compile and run-time error. Not a "did you really mean to do that" warning by an Elvish linter.

**Comment by xiaq** [comment]
Well the linter should only flag code like `eq foo`, where there is _always_ only one argument and the command is meaningless (it's equivalent to just `put $true`).

Invocations like `eq $@li` are still supported and won't trigger linter warnings.

**Comment by krader1961** [comment]
I guess I'm still confused why the compiler can't just complain when it sees `eq foo` or just `eq`. Why is it necessary to delegate that to a linter?

Yes, a construct like `eq $@li`, where `li` contains fewer than two elements, can't (in general) be detected by the compiler. It sounds like you are arguing that case should output `$true` at run-time even if the list does contain fewer than two elements. From a mathematician's perspective that is reasonable. However, from a pragmatic programmer's perspective it is a source of subtle bugs. Which is why I'm arguing there should also be a run-time test for too few arguments.

I feel this is a case where pragmatism is more important than purity. If someone really wants `eq $@li` to output `$true` when `li` contains fewer than two elements it isn't much of burden to ask them to write `(and (<= 2 (count $li) (eq $@li))`. Or, perhaps an option, such as `&any`, could be added to these comparison commands to indicate the programmer understands what happens when fewer than two values are present.

**Comment by xiaq** [comment]
> I guess I'm still confused why the compiler can't just complain when it sees `eq foo` or just `eq`. Why is it necessary to delegate that to a linter?

Letting the compiler detect this is an interesting idea. It can be done in two ways:

- Make this a compile-time warning. On the issue of warnings I'm pretty firmly with Go's authors that compilers should _not_ emit warnings. It's a linter's job to identify legal but likely wrong code.

- That still leaves the choice of making this a compile-time error. This could work, but I don't feel comfortable making the compiler care about individual commands. The compiler only deals with special commands like `var` and `set`. Unless there are other compelling use cases that form a pattern, the compiler shouldn't care about specific non-special commands.

So I'd rather stick to the beaten path of doing this type of checks in a linter. Elvish doesn't have a linter now but it will eventually have one.

Checking nullary and unary uses of `eq` also falls neatly into a common category of linting errors of "trivial expressions". The linter can also warn about uses of, say, `eq $a $a` because it is also trivially true.
 
> Yes, a construct like `eq $@li`, where `li` contains fewer than two elements, can't (in general) be detected by the compiler. It sounds like you are arguing that case should output `$true` at run-time even if the list does contain fewer than two elements. From a mathematician's perspective that is reasonable. However, from a pragmatic programmer's perspective it is a source of subtle bugs. Which is why I'm arguing there should also be a run-time test for too few arguments.
>
> I feel this is a case where pragmatism is more important than purity. If someone really wants `eq $@li` to output `$true` when `li` contains fewer than two elements it isn't much of burden to ask them to write `(and (<= 2 (count $li) (eq $@li))`. Or, perhaps an option, such as `&any`, could be added to these comparison commands to indicate the programmer understands what happens when fewer than two values are present.

Well, the correct expression is `(or (<= (count $li) 2) (eq $@li))`, so maybe it is a little bit of burden to ask people to write.

Being "mathematical" or "pure" doesn't automatically makes something unnatural. I think of `eq` as inherently variadic ("check if all arguments are equal") and the binary case as a special case.

This is similar to how the closest analog of Elvish's `+` in Python is **not** Python's `+` operator (because it's always binary), but Python's `sum` function. It wouldn't make sense for Python's `sum` function to require its argument to have at least 2 elements, and for me the logic then extends to Elvish's `+`, and then Elvish's `eq`. You don't have to agree with this multi-step analog, but for me it is very natural and I rely on intuition a lot in language design.

I do agree with @hanche's point that the negative commands like `!=` should be strictly binary, their current semantics is confusing and unlikely useful. I would further extend that to require `/` to be binary too (except when used for implicit cd, that's another discussion...), and `-` to be unary or binary.

**Comment by xiaq** [comment]
A note on compiler warnings: Elvish does currently violate the "no warning" rule in that it emits deprecation warnings. But:

- Deprecation warnings are ephemeral: deprecated features soon get removed, so the set of possible warnings remains pretty small.
- After the 1.0 release, deprecated features will no longer get removed, so the job of checking uses of deprecated features will also be relegated to the linter.

**Comment by krader1961** [comment]
> Well, the correct expression is (or (<= (count $li) 2) (eq $@li)), so maybe it is a little bit of burden to ask people to write.

Yes, but I think my mistake makes my point. Less than two values is a subtle case. And your acknowledgement that that `!=` and `not-eq` needs to be special-cased vis-a-vis less than two values is itself an argument that the positive tests should behave similarly.

**Comment by xiaq** [comment]
Revisiting this, I'm not convinced of the original proposal but I will change `!=`, `!=s` and `not-eq` to only accept two arguments.
