### ISSUE TITLE
[RFC] Structured data for non-built in commands #19259 

### ISSUE THREAD

**Issue by KoviRobi** [elves/elvish#1664]
Hi,

I am looking at coming up with a portable way to tell programs that they can output structured data, and telling the shell that the said data is structured according to the given format. For this I have a draft proposal write-up at https://github.com/KoviRobi/structured-shell-stdio but I would like some feedback, so please leave feedback either here or on the proposal.

This should avoid having to define aliases for all the commands that support e.g. JSON, for example
```
ip --json addr | from-json
```
could become just
```
ip addr
```
(assuming also some pretty-printing for structured data, such as [nushell](https://nushell.sh/) does, which also has `explore` which is a pager like `less` but supports structured data. Sorry I'm not very familiar with elvish)

Thanks,
Robert

**Comment by krader1961** [comment]
It seems to me your proposal is incoherent and impossible to implement in any meaningful manner.

**Comment by xiaq** [comment]
@krader1961 you are entitled to your opinions, but calling someone's proposal "incoherent and impossible to implement" without given any concrete reason is unnecessarily harsh and dismissive. I do not welcome such behavior in the community. Please engage in conversations civilly and constructively, or not at all.

Getting back to the proposal: I appreciate the need to simplify working with external commands, but:

- There isn't really a strong pattern in how external commands handle structured output. Some take `--json` like `ip` but most commands don't.

- I would rather keep the semantics of external commands simple: if I run `ip addr`, it should call the `ip` command with a single argument `addr`, with no hidden processing.

Defining wrapper functions is a fine way to handle things - if you only work with JSON outputs from the `ip` command, you can just define `fn ip {|@a| e:ip --json $@a | from-json }`. It's a little bit of overhead, but it keeps things straightforward. You can also collect such aliases in a module to reuse them.

Overall I'm fine with the current status and not considering this proposal, so I'll close this.

**Comment by KoviRobi** [comment]
Thank you, I agree that wrappers work and are fine, and with repositories such as awesome-elvish it's easy to make them discoverable.

My main goal was to try and get people's opinions and see if anyone else had thoughts on this -- it does make sense that this isn't high priority, it's a very minor UX improvement at most. It's more that I wanted to reach out to other structured data shells to see if anyone had thought of this and end up with a single solution rather than multiple different ones.

**Comment by zzamboni** [comment]
@KoviRobi since you are interested in structured output processing, you might find this utility useful: https://github.com/kellyjonbrazil/jc

**Comment by krader1961** [comment]
@KoviRobi: I apologize for my previous comment which was terse to the point of being rude. However, it seems like you do not have a good appreciation for why the creators of Unix chose to use pipelines of commands that handle byte streams. Since you favor JSON (as do I) for an external representation of most data there is no reason the data cannot be exchanged over the usual stdin/stdout streams. There is no reason to introduce a new communication channel. While the original Unix pipeline semantics were "line" oriented that simply reflected that most of the commands they envisioned would process lines of text (e.g., the `awk` and `sed` commands). However, there was nothing preventing more complex structures being exchanged between pairs of commands.

Note that your proposal also does not address, AFAICT, sending structured data from the shell to an external command.

Also, your proposal doesn't work in practice. If a shell implicitly exports a `JSON_STDOUT` variable then consider how that affects any shell code that expects the data from an external command on its stdin byte stream. Your proposal is essentially unworkable. The only practical solution at this point is to explicitly leverage the existing stdin/stdout byte stream paradigm with JSON encoded data. And that will a) require the user to explicitly ask for JSON handling of the byte stream and, b) take a long time to become commonplace.
