### ISSUE TITLE
Support Shebang?

### ISSUE THREAD

**Issue by darcy-shen** [elves/elvish#1709]
https://en.wikipedia.org/wiki/Shebang_(Unix)

**Comment by nichtsundniemand** [comment]
Could you please elaborate a bit?

**Comment by krader1961** [comment]
@darcy-shen, Elvish code works fine when put in a file that begins with a shebang line. I have several Elvish programs where I use that mechanism to make the Elvish program work like any other command I might run. Did you try this and run into a problem?

Note that shebang lines don't work on Windows unless you use a shell like Cygwin Bash which emulate the Unix behavior.

P.S., When opening an issue of this type you should always include the Elvish version you are using and the platform you are using.

**Comment by darcy-shen** [comment]
## What works?

In Bash interactive shell:

Save the following code snippet into `test` and `chmod +x test` and then `./test`
```
#!/usr/bin/env elivish

echo Hello; echo World
```

It works because there are shebang support in Bash.

## What doesn't not work?

In Elvish interactive shell:

Save the following code snippet into `test` and `chmod +x test` and then `./test`
```
#!/bin/bash

echo Hello && echo World
```
It does not work because Elvish does not support shebang.

## In a word
There is shebang support in Bash/Zsh/...
There is no shebang support in Elvish. Hope that shebang support could be implemented in Elvish.

**Comment by darcy-shen** [comment]
> Note that shebang lines don't work on Windows unless you use a shell like Cygwin Bash which emulate the Unix behavior.

You read my mind. Elvish already supports shebang. I was using Windows, and I thought Elvish does not support Elvish and finally I find that I was wrong.

**Comment by jcrben** [comment]
The question that comes to mind: why not support the shebang on Windows similar to the way cygwin Bash does?
![image](https://github.com/elves/elvish/assets/5614134/2a6c5956-19a2-4d07-83d6-408128674b57)

**Comment by jcrben** [comment]
@xiaq thanks for those insights, makes sense

Another way to consider it tho: people using Cygwin are looking for Linux emulation. So if elvish could handle shebang when people enter it from a cygwin environment that would alleviate those concerns

I'm pretty much exclusively using Windows from cygwin (actually msys bash but same difference) except when I need to test running something outside it

**Comment by xiaq** [comment]
@jcrben Right, if Elvish has access to Cygwin's virtual filesystem this would make a ton of sense. I don't think this is technically feasible though: the way Cygwin works is that it provides a dynamically linked library (cygwin1.dll) that programs link to, which provides a POSIX C API and implements the virtual filesystem stuff (among others). This library **replaces** libc which is why many Unix programs can be ported directly (with re-compilation, but no to little code change).

Go's standard library in general does not actually depend on libc (it uses syscalls directly), so Elvish can't be "Cygwinized" in the same way that, say bash, is "Cygwinized". It is technically possible for Elvish to explicitly depend on cygwin1.dll and use it to access Cygwin's virtual filesystem but it's going to be a lot of extra work.

**Comment by krader1961** [comment]
For those who might be wondering why this issue exists.... The kernel code on Unix like OS's that creates new processes, given a path to a file (the `exec` family of functions), opens the file and looks for the magic `#!` sequence at the start of the file to determine if it should invoke an interpreter to handle the program. See https://en.wikipedia.org/wiki/Shebang_(Unix). My first introduction to this feature was Sequent's DYNIX/3 OS in the mid 1980's that was based on 4.2BSD. Windows does not have an equivalent mechanism in its OS kernel. Windows primarily relies on file extensions to determine how to execute a program.

Linking against the Cygwin/MSYS2 libc DLL is certain to be far too expensive and fragile to be practical. However, it seems to me Cygwin's VFS mapping logic is stable enough it should be possible to implement it in a modest amount of Go code that won't need frequent updating. I briefly looked into doing so a few years ago when I setup my first Windows/MSYS2 environment for doing Elvish builds and running its unit tests on Windows. I quickly abandoned the effort because I only use Windows for testing software, like Elvish, on Windows. In other words I don't use Windows on a daily basis and thus lack sufficient motivation to improve matters. Still, someone with sufficient motivation could probably write the Cygwin VFS logic in Go with a modest amount of effort. Most of the work would involve integrating that logic into the Elvish code in a manner that did not affect its behavior on Unix systems.

As with switching from the legacy BoltDB interactive history to a simpler flat-file history without the need for a daemon process (see issue #1222) it's just a small matter of someone with sufficient motivation to put forth the effort to write the necessary code. 😺

**Comment by darcy-shen** [comment]
I'm using an extra bat script on windows as a solution.

For example, here is the content of `format.bat`
```
elvish format
```
It will execute the `format` elvish scripting file.

Thanks to the fix of
https://github.com/elves/elvish/issues/1746

The solution works fine in elvish 0.20.x.
