### ISSUE TITLE
The digest of the windows installer is not stable

### ISSUE THREAD

**Issue by darcy-shen** [elves/elvish#1722]
See https://github.com/ScoopInstaller/Main/commits/master/bucket/elvish.json

Why?

**Comment by xiaq** [comment]
Huh. dl.elv.sh is geo-balanced to one of two nodes that build binaries independently, and it turns out that zip files includes timestamps so they are not reproducible by default. The exe files are identical though

- https://cdg.dl.elv.sh/windows-amd64/elvish-v0.19.2.exe.sha256sum
- https://hkg.dl.elv.sh/windows-amd64/elvish-v0.19.2.exe.sha256sum

Still looking into the best way to get reproducible zip files.

**Comment by xiaq** [comment]
I've manually copied the 0.19.2 zip files and their sha256 sum files from the cdg node to the hkg node. I'll fix the reproducibility problem later.
