### ISSUE TITLE
RISC-V binaries

### ISSUE THREAD

**Issue by IngwiePhoenix** [elves/elvish#1811]
### What new feature should Elvish have?

I just built Elvish on my VisionFive2 - and by verbatin this works out perfectly!

```
root@riscboi ~# go install src.elv.sh/cmd/elvish@latest
go: downloading src.elv.sh v0.20.1
go: downloading pkg.nimblebun.works/go-lsp v1.1.0
go: downloading github.com/sourcegraph/jsonrpc2 v0.2.0
go: downloading golang.org/x/sys v0.16.0
root@riscboi ~# elvish --version
0.20.1
root@riscboi ~# uname -a
Linux riscboi 6.6.0-g076ede06c00a #29 SMP Tue Feb 13 00:01:46 CET 2024 riscv64 GNU/Linux
```

So, since this works quite well, I wanted to request RISC-V (`riscv64`) binaries.

### Output of "elvish -version"

0.20.1

### Code of Conduct

- [X] I agree to follow Elvish's [Code of Conduct](https://src.elv.sh/CODE_OF_CONDUCT.md).

**Comment by krader1961** [comment]
This is a reasonable request but it requires that the CI/CD environment used by the project support that architecture. Although I've been contributing changes for several years I've never looked at how the pre-built binaries are built. I think it's done using https://cirrus-ci.org/ which, AFAICT, does not support Risc-V at this time. It's not obvious that the number of users running Elvish on Risc-V is large enough today to justify setting up a build environment on something like the https://cloud-v.co/ service.

**Comment by xiaq** [comment]
> I think it's done using https://cirrus-ci.org/ which, AFAICT, does not support Risc-V at this time.

The binaries are built from my own VPSs, not from Cirrus CI (or GitHub Actions, which Elvish also uses). All the binaries are cross-compiled using the `tools/buildall.elv` script. Since they are cross-compiled, the architecture of the builders themselves are not relevant.

It would still be nice if I can get a RISC-V test runner to make sure that everything actually works as expected. I may try to set up one in future but that's another project.

In any case, RISC-V is pretty cool, so I just added that to `tools/buildall.elv` in 7f24110d79fd4287d280bccb8c6b90345f677e05 and HEAD builds are now available from https://dl.elv.sh/linux-riscv64/. I haven't added them to https://elv.sh/get because they weren't built for the last release and I'd like to keep the JavaScript simple, but I'll add it after the 0.21.0 release.

**Comment by IngwiePhoenix** [comment]
A test runner?
Well; does your VPS have docker? You could utilize QEMU + Docker to do that. There is a smaller emulator out there but I can't remember the name...
That said, how do I run the tests? Would be happy to take my board for a spin and run the whole suite.

**Comment by xiaq** [comment]
@zhsj taught me about qemu-user-static and it's a breeze to use. We're now running tests on both riscv64 and s390x! https://github.com/elves/elvish/actions/runs/10402716105
