### ISSUE TITLE
List, braced list and map comprehension

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#204]
List comprehension: `[(+ $x 1) | x in 2 3 5 7]`, equivalent to `[(for x in 2 3 4; do + $x 1; done)]`.

By analog, braced list comprehension: `{(+ $x 1) | x in 2 3 5 7}`; map comprehension: `[&$x=prime | x in 2 3 5 7]`.

**Comment by krader1961** [comment]
I love Python list comprehensions. However, I don't think that pattern is a good fit for Elvish. In fact, the first "equivalent to" example, `[(for x in 2 3 4; do + $x 1; done)]` is not valid (perhaps it was in the past). The valid version of that statement today is `[(for x [2 3 4] { + $x 1 })]`. I don't think that is particularly hard to read once you are familiar with Elvish and don't think any Python inspired equivalent is worth the increased complexity.

**Comment by zzamboni** [comment]
I agree with @krader1961 - I think the existing Elvish expressions are expressive and not much longer than any list comprehension syntax.

**Comment by xiaq** [comment]
Revisiting this, I agree that the combination of `for` and output capture is already quite clear and succinct.

We still lack an easy way to do map comprehension without mutating a map repeatedly. For that I filed #943.

**Comment by krader1961** [comment]
FWIW, I'm just looking at old issues to

1) see if there are any that an experienced software engineer like myself, who is new to the project, can address by changes to the code or documentation, or

2) that are obsolete or otherwise no longer relevant and should be closed.

I'm always skeptical of enhancement issues that are more than two years years old. By "old" I mean that there hasn't been any discussion of the issue in the past two years; not that it was opened more than two years ago. Lots of enhancement ideas require a long period of discussion. But if that discussion isn't taking place it suggests the idea might not be a good fit for the project.

**Comment by xiaq** [comment]
@krader1961 In the company where I work some teams simply close issues that have been inactive for a certain period of time (many of them have the same intuition as you and use 2 years as the threshold).

This practice has the underlying assumption that the direction of the project is driven by its users, so if no user appears to be interested in something, then there is no point in doing it. This assumption is true for many projects, proprietary or open. For Elvish it is true in many cases - a lot of fundamental design questions are still designer-driven, not user-driven.

As Elvish matures and its major design questions get settled, Elvish *will* become more and more user-driven. But for now, there are things that may not get the attention of users but still require that of the designers.
