### ISSUE TITLE
[question] How to do a logical or?

### ISSUE THREAD

**Issue by bpinto** [elves/elvish#214]
I'm trying to implement my own prompt with support for git, but I don't know how to do the logical or, I have been reading the [eval tests](https://github.com/elves/elvish/blob/master/eval/eval_test.go) but I couldn't find a solution yet.

Code I'm trying to achieve:
```
fn git-branch-name {
  e:git symbolic-ref --short HEAD || e:git show-ref --head -s --abbrev | head -n1
}
```

**Comment by xiaq** [comment]
Since non-zero external commands are treated as errors, you can use `try/except/tried`:

```
try
  git symbolic-ref --short HEAD
except
  git show-ref --head s --abbrev | head -n1
tried
```

**Comment by bpinto** [comment]
Okay, I have been using it to check if the folder is a git repository, I'll continue doing like this.

I assume I need to use `if/else` when I need a logical or otherwise?

**Comment by xiaq** [comment]
Logical combinators are indeed missing now.

Here is a explanation about how elvish treats errors and logic:

Elvish is different when it comes to errors and logic. Traditional shells conflate errors with failed tests: both are represented by non-zero return values. For instance, `ls -y` exits with 2 because the options `-y` is not correct, while `test 1 = 2` exits with 1 because the test fails. There is, to some extent, a convention of using 1 for test failures or "minor" errors, and 2 or greater for "major" errors, but I don't think we can fully rely upon this convention.

Errors in elvish are handled by the `try/except/tried` construct, as we have seen. Non-zero exits of external commands always become errors. You may also signal errors in your elvish function using the `fail` builtin function.

```sh
fn test { x=true; try e:test $@; except; x=false; tried; $x }
```

On the other hand, test results are represented by so-called **verdicts** (terminology not final) of commands, which may either be `$true` or `$false`. Unlike errors, when a command returns with a `$false` verdict, not much will happen. You may think them as `bool` return values of elvish commands that can be ignored. Commands intended to be used for their verdicts are called **predicates**; two examples are `<` and `has-prefix`. The verdict of an elvish function is that of the last command executed: this allows you to build predicates yourself.

The `if/else` is used for verdicts. You can also use `?()` for capturing the verdict of a command. For instance, `put ?(> 1 2)` puts `$false`.

**Comment by xiaq** [comment]
An unfortunate consequence is treating non-zero exits of external commands as errors is that it makes `test` much harder to use. However, it is easy build a wrapper for it:

```
fn test {
  try
    e:test $@
  except
    false
  tried
}
```

**Comment by bpinto** [comment]
Thanks for the through explanation! I'll be using it while I'm coding this prompt! 👍 
Super helpful!

P.S.: I am enjoying the try/except/tried usage so far.

**Comment by xiaq** [comment]
Note: the `false` command above is not the external `false` command, but an elvish builtin that simply renders a `$false` verdict.

@bpinto Glad to hear that :)
