### ISSUE TITLE
[Sharing][Question] Git prompt

### ISSUE THREAD

**Issue by bpinto** [elves/elvish#215]
I have finished coding the basics for my prompt with git support.

What do you think about the coding? Are the some tips you could give me? I decided to open it here so others could use it as an example in the future.

Thanks for building this shell! 👍 

```
### Prompt ###
fn git-is-repo {
  try
    e:test -d .git 
    e:git rev-parse --git-dir >/dev/null
  except
    false
  tried
}

fn git-branch-name {
  try
    e:git symbolic-ref --short HEAD
  except
    e:git show-ref --head -s --abbrev | head -n1
  tried
}

fn git-commit-count {
  { put $1 $2 } (e:git rev-list --count --left-right "@{upstream}...HEAD" | eawk put)
}

fn git-ahead [ahead behind diverged none]{
  {commits-behind,commits-ahead}=(git-commit-count)

  if == $commits-behind '0'; then
    if == $commits-ahead '0'; then
      put ' '$none' '
    else
      put ' '$ahead' '
    fi
  else
    if == $commits-ahead '0'; then
      put ' '$behind' '
    else
      put ' '$diverged' '
    fi
  fi
}

fn git-is-touched {
  try
    e:git diff --no-ext-diff --quiet --exit-code
    false
  except
    true
  tried
}

# Prompt with git support
le:prompt={ 
  ahead="↑"
  behind="↓"
  diverged="⥄ "
  dirty="⨯"
  none="◦"

  le:styled (tilde-abbr $pwd) 33
  if git-is-repo; then
    put ' on '; le:styled (git-branch-name) 32

    if git-is-touched; then
      put ' '$dirty' '
    else
      git-ahead $ahead $behind $diverged $none
    fi
  else
    put ' ❱ ' 
  fi
}
```

**Comment by bpinto** [comment]
I couldn't find support for a switch statement, I was looking for something like this:

```
  switch "$commit_count"
  case ""
  case "0"\t"0"
  case "*"\t"0"
  case "0"\t"*"
  case "*"
  end
```

**Comment by xiaq** [comment]
Hi @bpinto, thanks for the work! Comments:

1. `e:git` and `e:test` are not necessary; just use `git` and `test`. If you worry that the user might define them as a function, you can put this prompt in a file `~/.elvish/prompt-git.elv` and add `use prompt-git` in `~/.elvish/rc.elv`. Functions are lexically scoped, so `fn git` defined in `rc.elv` does not affect `prompt-git.elv`. This also has the advantage that you can define your symbols at the script level (instead of at the function level), so the user can later customize the prompt by modifying them. I would also put those symbols in a map:

  ```
  symbol-for=[&ahead="↑" &behind="↓" &diverged="⥄ " &dirty="⨯" &none="◦"]
  ```

  (There is now a bug #216 preventing you from writing multi-line map literals.)

1. I would first build two helper functions:

  ```
  fn ok [f]{
    try $f
    except; false
    tried
  }
  fn not-ok[f]{
    try $f; false
    except
    tried
  }
 ```
  (I might make `ok` into a builtin function, and `not-ok` will be unnecessary once we have logical negations.)

  which allow you to write `git-is-{repo,touched}` in a cleaner way:

  ```
  fn git-is-repo {
    ok {
      test -d .git 
      git rev-parse --git-dir >/dev/null
    }
  }

  fn git-is-touched {
    not-ok { git diff --no-ext-diff --quiet --exit-code }
  }
  ```

  Elvish is a functional language :)

1. `git-commit-count` can be simplified by using the `splits` builtin:

  ```
  fn git-commit-count {
    splits &sep="\t" (git rev-list --count --left-right "@{upstream}...HEAD")
  }
  ```

1. Since the symbols now reside in a map, I would write `git-ahead` to output the key. By the way, the quotes around `'0'` are not needed:

  ```
  fn git-ahead [ahead behind diverged none]{
    {commits-behind,commits-ahead}=(git-commit-count)

    if == $commits-behind 0; then
      if == $commits-ahead 0; then
        put none
      else
        put ahead
      fi
    else
      if == $commits-ahead 0; then
        put behind
      else
        put diverged
      fi
    fi
  }
  ```

1. Finally, I would define the prompt as a function before assigning it to `le:prompt`. This allows for easier reuse:

  ```
  fn prompt {
    le:styled (tilde-abbr $pwd) 33
    if git-is-repo; then
      put ' on '; le:styled (git-branch-name) 32

      if git-is-touched; then
        put ' '$symbol-for[dirty]' '
      else
        put ' '$symbol-for[(git-ahead)]' '
      fi
    else
      put ' ❱ ' 
    fi
  }

  le:prompt={ prompt }
  ```

You can find the entire source at https://gist.github.com/xiaq/f5ed2c0fe5292c3d1bc1b93e5c612f3b.

As for the `switch` proposal: yes, I would like to have pattern matching (#217) at some point.

**Comment by xiaq** [comment]
Hmm the new definition of git-ahead should take no arguments. It is correct in the gist but not in the comment.

Also, you can get rid of all the git- prefixes from the function names since there is no danger of polluting the global namespace if you have the above in a separate file.

Again, glad to see you enjoy elvish!

**Comment by bpinto** [comment]
Wow! Amazing comments! Thank you so much!

1. That was a great idea, I was using `e:` to not use a user-defined function. I don't understand the `symbol-for`, could you direct me to a place I could read about it?

2. This `ok` and `no-ok` function is great! I can imagine them being useful for other scripts!

3. This `splits` is a life-saver... I lost a long time getting around that code. :P

4. Will become awesome with pattern matching, I expect it to be super powerful. :)

5. How could one reuse this function? Is there a way to bring these functions to another scope?

**Comment by bpinto** [comment]
I thought about removing the `git-` prefixes, but maybe they will be useful in a mercurial + svn world (not mine).

**Comment by xiaq** [comment]
Answering 1: `symbol-for` is a map here. Map literals are mentioned in the README (search for "map"). By the way, I just added one more sample for using maps.

Answering 5: After using `use prompt-git`, variables and functions defined in it become available in the `prompt-git:` namespace. So the user may call your prompt with `prompt-git:prompt`, and alter the `symbol-for` map using, say, `prompt-git:symbol-for[dirty]=X`.

Answering the last comment: Since your functions would reside in a separate namespace, users will use your functions through the `prompt-git:` namespace. There is no room for collision, and having `prompt-git:git-is-repo` is a bit redundant.

**Comment by xiaq** [comment]
Hmm, `git-is-repo` was not implemented correctly. It should be:

```
fn git-is-repo {
  if ok { test -d .git }; then
  else ok { git rev-parse --git-dir >/dev/null 2>&1 }
  fi
}
```

Note: This will only work with HEAD since I just modified the verdict rule for `if`. The rule for verdicts might change again in future because the current rule set is a bit hacky :(

I have updated the gist as well, removing `git-` prefixes of the function names.

By the way, if you want to keep an eye on elvish development, consider joining #elvish on freenode, the [Gitter room](https://gitter.im/elves/elvish-public) or the [international user group on Telegram](https://telegram.me/elvish). Thanks to [fishroom](https://github.com/tuna/fishroom), the IRC channel, Gitter room and Telegram group are interconnected, so you can just join any one you like :)

**Comment by bpinto** [comment]
Thanks! I have one idea I would like to try when I get into my computer! I'll reply here later.

Awesome support! I'll join the gitter channel!

**Comment by bpinto** [comment]
Okay, just joined the gitter room! Thanks again for all the help here!

I just did one final thing on my local computer, which was to extract git functions into another file called `git` and then I use `git:function-name` on the `git-prompt` file.

So I've cleanup my configuration file a lot and I only need this on the top:

```
use git-prompt

# Use git prompt
le:prompt={ git-prompt:prompt }

# Disable right prompt
le:rprompt={ put '' }
```
