### ISSUE TITLE
Save stack trace to temporary file when crashing

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#224]

**Comment by krader1961** [comment]
Google, internally, has the concept of a "death rattle" (I'm an ex-Google software engineer). That is, when a process dies for an unexpected reason it sends as much relevant info as possible, via RPC, to a system that collects such information. It's similar to the sort of data collection that helps inform epidemiologists. You'll also see this mechanism used in many other software projects such as Apple's macOS. So the concept is definitely useful. Nonetheless, 3.4 years have passed since this issue was opened and it still hasn't been implemented so it's not obvious this is really needed for elvish support or development today.  At least not unless the info is uploaded, via RPC, to a global elvish database containing info about such failures. Which has significant privacy and security concerns.

**Comment by xiaq** [comment]
It seems that the global panic handler has worked well enough to give the user a chance to save the stack trace when Elvish crashes. Closing.
