### ISSUE TITLE
eval function

### ISSUE THREAD

**Issue by zhsj** [elves/elvish#230]
When I tried to replace the default shell in konsole with elvish, I failed to migrate following line in my zshrc:

```
eval `dircolors ~/.dircolors`
```

**Comment by zhsj** [comment]
Is it possible to do things like:

```
LS_COLORS='....'
export LS_COLORS
```

These are the output of `dircolors`

**Comment by huiyiqun** [comment]
How about following as a workaround
```
E:LS_COLORS=[(splits &sep="'" (dircolors | head -1))][1]
```

**Comment by huiyiqun** [comment]
try `dirs` for a more ~~powershell~~ elvish way

**Comment by xiaq** [comment]
Even if we have `eval`, we won't be able to evaluate the output of `dircolors` directly, as the syntax is not compatible with elvish.

**Comment by krader1961** [comment]
I'm a strong thumbs-down for adding an `eval` command. As @xiaq noted it assumes the code being eval'd is legal for the current shell -- which is not a safe assumption. Even among POSIX compatible shells it is not safe. Notwithstanding that in practice the features used are generally implemented by the lowest common denominator among POSIX compatible shells so it is rarely a problem.

The `dircolors` command is a particularly egregious example of abusing the POSIX `eval` command. It outputs a single value. There was literally no reason for it to produce shell statements meant to be `eval`'d. It could have simply output the single value and the user would then do `export LS_COLORS=$(dircolors)`, or whatever makes sense for that shell. Notice that `dircolors` has a `--csh` flag precisely because it, pointlessly, emits shell statements rather than just data.

Other commands that output more than a single value would, or should, be written today in a shell agnostic manner. Possibly using an encoding such as JSON.

I can't think of a single example similar to that in the initial comment of this issue which would justify an `eval` command.

P.S., Note that where `eval` is used  the `source` command should also work; e.g., `dircolors | source`. That it doesn't work is because the POSIX 1003.2 standard is a white hot mess. Yes, despite (or because of) being a grey-beard who spent three decades using nothing but POSIX compatible shells I want to see that shell standard kicked to the curb. Elvish should not implement the mistakes made by POSIX shells.

**Comment by xiaq** [comment]
I am introducing an `eval` command, but note that the original use case of this issue won't be satisfied it, since Elvish is not a POSIX shell.
