### ISSUE TITLE
Built-in autojump-like functionality

### ISSUE THREAD

**Issue by joelthelion** [elves/elvish#27]
Hi,

Thanks for your new shell. It looks very promising. I would like to know if you have considered bundling somthing similar to autojump with your elvish?

In case you're not familiar with it, autojump (https://github.com/joelthelion/autojump) is a tool that learns the directories where you spend the most time and allows you to jump quickly to these directories. A lot of people have found it useful. Autojump is not built into the shells it extends, and as a result it is a bit fragile and difficult to maintain. Having it built into elvish could be a great addition to the already very nice features of the new shell.

Feel free to close this issue if you think this is a bad idea, or simply not a priority.

**Comment by xiaq** [comment]
@joelthelion I just pushed 7a50c04bd4efc6dfc009a7c6881bef09e785fd92 which introduces two builtin functions that expose the directory history. I know the names are clumsy :) The user is supposed to define a handy alias themselves in the `rc` file, which unfortunately is not yet supported. The history is recorded by the `cd` builtin (which is probably a bad idea since there is no opt-out). The backend is found in `store/visisted_dir.go`.

There is no TUI yet, since I am focusing on the language at the moment. I'll do it when I switch my focus to the editor.

Suggestions and contributions are always welcome!

**Comment by xiaq** [comment]
Some time in future I would like to move this feature **out** of the core into a (pure elvish) module. But that will only be possible when the editor becomes programmable enough, which is not the case currently.

**Comment by xiaq** [comment]
The UI of the [command-t plugin](https://wincent.com/products/command-t) for vim is an excellent model for that of directory jumping. The directory jumping UI should work as follows:

1. A hot key (`Ctrl-T` by default) triggers the **directory jumping mode**. This mode is characterized by a buffer under the normal line editor buffer (like a minibuffer, should the reader be familiar with the word). The line buffer is preserved and still shown.

2. As the user types, matching directories in the history are automatically suggested using the command completion UI. Since the command completion UI is used, the keys for navigating among completion candidates (arrow keys and tab) are also available and the user may select a directory other than the first one.

3. Hitting Enter leaves the directory jumping mode and causes elvish to `cd` there. Hitting `Ctrl-C` (or maybe also `Esc`) leaves the mode without jumping.

An open question: how should the key bindings in this mode relate to those in the insert mode, vi-normal mode and completion mode? Specifically, when the user enters this mode from vi-normal mode, should line editing in the minibuffer use vi-normal key bindings?

**Comment by xiaq** [comment]
I am also considering using `Ctrl-L` for the trigger key by analogy to browsers.

**Comment by xiaq** [comment]
@joelthelion The UI for directory jumping has landed. I find it pretty cool :)
