### ISSUE TITLE
completing environment variable fails

### ISSUE THREAD

**Issue by huiyiqun** [elves/elvish#284]
```
~> E:<tab>
```

the candidates are the executables instead of the environment variables.

**Comment by xiaq** [comment]
Now `$E:<Tab>` correctly completes environment variables. However, `E:<Tab>` still completes external commands, since external commands and environment variables actually share the same namespace for now, and `e:` and `E:` are aliases of the same namespace.

If you think that they should be separated, please discuss in #285.
