### ISSUE TITLE
Some shell scripts fail under Elvish

### ISSUE THREAD

**Issue by vendion** [elves/elvish#320]
I have found that certain shell scripts fail to run under Elvish, but works just fine under ZSH.  Two scripts I have been able to repetitively get errors with are [this one that uses bash shell](http://sprunge.us/feSa?bash) and [this one that uses zsh shell](http://sprunge.us/jMQi?zsh).

The output I get from Elvish is as follows
```
~ ❱ tvs
Exception: forkExec: exec format error
Traceback:
  [interactive], line 1:
    tvs
~ ❱ sprunge bin/tvs
Exception: forkExec: exec format error
Traceback:
  [interactive], line 1:
    sprunge bin/tvs
~ ❱ /usr/bin/env bash
[vendion@Vili ~]$ exit
exit
~ ❱
```

Here the tvs script is the one written in bash and sprunge is the one written in zsh.

**Comment by vendion** [comment]
Could it have something to do with the shebang line using `/usr/bin/env` which is a common portability hack as different distributions/OSes wont put `bash` or `zsh` in the same place or maybe related to #316 ?

**Comment by xiaq** [comment]
Hi vendion, I cannot reproduce your bug. Can you make sure that the shebang line is correct? Can you paste a raw version of the scripts somewhere?

Most commonly, this problem is most commonly caused by the lack of shebang lines. In face of an exec format error some shells will fall back to using `sh` to execute the file, but elvish does not do this.

**Comment by vendion** [comment]
If you edit the URLs from my original post remove the the `?bash` and `?zsh` you will get the raw version as well.  If I need to also post them in a Gist I can.

The shebang lines should work as long as `bash` and `zsh` are found in my `PATH`, which they should be

```
~ ❱ echo $paths
[/usr/local/go/bin /home/vendion/bin /home/vendion/gocode/bin /usr/local/bin /usr/local/sbin /usr/local/opt/ruby/bin /home/vendion/bin /home/vendion/gocode/bin ')/home/vendion/bin' ')/usr/local/sbin' /usr/local/bin /usr/bin /usr/lib/jvm/default/bin /usr/bin/site_perl /usr/bin/vendor_perl /usr/bin/core_perl /home/vendion/.fzf/bin /home/vendion/.composer/vendor/bin]
~ ❱ which bash
/usr/bin/bash
~ ❱ which zsh
/usr/bin/zsh
```

My `PATH` is correctly configured in my `$HOME/.elvish/rc.elv` file.  Some of the paths are duplicated as this elvish shell was started under ZSH.

```
~ ❱ env bash
[vendion@Vili ~]$ exit # Now in BASH
exit
~ ❱ env zsh
[vendion@Vili][~]% exit # Now in ZSH
```

This is what made me thing this could be related to #316 , when it goes to exec the script could the value of `PATH` be reset and thus it is unable to find `/usr/bin/bash` and `/usr/bin/zsh`?

**Comment by vendion** [comment]
I think I fixed those scripts, the very first line was a newline for some reason that was causing it to break.  I have other scripts for things like [lemonbar](https://github.com/LemonBoy/bar) those scripts may or may not run with a valid `PATH` if `elvish` is my login shell.

**Comment by xiaq** [comment]
That confirms my suspicion. I do not intend to implement other shells' behavior here; using `sh` for missing shebang line can be dangerous, and people should not rely on this.

If you are seeing invalid `PATH`, it is most likely because `elvish` has been given an empty environment. My suggestion is that to simply put all paths inside your `rc.elv`, instead of just adding the ones not in the default PATH:

```
paths = [/bin /usr/bin ...]
```

This only applies to interactive sessions though.
