### ISSUE TITLE
'GLIBC_2.14' not found (required by ./elvish)

### ISSUE THREAD

**Issue by kybin** [elves/elvish#377]
Hello, thank you for doing this.

I test this on CentOS 6 and meet this error.

I saw elvish claims that it has no dynamic dependency.

Does this error expected?

**Comment by xiaq** [comment]
Aha, OK. Since we use cgo, the binary does depend on whatever libc was present when the binary was built. And I suppose our building environment has glibc 2.14, while your OS has an older version.

We can either [link statically with musl](https://dominik.honnef.co/posts/2015/06/go-musl/) or get rid of cgo dependencies.

**Comment by kybin** [comment]
I prefer remove cgo dependencies, but either way seems fine!

**Comment by xiaq** [comment]
The prebuilt binaries are now built with CGO disabled. Can you verify whether https://dl.elvish.io/elvish-linux.tar.gz works for you now?

**Comment by kybin** [comment]
Sorry, I could not check this because I upgraded to CentOS7.

If anyone confirmed this, please reply here.
