### ISSUE TITLE
Multiple "waiting for unsupported file type" when compiled with go1.9beta2

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#384]
When compiled with go1.9beta2, typing any character in Elvish will cause a lot of these errors to be printed:

```
reader error: read /dev/stdin: waiting for unsupported file type
```

**Comment by tw4452852** [comment]
This issue due to https://github.com/golang/go/issues/18507, after this, reading on a nonblocking file won't return `EAGAIN` any more. There are two ways to fix this issue: 

1. use `syscall.Read` to read file directly instead of `*File.Read`
2. I have just propose a patch in https://github.com/golang/go/issues/20915, it will keep the compatibility.

**Comment by xiaq** [comment]
@tw4452852 Thank you! :) For now let's wait a while and hope your patch gets accepted.

**Comment by tw4452852** [comment]
This issue should be fixed by https://github.com/golang/go/commit/26f0a7af456b3743e718002534576c6ef1ad99a3
