### ISSUE TITLE
Add number types

### ISSUE THREAD

**Issue by alexherbo2** [elves/elvish#456]
Considering bare numbers as numbers and quoted numbers as strings.

**Comment by xiaq** [comment]
Number type is OK, but number literals are problematic.

You don't want number literals (`1`, `1.0` or `-1`) to be an entirely different thing from strings, because they could well be filenames or command arguments. If naming a file `-1` sounds rare, beware that [there](https://manpages.debian.org/unstable/wget/wget.1.en.html) [are](https://manpages.debian.org/unstable/curl/curl.1.en.html) [numerous](https://manpages.debian.org/stretch/iproute2/ip.8.en.html) [commands](https://manpages.debian.org/unstable/netcat-openbsd/nc.1.en.html) that accept `-4` and `-6` as switches, and [man](https://manpages.debian.org/unstable/man-db/man.1.en.html) accepts an optional section number argument.

To accomodate such usages, you inevitably need to give number literals a double identity of both number and string. This double identity leads to (among other things) problems in equality semantics: are `1` and `1.0` equal? They are equal as numbers, but not as strings; how do you tell which one the user intends? If we were to support hexadecimal number literals, are `10` and `0xa` equal?

Distinct types and fuzzy equality semantics are not a good mix. We already know this from the `==` operator in JavaScript. Elvish now solves this problem by not having number literals at all, and let a set of arithmetic commands parse their arguments into numbers. This is a less magical and less confusing approach.

**Comment by alexherbo2** [comment]
### Comparing bare numbers (Numbers)

``` elvish
== 1 1.0 → true
```

### Comparing quoted numbers (Strings)

``` elvish
== '1' '1.0' → false
```

**Comment by xiaq** [comment]
For an external command `x`, should `x 1` and `x 1.0` behave the same?

This is an open design question, but I strongly prefer that they should behave differently, since `1` and `1.0` can be different filenames or otherwise have different meanings, and they are common enough that I don't want to require them to be quoted.

Then we end up with the situation where `1` and `1.0` are considered equal (`== 1 1.0` outputs `$true`), but do not always behave the same, which contradicts the fact that they are equal. Technically it can be made to work, but it's bad design.

**Comment by alexherbo2** [comment]
We could draw inspiration from [String interpolation][].

[Ruby / Crystal][] automatically convert objects to their string representation.

### Converting numbers to strings (Elvish)

``` elvish
str 1.0 → "1.0"
```

[String interpolation]: https://en.wikipedia.org/wiki/String_interpolation
[Ruby / Crystal]: https://en.wikipedia.org/wiki/String_interpolation#Ruby_.2F_Crystal

**Comment by xiaq** [comment]
Please read my last comment; it is not about string interpolation, it is about equality semantics.

**Comment by alexherbo2** [comment]
I read it.

**Comment by krader1961** [comment]
I'm reasonably happy with the current situation with regard to how `float64` works and interoperates with unquoted numbers. I consider `== 1 (float64 1.0)` outputting `$true` to be reasonable behavior. There are still some things that need more thought. Such as what it means to do an equality test on `float64` types that are extremely close in value but not literally identical bit values. Should `==` automatically apply an appropriate epsilon or should that be the responsibility of the user? Nonetheless, it seems to me this issue can be considered resolved and closed.

**Comment by krader1961** [comment]
Note that there are still some situations that should output a `float64` rather than a string. Such as the `count` builtin. But that should probably be addressed by resolving issue #816.
