### ISSUE TITLE
Documentation should explicitly point out early exit behavior regarding ;

### ISSUE THREAD

**Issue by mqudsi** [elves/elvish#470]
Users coming to elvish from pretty much any other shell are probably going to be surprised that the the `;` is not actually equivalent to a new "chunk" or "pipeline" or whatever you want to call it.

In particular, in all other shells, `foo; bar;` will execute `bar` after the execution of `foo`, regardless of the result. To conditionally execute, shells have operators like fish's `and` and `or`.

* I think the "unique semantics" document should make it clear that this is a very unique feature of elvish (it does say that elvish has exceptions and not exit codes, but it doesn't make clear what the side effect of that is)
* The language document should definitely mention that `;` in a chunk is equivalent to the logical `and` feature (at least, that's my understanding) under the `and` section.
* The "Execution flow" section of https://elvish.io/learn/unique-semantics.html is probably the most important part to include this info.

**Comment by xiaq** [comment]
Hmm, sorry for the confusion. Since you mentioned the "unique semantics" doc, it is actually documented in another section: https://elvish.io/learn/unique-semantics.html#exit-status-and-exceptions - have you read that section and how do you think of it? I agree that it is very helpful to compare `;` (or newline, actually) to `and` or `&&` in traditional shells and will include that. I will also cross-reference that section from other docs.

The "execution flow" section is not well named and I have renamed it "execution phases".

(Also, please direct future doc-related discussions to [elves/elvish.io](https://github.com/elves/elvish.io).)

**Comment by xiaq** [comment]
This is now further clarified in https://elvish.io/learn/unique-semantics.html#exit-status-and-exceptions as the follows:

> If you come from POSIX shell, this is aknin to `set -e` or having a `&&` between each pair of pipelines. In a sense, `&&` is written as `;` (or more commonly, a newline) in Elvish.
