### ISSUE TITLE
Decide whether ~ should be expanded and be consistent about it

### ISSUE THREAD

**Issue by mqudsi** [elves/elvish#472]
While my personal preference is for `~` to never be automatically expanded when referring to the current user's directory, elvish expands this to the full `$HOME` path in places but not in others.

For example, in the location history (ctrl+L), `~` is used. But in the command history, it's usually expanded to the full path. This means that users cannot use muscle memory and there's cognitive overhead when searching history depending on whether they are searching for a command or a location.

**Comment by xiaq** [comment]
I don't understand the problem here. Can you elaborate?

**Comment by mqudsi** [comment]
CTRL+L shows subdirectories of $HOME as ~/foo/bar
CTRL+R shows arguments that are subdirectories of $HOME as /home/../whatever (related to #471) 

The same path $HOME/foo/bar is shown one way in Ctrl+L and another in Ctrl+R. Elvish should be more consistent and either show `~` (_and other variables_) expanded or unexpanded in both, even if only from a purely ideological/purist perspective.

Additionally and from a pragmatic perspective, if I want to search for a subdirectory of my home directory in the location history, I type in `~/` to filter to what I want to see. But if I want to search for a command with an argument that was a subdirectory of $HOME, I need to filter by the expanded `/home/.../` prefix.

**Comment by xiaq** [comment]
There is no expansion in the location mode (Ctrl-L): the pattern matches what is presented. The presentation of directory paths abbreviates $HOME to ~, so when you type ~ to filter it matches what appears as ~. (I am actually lying because that is not how it is implemented, but effectively it behaves just in the way I described.) Filtering in history listing mode (Ctrl-R) also matches with whatever is presented, so there is no inconsistency here. If you typed `~/whatever` in your command, you can match it with `~`. If you typed `/home/username/whatever`, you can match it with `/home/username`.

One could still argue that the *presentation* of directories should be consistent across the two modes, by massaging the command history, turning /home/username/whatever into ~/whatever. But that breaks the simplicity of command history, because now what is in the history is no longer what you typed. Worse, it does not solve the problem: what if the current directory is already ~? Should you turn ./whatever into ~/whatever?

The inconsistency here, if it is an inconsistency, stems from the fact that directory history and command line history operate on different levels: command history simply reflects whatever the user typed and does not attempt to derive anything semantic from it. The user typed text, so Elvish should give back the user the exact text; massaging the text is error-prone and surprising. On the other hand, the text associated with a directory is not fixed, it could `/home/username/whatever`, `~/whatever` or `./whatever` (depending on pwd). The user could have used any of the above to access the same directory, so the user will not have the expectation of a fixed presentation, so a sane amount of massaging will not be surprising.

**Comment by mqudsi** [comment]
#474 will take care of the most annoying cases.
