### ISSUE TITLE
Option to change ▶ symbol

### ISSUE THREAD

**Issue by mqudsi** [elves/elvish#473]
I'm using elvish under WSL (basically, shell-only Ubuntu) under Windows 10. The only problem that I've noticed thus far in compatibility with conhost (the Windows master terminal) is that the default symbol used as the indicator for structured output `▶` is not rendered.

I'm sure that conhost isn't the only terminal with issues rendering the ▶ symbol (or maybe the font used simply doesn't have a mapping for that codepoint), so an option to change the indicator to an ascii character like * or something would be handy.

If this is already possible, I humbly beg forgiveness and would appreciate a link to read the relevant documentation.

**Comment by xiaq** [comment]
Documented in https://elvish.io/ref/builtin.html#value-out-indicator.

**Comment by krader1961** [comment]
It's nice that you allowed for an arbitrary string rather than a single character. This means you can include escape sequences to do things like change the color. You can't see it here but the hash-mark is rendered in green:

```
~/go/src/github.com/elves/elvish> value-out-indicator = "\e[32m#\e[m "
~/go/src/github.com/elves/elvish> put $value-out-indicator
# "\e[32m#\e[m "
```

I didn't see any obvious way to specify the style of the text in an abstract manner rather than hardcoding the escape sequences. Using `le:styled` as documented in issue #199 no longer works and there doesn't seem to be anything relevant in the docs.

Is the intent that people should use the external `tput` command? Would introducing a builtin analogous to fish's `set_color` command be accepted?

**Comment by xiaq** [comment]
The `le:` module is now known as `edit:`.

It is not ideal, but you can use `echo` to convert the output of `edit:styled` to a string: `value-out-indicator = (echo (edit:styled '# ' green))`
