### ISSUE TITLE
A Richer Pipeline

### ISSUE THREAD

**Issue by zikes** [elves/elvish#52]
Have you considered something like the Redis protocol?

http://redis.io/topics/protocol

It's easy to understand and extensible, streamable, and could support complex objects.

**Comment by xiaq** [comment]
We already have a "rich" pipeline implemented with golang channels. Using Redis will not make it any richer :)

**Comment by zikes** [comment]
You misunderstand.  I'm referring to your plan for moving data across processes using shell pipes  via stdin/stdout.  My suggestion is not to use Redis, but to replace (or rather supplement) the current convention of newline-separated strings with a raw []byte-based protocol that does not rely on simple string splits.  I use Redis's protocol as an example because it precedes each object with an identifier that includes the object's length in bytes, making it easy to parse with no pesky newline issues such as those you cite here: https://github.com/elves/elvish#the-drawbacks-of-traditional-pipelines

**Comment by xiaq** [comment]
@zikes That makes sense, but your original comment was lacking in information.

We cannot change the semantics of pipelines between external commands, and pipelines between internal commands are fine as they are. That leaves the potential use of redis to the interfacing between internal and external commands. And we'd better make the interfacing step explicit, since the user may prefer some other serialization methods instead (say JSON, XML, protocol buffer or [gob](http://blog.golang.org/gobs-of-data)). We can do it like:

    internal-that-outputs-values | dump-redis | external-that-takes-redis
    external-that-outputs-redis | parse-redis | internal-that-takes-values

Hence, supporting the interfacing between internal and external commands using the redis protocol just requires us to implement `dump-redis` and `parse-redis`, and no change to the existing pipelining mechanism is needed.
