### ISSUE TITLE
Add some solution to modify command line in after-readline hook

### ISSUE THREAD

**Issue by notramo** [elves/elvish#523]
Some solution would be cool to modify the command line after entering command.
For example, in interactive mode, if a command exits with non-zero, I want to see only one line:
`<command> exited with <number>.`
I want to achieve this by modifying the command after readline, and add `?()` and other things, but currently there is no solution for this.

**Comment by xiaq** [comment]
The particular functionality you are trying to achieve is #487; it has been inactive though.

Allowing arbitrary modifications to the command sounds like a potential dangerous feature, especially if the logics grows complex and the user is not given feedback or an option to cancel it. History expansion in bash is such an example: you type `sudo !-3` to repeat the third last command, but you might have miscounted and executed `sudo rm *` instead of `sudo apt install something`.

Elvish's approach is to always build such functionality into the editor, so that the user always knows what the command is before executing it. You browse through the command line history, pick one, and then execute it.

Do you have other use cases for modifying commands before execution? Can they be solved by building an editor plugin instead?

**Comment by xiaq** [comment]
Closing this as the original use case is less necessary now that tracebacks are more compact, and there isn't another compelling use case.
