### ISSUE TITLE
Parse/compilation errors can cause Elvish to hang

### ISSUE THREAD

**Issue by adracea** [elves/elvish#543]
At this point I've tested just put and re: functions , the sequence in question is `"(\."` 

```
~> re:find "aaaaa.a" "(\.)"
Parse error: invalid escape sequence
  [interactive], line 1:
    re:find "aaaaa.a" "(\.)"
```

```
~# put "(\.)"
Parse error: invalid escape sequence
  [interactive], line 1:
    put "(\.)"

```
After entering one of these the client seems to become unresponsive . The problem seems to be with the parser .
Update : The root cause is in the doubleQuoted function of the parser and it has to do with the `.` character .

Update 2 : Also tested on the phone , was able to pin it to something introduced in the last 88 commits as I was using an outdated version and it wasn't replicating before updating the local repo and rebuilding .

**Comment by HtwoO** [comment]
The following showed all command and their output since elvish was started to it hanged.

[bnw@bnw-mbp u-root]$ elvish 
74487
~/project/go/src/github.com/u-root/u-root> echo $GOPATH
Compilation error: variable $GOPATH not found
  [interactive], line 1:
    echo $GOPATH
~/project/go/src/github.com/u-root/u-root> ls -l $GOPATH/bin/elvish
Compilation error: variable $GOPATH not found
  [interactive], line 1:
    ls -l $GOPATH/bin/elvish
~/project/go/src/github.com/u-root/u-root> goroutine 21 [running]:   bnw@bnw-mbp.local
github.com/elves/elvish/sys.DumpStack(0xc42001b5c0, 0xc42012e4e0)
	/Users/bnw/project/go/src/github.com/elves/elvish/sys/dumpstack.go:10 +0xa2
github.com/elves/elvish/program/shell.handleSignal(0x1789440, 0xc4203546d0)
	/Users/bnw/project/go/src/github.com/elves/elvish/program/shell/sys_unix.go:19 +0x7b
github.com/elves/elvish/program/shell.handleSignals.func1(0xc4201620c0)
	/Users/bnw/project/go/src/github.com/elves/elvish/program/shell/shell.go:210 +0xc7
created by github.com/elves/elvish/program/shell.handleSignals
	/Users/bnw/project/go/src/github.com/elves/elvish/program/shell/shell.go:207 +0x8a

goroutine 1 [select]:
github.com/elves/elvish/edit.(*Editor).ReadLine(0xc4201758c0, 0x0, 0x0, 0x0, 0x0)
	/Users/bnw/project/go/src/github.com/elves/elvish/edit/editor.go:361 +0x5b0
github.com/elves/elvish/program/shell.interact.func1(0xc42015c7e0, 0x151da4a, 0xd, 0xc42041e300)
	/Users/bnw/project/go/src/github.com/elves/elvish/program/shell/shell.go:160 +0x2f
github.com/elves/elvish/program/shell.interact(0xc42015c7e0)
	/Users/bnw/project/go/src/github.com/elves/elvish/program/shell/shell.go:171 +0x207
github.com/elves/elvish/program/shell.(*Shell).Main(0xc42013cc80, 0xc420010180, 0x0, 0x0, 0x0)
	/Users/bnw/project/go/src/github.com/elves/elvish/program/shell/shell.go:62 +0x209
github.com/elves/elvish/program.Main(0xc420010180, 0x1, 0x1, 0x0)
	/Users/bnw/project/go/src/github.com/elves/elvish/program/program.go:118 +0x18a
main.main()
	/Users/bnw/project/go/src/github.com/elves/elvish/main.go:12 +0x45

goroutine 5 [syscall]:
os/signal.signal_recv(0x1789440)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/sigqueue.go:131 +0xa7
os/signal.loop()
	/usr/local/Cellar/go/1.9.2/libexec/src/os/signal/signal_unix.go:22 +0x22
created by os/signal.init.0
	/usr/local/Cellar/go/1.9.2/libexec/src/os/signal/signal_unix.go:28 +0x41

goroutine 18 [chan receive]:
github.com/elves/elvish/eval.init.9.func1()
	/Users/bnw/project/go/src/github.com/elves/elvish/eval/port.go:56 +0x67
created by github.com/elves/elvish/eval.init.9
	/Users/bnw/project/go/src/github.com/elves/elvish/eval/port.go:55 +0x49

goroutine 19 [IO wait]:
internal/poll.runtime_pollWait(0x1d04f00, 0x72, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42013e218, 0x72, 0xffffffffffffff00, 0x1786d80, 0x1782590)
	/usr/local/Cellar/go/1.9.2/libexec/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42013e218, 0xc4201ab000, 0x1000, 0x1000)
	/usr/local/Cellar/go/1.9.2/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42013e200, 0xc4201ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/internal/poll/fd_unix.go:126 +0x18a
net.(*netFD).Read(0xc42013e200, 0xc4201ab000, 0x1000, 0x1000, 0x150d140, 0x1447b60, 0x1447b60)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/fd_unix.go:202 +0x52
net.(*conn).Read(0xc420134078, 0xc4201ab000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/net.go:176 +0x6d
bufio.(*Reader).Read(0xc42015a120, 0xc42013a790, 0x1, 0x9, 0xc420049ca8, 0x102b358, 0x153a430)
	/usr/local/Cellar/go/1.9.2/libexec/src/bufio/bufio.go:213 +0x30b
io.ReadAtLeast(0x1783cc0, 0xc42015a120, 0xc42013a790, 0x1, 0x9, 0x1, 0xc420021300, 0xc420413b00, 0x182)
	/usr/local/Cellar/go/1.9.2/libexec/src/io/io.go:309 +0x86
io.ReadFull(0x1783cc0, 0xc42015a120, 0xc42013a790, 0x1, 0x9, 0xc420049d10, 0x100612b, 0x3)
	/usr/local/Cellar/go/1.9.2/libexec/src/io/io.go:327 +0x58
encoding/gob.decodeUintReader(0x1783cc0, 0xc42015a120, 0xc42013a790, 0x9, 0x9, 0xc420049d88, 0x102ac99, 0xc400000008, 0xc420058080)
	/usr/local/Cellar/go/1.9.2/libexec/src/encoding/gob/decode.go:120 +0x63
encoding/gob.(*Decoder).recvMessage(0xc42013e400, 0xc420049da0)
	/usr/local/Cellar/go/1.9.2/libexec/src/encoding/gob/decoder.go:80 +0x57
encoding/gob.(*Decoder).decodeTypeSequence(0xc42013e400, 0x153bd00, 0xc42013e400)
	/usr/local/Cellar/go/1.9.2/libexec/src/encoding/gob/decoder.go:144 +0x14c
encoding/gob.(*Decoder).DecodeValue(0xc42013e400, 0x144eea0, 0xc420142030, 0x16, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/encoding/gob/decoder.go:212 +0xe6
encoding/gob.(*Decoder).Decode(0xc42013e400, 0x144eea0, 0xc420142030, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/encoding/gob/decoder.go:189 +0x16d
net/rpc.(*gobClientCodec).ReadResponseHeader(0xc4201313e0, 0xc420142030, 0xc420413b00, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/rpc/client.go:223 +0x45
net/rpc.(*Client).input(0xc42015a1e0)
	/usr/local/Cellar/go/1.9.2/libexec/src/net/rpc/client.go:109 +0xb5
created by net/rpc.NewClientWithCodec
	/usr/local/Cellar/go/1.9.2/libexec/src/net/rpc/client.go:201 +0xc5

goroutine 20 [select, locked to thread]:
runtime.gopark(0x153bc90, 0x0, 0x151956c, 0x6, 0x18, 0x1)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/proc.go:287 +0x12c
runtime.selectgo(0xc420027750, 0xc420162180)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/select.go:395 +0x1149
runtime.ensureSigM.func1()
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/signal_unix.go:511 +0x1fe
runtime.goexit()
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/asm_amd64.s:2337 +0x1

goroutine 22 [IO wait]:
internal/poll.runtime_pollWait(0x1d04cc0, 0x72, 0x1)
	/usr/local/Cellar/go/1.9.2/libexec/src/runtime/netpoll.go:173 +0x57
internal/poll.(*pollDesc).wait(0xc42012e978, 0x72, 0xffffffffffffff01, 0x1786d80, 0x1782590)
	/usr/local/Cellar/go/1.9.2/libexec/src/internal/poll/fd_poll_runtime.go:85 +0xae
internal/poll.(*pollDesc).waitRead(0xc42012e978, 0xc4201cc001, 0x1000, 0x1000)
	/usr/local/Cellar/go/1.9.2/libexec/src/internal/poll/fd_poll_runtime.go:90 +0x3d
internal/poll.(*FD).Read(0xc42012e960, 0xc4201cc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/internal/poll/fd_unix.go:126 +0x18a
os.(*File).read(0xc4201342b8, 0xc4201cc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/os/file_unix.go:216 +0x4e
os.(*File).Read(0xc4201342b8, 0xc4201cc000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/os/file.go:103 +0x6d
bufio.(*Reader).fill(0xc42003df58)
	/usr/local/Cellar/go/1.9.2/libexec/src/bufio/bufio.go:97 +0x11a
bufio.(*Reader).ReadSlice(0xc42003df58, 0xc42002850a, 0x1012566, 0x1d01c80, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/bufio/bufio.go:338 +0x2c
bufio.(*Reader).ReadBytes(0xc42003df58, 0xa, 0x0, 0xc420028680, 0x1044587, 0x1000, 0x1462c60)
	/usr/local/Cellar/go/1.9.2/libexec/src/bufio/bufio.go:416 +0x6b
bufio.(*Reader).ReadString(0xc420028758, 0x100a, 0x1000, 0xc4201cc000, 0x1000, 0x1000)
	/usr/local/Cellar/go/1.9.2/libexec/src/bufio/bufio.go:456 +0x38
github.com/elves/elvish/edit.NewEditor.func1(0xc4201342b8, 0x0, 0x0, 0xc4201758c0)
	/Users/bnw/project/go/src/github.com/elves/elvish/edit/editor.go:119 +0x1d6
created by github.com/elves/elvish/edit.NewEditor
	/Users/bnw/project/go/src/github.com/elves/elvish/edit/editor.go:116 +0x2ef

goroutine 23 [chan receive]:
github.com/elves/elvish/edit.NewEditor.func2(0xc4201623c0, 0xc4201758c0)
	/Users/bnw/project/go/src/github.com/elves/elvish/edit/editor.go:131 +0x118
created by github.com/elves/elvish/edit.NewEditor
	/Users/bnw/project/go/src/github.com/elves/elvish/edit/editor.go:130 +0x31b

goroutine 232 [syscall]:
syscall.Syscall6(0x5d, 0x7, 0xc420278600, 0x0, 0x0, 0x0, 0x0, 0x0, 0xc420060d01, 0xc42003fd00)
	/usr/local/Cellar/go/1.9.2/libexec/src/syscall/asm_darwin_amd64.s:41 +0x5
syscall.Select(0x7, 0xc420278600, 0x0, 0x0, 0x0, 0x0, 0x0)
	/usr/local/Cellar/go/1.9.2/libexec/src/syscall/zsyscall_darwin_amd64.go:1048 +0xa3
github.com/elves/elvish/sys.Select(0x7, 0xc420278600, 0x0, 0x0, 0x0, 0xc42000e010, 0xc42003fea7)
	/Users/bnw/project/go/src/github.com/elves/elvish/sys/select_bsd.go:8 +0x53
github.com/elves/elvish/sys.WaitForRead(0xc42003fee8, 0x2, 0x2, 0x0, 0x1, 0x0, 0x0, 0x0)
	/Users/bnw/project/go/src/github.com/elves/elvish/sys/waitforread_unix.go:23 +0x13f
github.com/elves/elvish/edit/tty.(*runeReader).run(0xc42013d440)
	/Users/bnw/project/go/src/github.com/elves/elvish/edit/tty/rune_reader_unix.go:67 +0x91
created by github.com/elves/elvish/edit/tty.(*runeReader).Start
	/Users/bnw/project/go/src/github.com/elves/elvish/edit/tty/rune_reader_unix.go:58 +0x3f

**Comment by xiaq** [comment]
This bug was introduced in 0f7f29a51dd2e4b6b47745fd078084be2771f7dc.
