### ISSUE TITLE
[WIN64] Elvish turns all inputs to upper case if NUMLOCK is enabled

### ISSUE THREAD

**Issue by be5invis** [elves/elvish#567]
![image](https://user-images.githubusercontent.com/240091/35082619-d9de71e0-fc55-11e7-8f44-682952043711.png)

**Comment by xiaq** [comment]
That sounds like a bug in the Windows version of the terminal reader, which I remember is indeed somewhat hacky. Which version of Windows and Elvish are you running? How did you launch `elvish.exe`?

**Comment by be5invis** [comment]
In Windows 10 16299 it works fine, but in Windows 10 17074 (RS4 Insider Slow) it does not work.
`elvish-windows-amd64-0.11`

**Comment by be5invis** [comment]
- 16299: No repro
- 17074: Repro
The same issue does not occur in other Windows console programs (like node.js).
Hmmm you may need a short C or GO code that could reproduce this. If it's an Windows issue I'll report it to the Console team.

**Comment by miniksa** [comment]
If you turn off your NumLock, Elvish works correctly. If you have it on, it will process everything as a capital letter.

I checked the current Windows Insider previews (RS4) as well as the previous 3 public releases of Windows 10 (RS3, RS2, RS1) and they all have the same behavior.

**Comment by xiaq** [comment]
Aha. It seems that there is some bug in Elvish's recognition of modifers then.

**Comment by xiaq** [comment]
Funnily enough, I cannot reproduce this because it works on my only Windows machine and *it does not have a NumLock key*. /facepalm

The part of the code that reads Windows console events is https://github.com/elves/elvish/blob/1ab103aceed10eca03d7a46359fd09edd1014f41/edit/tty/reader_windows.go#L135-L226

There is quite some heuristics there; MSDN did not document precisely how the key codes behave when modifiers are applied.

I will take a look at this again when I do have access to a keyboard with a NumLock key. Or if any of you have worked with Windows's console API before, you can probably look at the code and spot something wrong there. It should also be possible to come up with a simple test program for that event reader.

**Comment by be5invis** [comment]
@xiaq try an OSK?
