### ISSUE TITLE
API for accessing deduplicated command history

### ISSUE THREAD

**Issue by notramo** [elves/elvish#568]
Please add a `&dedup` option to `edit:command-history`

**Comment by krader1961** [comment]
See also issue #1205. Having used shells like `ksh` and `bash` for at least two decades and `fish` for a much shorter period I much prefer the `fish` approach to eliminating older, duplicate, instances of a command invocation.

**Comment by krader1961** [comment]
I'm going to go ahead and implement this feature but still feel, as discussed here and in issue #1205, that Elvish should always dedup the interactive command history. That, however, might be controversial, if only from a performance perspective when recording the most recent command, and I'd rather get a change merged sooner rather than later that makes using `fzf` for selecting from the command history much faster. If deduplication becomes the default behavior a `&dedup` option can always be retained but ignored.

**Comment by krader1961** [comment]
Note that the default Ctrl-R binding ("histlist" navigation mode) defaults to dedup enabled. That, however, isn't documented anywhere nor is how to toggle between hiding and showing duplicates (answer: press Alt-d). Similarly, pressing UpArrow to walk though the command history also ignores duplicates.

What I'm still pondering is whether duplicate elimination should be the only behavior. The only reason for retaining duplicates is that you **might** want to see how many times, and when, you ran a particular command. Not just the most recent instance. That is theoretically useful but in practice isn't particularly useful and people almost always want only the most recent instance of an interactive command. I say that as someone who started using UNIX around 1984 and have used shells without (ksh) and with (fish) interactive command deduplication.
