### ISSUE TITLE
Pour go's strings package into a "str:" module

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#576]
In the same spirit of pouring Go's `regexp` package into the `re:` module, let's do the same to the excellent `strings` package.

**Comment by occivink** [comment]
Would `joins` and `splits` be moved to that module?

**Comment by xiaq** [comment]
@occivink Yes, and they will be renamed `str:join` and `str:split`.

**Comment by krader1961** [comment]
Which, if any, elvish commands should automatically coerce their values to strings if they expect that argument to be a string? I'm asking this in the context of PR #928 and PR #934. What does it mean to pass a `(float64 ...)` as an argument to a command that requires a string. Should elvish automatically convert the value or should we require the user to do a `(to-string $value)`? Given the recent introduction of a `float64` data type is it reasonable to require the user to use `to-string` when passing the value of a variable to a command that requires a string?

**Comment by krader1961** [comment]
@xiaq Should builtins like `has-prefix` be marked as deprecated and the reader told to use `str:has-prefix`? Or should the documentation be left as is but with a note that the command is simply an alias for the equivalent `str:` command and the `str:` form is preferred?

**Comment by krader1961** [comment]
Also, if `has-prefix` is simply an alias for `str:has-prefix` shouldn't the former defer to the latter rather than reinvent the wheel? Which reinvention leading to possible incompatible behavior?

**Comment by zzamboni** [comment]
@xiaq has described somewhere (but I can't find it at the moment) his idea for deprecating features over a two-release cycle, I think this is the way this could be handled.

**Comment by krader1961** [comment]
@zzamboni Understood, vis-a-vis the deprecation model. In fact, that's the model I normally use for this situation. So I've created a PR to formally deprecate the `has-prefix` and `has-suffix` builtins and start the clock ticking. Which doesn't necessarily mean they will actually be removed prior to the 0.16 release but it does put people on notice that they need to start using the commands in the `str:` rather than the `builtin:` name space. Note that `str:has-prefix` and `str:has-suffix` was introduced by commit 9d342125f way back on 2018-01-26. Since the `str:` name space seems unlikely to go away it's time to start simplifying the `builtin:` name space by removing such redundancies.

**Comment by krader1961** [comment]
@xiaq, It seems like this can be closed. While we haven't poured the entirety of Go's `string` package into the `str` module we've got all the most useful functions. Other functions can be handled on a case-by-case basis as people find a need a particular function.

**Comment by xiaq** [comment]
Sounds good, closing.

**Comment by tfga** [comment]
The [docs](https://elv.sh/ref/builtin.html#joins) already say

> `joins` is deprecated and; use `str:join` instead.

but that's not the reality of the latest release:

```elvish
$ elvish --version
v0.13.1

$ elvish

$ resolve joins
▶ '$joins~'

$ resolve str:join
▶ '(external str:join)'
```

It would be nice if there was a way to keep these things in sync.  
Maybe instead of having just one URL for the docs, we could have one for each version? 🤔

**Comment by krader1961** [comment]
@tfga, Good point about the online documentation not making it clear that you're reading the docs for the "master" branch, not the most recent released version. I'll open an issue about that. But note that you'll get the same result using elvish built from the "master" branch because you didn't first do `use str`.

**Comment by tfga** [comment]
@krader1961 Thanks! :+1: 

> you didn't first do `use str`

Fixed in my comment.
