### ISSUE TITLE
Command to import history from other sessions

### ISSUE THREAD

**Issue by notramo** [elves/elvish#638]
There is session **A**.
Enter some commands.
Open session **B**.
The **B** session will have the commands in its history that were entered in session **A** *until the launching* of session **B**.
Enter some commands in both session. These commands will be only visible in the session they were entered.
If this command is launched in a session, the history of the other session would be merged with its own history.

**Comment by zzamboni** [comment]
Shared history might be nice. Since all the shells are logging history to the same database, it should be sufficient to have a way to re-read the command history into the current shell.

**Comment by notramo** [comment]
I think it should be done with a special command. Maybe a variable to enable continous importing (e.g. `edit:realtime-import-history = $true`)
I often repeat three or four commands in a session in the same ordering (e.g. when playing with a language, or searching for bugs), then pressing the history up button 2-3 times is quite fast solution. If it would be continously imported, the commands from other sessions would bloat the session history, so the history up button should be pressed more times (but in other cases, continous importing can be comfortable, so I think the shell should have a variable that controls this).

**Comment by xiaq** [comment]
I plan to implement a function `edit:history:fast-forward`.

The way history works now is that when a new session starts up, it queries how many items there already are in the permanent history. After that, the session's view of the permanent history is frozen; items added after the session startup is simply not seen. The session also maintains an in-memory, session-local history. When you append a new entry, it is appended to both permanent history and the session-local history. When you access the history in e.g. history mode, the two parts are "fused" together (this is implemented by [`edit/history.Fuser`](https://github.com/elves/elvish/blob/master/edit/history/fuser.go).)

"Importing" history from other sessions will essentially do two things: move the pointer to the permanent history forward (to the very end), and clear the session-local history. The second part is important, because otherwise you will see the session-local history twice. Hence it is really more complex than that "import" and that is why I call the command `fast-forward`.

I am not sure about how to name the variable though. The variable would basically disable the entire behavior of the fuser and makes the history view equivalent to the permanent history. I am thinking about `edit:history:disable-per-session`, but that doesn't really imply its relationship with `fast-forward`.

**Comment by notramo** [comment]
In my opinion, `edit:history:disable-per-session` is a good name.

**Comment by zzamboni** [comment]
I'm not completely sure whether this should be enabled by Elvish (i.e. the variable), as it can be easily implemented by just adding `edit:history:fast-forward` to the `before-readline` prompt hook.

If there's going to be a variable, I would vote for `$edit:history:global`.

**Comment by notramo** [comment]
I have tried to implement a temporary solution with hooks (I also changed the `$edit:history:start~` variable), but there are a lot of corner cases, and the config file is ugly. For example, if the `history` mode is active, commands entered in other sessions don't show up until the currentt history mode is closed, and restarted.

**Comment by zzamboni** [comment]
I tried modifying `$edit:history:start~` like this:
```
[~]─> old-hist-start = $edit:history:start~
[~]─> edit:history:start~ = { edit:history:fast-forward; $old-hist-start }
```

But when I start history mode (e.g. up arrow), I don't see the history from other terminals.

**Comment by notramo** [comment]
This works for me, but if a command is entered in another session, it don't shows up until the history mode is restarted.

**Comment by xiaq** [comment]
Aha. I filed #731 for what you discussed after I closed the issue.
