### ISSUE TITLE
epm:upgrade failure on Funtoo Linux

### ISSUE THREAD

**Issue by iwoloschin** [elves/elvish#655]
I'm having issues with epm:upgrade on a Funtoo Linux machine using the latest Elvish.

```
$ epm:upgrade
/usr/bin/find: paths must precede expression: 2
Usage: /usr/bin/find [-H] [-L] [-P] [-Olevel] [-D help|tree|search|stat|rates|opt|exec] [path...] [expression]
Exception: find exited with 1
Traceback:
  , line 285:
          find $-lib-dir/$dom -type d -depth $lvl | each [pkg]{
  , line 283-288:
        if $cfg {
          lvl = $cfg[levels]
          find $-lib-dir/$dom -type d -depth $lvl | each [pkg]{
            replaces $-lib-dir/ "" $pkg
          }
        }
  , line 278-289:
      e:ls $-lib-dir | each [dom]{
        cfg = (-domain-config $dom)
        # Only list domains for which we know the config, so that the user
        # can have his own non-package directories under ~/.elvish/lib
        # without conflicts.
        if $cfg {
          lvl = $cfg[levels]
          find $-lib-dir/$dom -type d -depth $lvl | each [pkg]{
            replaces $-lib-dir/ "" $pkg
          }
        }
      }
  , line 330:
        pkgs = [(installed)]
  , line 329-332:
      if (eq $pkgs []) {
        pkgs = [(installed)]
        -info 'Upgrading all installed packages'
      }
  [tty], line 1:
    epm:upgrade
```

It works fine on macOS, same version of Elvish.  Presumably some sort of issue with the `find` utility between macOS & Linux?  I potentially have access to an 16.04 Ubuntu box to test on as well if that's helpful.

**Comment by zzamboni** [comment]
Thanks for the report. Unfortunately, Funtoo Linux is obscure enough that I can't find a ready-to-use Vagrant image to use for testing. Can you reproduce it in Ubuntu or some other Linux variant?

The error is strange, since `$-lib-dir/$dom` is clearly before the expression. Can you run `put $epm:-lib-dir` to see if it's properly defined?

**Comment by iwoloschin** [comment]
If you can find something based off Gentoo that's probably close enough.  I'll see if I can reproduce on the 16.04 Ubuntu machine too.

```
$ put $epm:-lib-dir
▶ /home/iwoloschin/.elvish/lib
```

I've also been able to do `epm:install` and that works fine, though I can't remember if that's trying to do anything with `find` or not.

**Comment by zzamboni** [comment]
I managed to install a funtoo VM and have diagnosed the problem - indeed it is caused by differences in the `find` command. On macOS (which has BSD find by default), `-depth` allows specifying an optional argument: `-depth n` is equivalent to `-mindepth n -maxdepth n`, but GNU find apparently does not support this.

I will look into the best way to fix this (preferably getting rid of the dependency of `find` altogether). In the meantime, you can add the following to your `rc.elv` to replace `epm:installed` with a fixed version:

```
use epm

epm:installed~ = {
  e:ls $epm:-lib-dir | each [dom]{
    cfg = (epm:-domain-config $dom)
    # Only list domains for which we know the config, so that the user
    # can have his own non-package directories under ~/.elvish/lib
    # without conflicts.
    if $cfg {
      lvl = $cfg[levels]
      find $epm:-lib-dir/$dom -type d -mindepth $lvl -maxdepth $lvl | each [pkg]{
        replaces $epm:-lib-dir/ "" $pkg
      }
    }
  }
}
```

**Comment by iwoloschin** [comment]
Awesome, thanks!  This works well as a workaround, though I suppose we should probably leave the issue open until it can be properly fixed?

**Comment by zzamboni** [comment]
@iwoloschin I have submitted a PR which fixes the use of external commands in `epm:installed`. In the meantime, you can use the new version of the command by adding this to your rc.elv:

```
  epm:installed~ = {
    put $epm:-lib-dir/*[nomatch-ok] | each [dir]{
      dom = (re:replace &literal $epm:-lib-dir/ '' $dir)
      cfg = (epm:-domain-config $dom)
      # Only list domains for which we know the config, so that the user
      # can have his own non-package directories under ~/.elvish/lib
      # without conflicts.
      if $cfg {
        lvl = $cfg[levels]
        pat = '^\Q'$epm:-lib-dir'/\E('(repeat (+ $lvl 1) '[^/]+' | joins '/')')/$'
        put (each [d]{ re:find $pat $d } [ $epm:-lib-dir/$dom/**[nomatch-ok]/ ] )[groups][1][text]
      }
    }
  }
```
