### ISSUE TITLE
Variable $:local does not exist, compiler bug

### ISSUE THREAD

**Issue by Makefile-dot-in** [elves/elvish#667]
When assigning stuff to the local namespace like so:

    local[test] = 2

it fails with;

    Exception: variable $:local does not exist, compiler bug
    [tty], line 1: local[e] = 2

I'm using elvish-0.11_4 from the Void Linux repos.

**Comment by zzamboni** [comment]
You need to create the variable as a map before being able to assign values to its elements:
```
[~]─> local = [&]
[~]─> local[test] = 2
```

Alternatively, you can initialize it in the declaration already with some elements:

```
[~]─> local = [&test= 2]
```

See https://elvish.io/ref/language.html#map for the syntax.

**Comment by krader1961** [comment]
In addition to @zzamboni's answer I'll point out that's not how you create a var in the local namespace. See https://elvish.io/ref/language.html#scoping-rule:

```
test = 1
{ put $test; local:test = 2; put $local:test; put $test }
put $test
```

**Comment by zzamboni** [comment]
Right - thanks @krader1961 - I missed the part of trying to assign to a variable in the `local` scope :)

**Comment by Makefile-dot-in** [comment]
Closing as I'm trying to use a feature that isn't in 0.11: namespace introspection.

**Comment by xiaq** [comment]
* The correct syntax for introspecting the `local` namespace is `$local:[var-name]`. Note the trailing `:` after `local`.

* You cannot create new variables using introspection, only accessing existing variables. This is intentional.

* The `local` namespace cannot be introspected in this way yet, while namespaces created by `use` can be. This is now tracked in #668.
