### ISSUE TITLE
Make spaces around `=` compulsory for non-temporary assignment

### ISSUE THREAD

**Issue by kwshi** [elves/elvish#705]
The [language manual](https://elv.sh/ref/language.html) states this:

> A variable can be assigned by writing its name, `=`, and the value to assign. **There must be inline whitespaces both before and after `=`.**

Yet this happens:

```
~> x = 2
~> put $x
▶ 2
~> x=1
~> put $x
▶ 1
```

It seems then that the *must be inline whitespaces* requirement is not a requirement at all.

Meanwhile, it is worth noting that the no-spaces syntax seems to be parsed as the temporary-assignment syntax, with the mere difference that assignments persist:

```
~> x=2 y=3
~> put $x $y
▶ 2
▶ 3
```

So a possibly more accurate description of this issue is that *temporary assignments with no command cause assignments to persist*.

This is not *necessarily* a bug: it can be a design choice to keep this behavior.  I would argue, however, that it should not be the desired behavior, since it seems to introduce inconsistent ways of assigning variables and seemingly contradicts the documentation.

**Comment by xiaq** [comment]
A left-over I forgot to clean up. Historically Elvish behaves like POSIX sh: the spaceless form is the only assignment form, and it is permanent if there are no commands following it.

**Comment by krader1961** [comment]
Argh! I just attempted to use this pipeline from https://stackoverflow.com/questions/2720014/how-to-upgrade-all-python-packages-with-pip:

```
pip list --outdated --format=freeze | grep -v '^\-e' | cut -d = -f 1  | xargs -n1 pip install -U
```

I was surprised to find it did not update my outdated python packages. Nothing happened -- not even a diagnostic message. It took me approximately 30 minutes before I realized the equal-sign, as the `cut` delimiter, was the problem since it implied an assignment.

What do you expect this command to output:

```
echo a=b | cut -d = -f 1
```

In any POSIX shell that will output `a`. In Elvish you get nothing because elvish treats the RHS as a pair of  assignments: `cut = -f` and `-d = 1`.

I am not arguing that Elvish should behave like POSIX shells in this respect. I'm only pointing out a hard to debug user mistake given the current behavior.

**Comment by krader1961** [comment]
@xiaq, Commit 37c3c0b0ded222e0d75f5aea14c59b74387d334e would seem to resolve this issue. The current behavior is deprecated and will be removed in the near future. Whether this is closed now, since the misfeature is deprecated, or later when it is actually removed is an open question.

**Comment by xiaq** [comment]
Yes, `x=a` no longer works except when used for temporary assignment. 🎉
