### ISSUE TITLE
Question: Shell to restrict / enable certain commands

### ISSUE THREAD

**Issue by rmasci** [elves/elvish#725]
Hi, 

Is there a way to capture a command that the user types, and before that command is run have that command checked to make sure that user is allowed to run that command based off a list that might be stored someplace?  I doubt this is a part of the code currently... but is there a way I could modify it to do that?

Thanks

**Comment by notramo** [comment]
How would this apply to scripts?

**Comment by krader1961** [comment]
In addition to @notramo's question how would this apply to functions? If the user defined a function with the same name as an allowed command but the function used commands not allowed what should happen? I don't think you have thought through the implications of what you're trying to do.

**Comment by rmasci** [comment]
Security policies in the company are in favor of granting sudo permissions,
and only a select few should have full root access. The issue that I am
having is that I have to write procedures for my end users to execute as a
part of an installation, and what happens is EVERY command winds up being a
sudo command. I wondered if it would be better to have a shell that worked
in reverse of sudo, and restricted the commands you're allowed to run. So
lets say you're not allowed to run /usr/local/bin/foobar as root. Well you
can still run /usr/local/bin/foobar, but either not run the command or
you'd run it as your user instead of root. Foolproof? No, but neither is
sudo.   Maybe it's not that great of an idea.  Thanks!

**Comment by krader1961** [comment]
@rmasci Your idea is not unreasonable at first glance but it is definitely not as useful as it seems. The idea you had is okay for basic "sanity" checks which provide useful feedback to the user about what they did wrong. But it is completely useless from a security perspective.

**Comment by xiaq** [comment]
Several remarks:

Security based on controlling the commands a user can run is a pretty old idea. While it can work in principle, in practice it almost never works. See [restricted shell](https://en.wikipedia.org/wiki/Restricted_shell).

> Security policies in the company are in favor of granting sudo permissions, and only a select few should have full root access.

There are two ways you can grant sudo permission, with command restrictions and without. If they are granted with command restrictions you probably won't be asking the question here, so I assume it is without. Granting sudo permission without command restriction **is** full root access. Just run `sudo sh`.

I feel that you are probably not really asking for a security mechanism, but a stupidness prevention mechanism. I can think of two models of stupidness prevention:

* Preventing people who have sudo permissions from doing stupid things, because they are not professional sysadmins, but need to do sysadmin work now and then. In that case, maybe set up a custom directory with symlinks to the commands they are supposed to use, and point `$PATH` to just that directory? If they know enough to modify `$PATH` they probably should know what they are doing.

* Preventing a script from doing stupid things. The script needs to touch a lot of places in the system, but it is also intertwined with some not-so-sysadmin-ish things, like asking the user for input, and you are afraid that some bug in it will burn your system. Running the entire script as `root` is too risky, but annotating every system-touching command with `sudo` is too tedious.

  In that case, try separating the system-touching and non-system-touching part. For instance, put the non-system-touching part in a "safe" script, and the system-touching part in another "unsafe" script. The user runs the "safe" script with normal privilege, the "unsafe" one as `root`. The former can write some kind of config file to be picked up by the latter.

**Comment by rmasci** [comment]
What the users do now is just do a sudo su - and become root. I don't like
this, but on the other hand they don't want to keep typing sudo for every
command.  What I want to do is give them a shell that can read in the sudo
list, and only execute those commands as root. all others run as that user.
This would also allow you to write in restrictions such as having the
rights to remove files, but not files in the /etc directory, or you can't
remove the kernel. Trying to make sudo easier is the goal. I could probably
setup some kind of alias script that loops through the contents of sudo -l:
alias mv='sudo mv' or something like that.  Thought it would be more
elegant to do this within a shell... but whatever.

**Comment by krader1961** [comment]
> What I want to do is give them a shell that can read in the sudo list, and only execute those commands as root. all others run as that user.

Gah! No! This is not the shell's responsibility. What about alternative elevated privilege mechanisms such as the `runas` command? If you are allowing people to do `sudo su -` you already have  significant security problems that aren't solved by your proposal. Furthermore, how would elvish determine whether to run the command as the user or as root based solely on whether the `sudo` configuration granted them the ability to run that command as root? If the user is already typing the commands in a REPL elvish shell with root privilege there is no way to stop them from doing harmful actions from within the shell.

@xiaq, I think this should be closed as infeasible and outside the scope of any shell, let alone Elvish.

**Comment by rmasci** [comment]
I don't think anyone gets the idea, this isn't a general shell you'd use by
default, but a shell you'd execute to give yourself elevated rights without
giving away ALL rights. Right now we have a problem users login to a system
and immediately run sudo su - and become root. It's a problem. I don't like
it, and I've told management about it, and that sooner or later someone is
going to destroy a critical system because of it. The main reason they do
this is that when the sudo su - to root, they don't have to think about
which commands require sudo, or that they'll have to type sudo in front of
every command.  I want to replace 'sudo su -' which gives them everything.
So users 'think' they're root -- all commands are assumed to be run by root
as if you've elevated your access to root. Let me give you an example using
a modified version of Elvish.  I call this command sudoshell, and at first
login user 'rich' is in a bash shell, then executes sudoshell instead of
sudo su - for elevated permissions:

[rich@mysystem ~$] sudoshell
Type 'showmesudo' to see them all.To run a command without sudo, put a @ in
front of the command. '@ ls /root', 'ls /root' would be run without sudo --
if sudo was defined for the ls command.
[rich@mysystem /home/rich]# rm /etc/passwd
/bin/rm: remove write-protected regular file '/etc/passwd'? y
/bin/rm: cannot remove '/etc/passwd': Permission denied
Exception: rm exited with 1
[tty], line 1: rm /etc/passwd
[rich@mysystem /home/rx7322]# cp /etc/passwd /etc/passwd.sav
Match: cp /etc/passwd /etc/passwd.sav
[rich@mysystem /home/rich]#

In this example user 'rich' couldn't remove /etc/passwd. But since this
user has the sudo rights to copy a file, they could copy /etc/passwd to
/etc/passwd.sav

**Comment by zzamboni** [comment]
@rmasci I think I understand your use case, but I still agree with @krader1961 that this is not the role of the shell. From your explanation above:

> I am having is that I have to write procedures for my end users to execute as a part of an installation, and what happens is EVERY command winds up being a sudo command.

If this is a custom sequence of commands, I would suggest again that it might be best written as a script that your users execute. The script can then use `sudo` whenever it needs, and work for the users is even reduced. If parameters are needed, the script could either ask for them (a la `./configure` scripts), or accept them as parameters.

**Comment by rmasci** [comment]
Yeah you know I totally agree.  It’s not really the function Of a shell,
and I have a few ideas that might work to do what I want. I do have a
version of elvish that does read the Sudo list and injects the sudo command
for a user but honestly I thin another way would be better. I developed it
a while back and forgot why I abandoned the idea.

**Comment by krader1961** [comment]
> this isn't a general shell you'd use by default, but a shell you'd execute to give yourself elevated rights without giving away ALL rights

I understood that point of your argument.

> I want to replace 'sudo su -' which gives them everything. So users 'think' they're root -- all commands are assumed to be run by root as if you've elevated your access to root

What you are trying to say? After someone executes `sudo su -` they are root -- without your scare-quotes that imply they aren't really the root user. You seem to be suggesting that a user of an elvish shell instance that has this feature enabled will automatically run commands via `sudo` if the sudo configuration allows the user to run the command with elevated privileges. This is fractally wrong. Which is to say, it's a bad idea on several levels. Not least of which is it is intimately tied to the `sudo` command. Which itself may have different behaviors, and config file syntax, depending the sudo version.

**Comment by zzamboni** [comment]
> I do have a version of elvish that does read the Sudo list and injects the sudo command for a user but honestly I thin another way would be better.

I fully agree that any other way would be better - this is a bad idea for multiple reasons. The first one that comes to mind is that if your modified shell is automatically inserting `sudo` for commands in the list, then **any** execution of that command will get run as root. This can have very bad unintended consequences for common commands like `cp`, `ls` or `rm`. You may need to run it with sudo for some things, but running it with privileges every time is a recipe for disaster.

One more idea: instead of a script, wrap the special commands your users must run into an Elvish library. That way, you can provide an abstracted, and possibly even easier-to-use, process to your users. E.g. instead of executing a bunch of commands, some of them with `sudo`, they could simply run something like this:
```
use setup
setup:step1 param1 param2
setup:step2
setup:step3
```
(assuming you need to split things by steps, otherwise just wrap everything in a single function)

Inside each function you can call the commands with `sudo` as needed, and you have full control over the sequence. Your users have an easier experience and less likelihood of errors. As I understand your use case, your main goal is to make things as easy as possible for your users, so I assume this would be good for them.

**Comment by rmasci** [comment]
Diego — those are some of the reason I abandoned my work on it. I like the
module idea — thank you
