### ISSUE TITLE
Keep documentation for builtin functions and variables somewhere in the code

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#738]
To add a new builtin function or variable today, one needs to implement it in Go and amend the documentation under `website`. These can be done in the same commit (a step forward from when the website was in another repo). However, it would be even better if the documentation is in the code itself.

Doing this also allows we to provide the documentation within Elvish itself.

**Comment by krader1961** [comment]
The Korn shell source does this so that you can do `a_bltin --help` (the option parser knows about the embedded doc string). The result is that it is hard to read and edit the documentation due to the need to make the text conform to the language syntax for strings. It also makes it hard, if not impossible, to repurpose the documentation as HTML or in the "man" pages. Which means the ksh man page source is now out of sync with the builtin documentation. What we want to do in the ksh project is move the documentation into separate plain text files; one file per builtin command. Then modify the build process to transform those doc files into valid C modules that get built along with the main source. It then becomes trivial to take those same doc files and merge them into relevant man pages or reformat them as HTML.

**Comment by kwshi** [comment]
There are two design questions here.  First, implementation--how (where) should documentation for builtin functions be written (how best to keep code and documentation in-sync/up-to-date, how to keep them close to each other and organized clearly)?  Second, presentation--how should this documentation be accessed by the user?  These are not entirely separate questions, since implementation depends on choice of presentation, and implementation probably influences the available means of presentation, but these the the two main points to consider.

On implementation, I am in favor of having documentation be written in-line with the code, rather than in external "help" files.  This is the common trend in modern languages (Python uses docstrings, Go uses godoc, and, uh Java uses Javadocs?).  I propose that Elvish take on the same convention--that Elvish code written in Elvish adopt some commenting format (ideally simple, similar to Godoc) so that it can be parsed to generate documentation in various formats (HTML/PDF/man pages/whatever).  For Elvish builtins written in Go code, then, I would suggest that we directly use the Godoc comments.  This approach is, I think, the simplest and clearest: there are no multiple files to keep track of (and hence no requirement on developers to remember to make changes in multiple places on each commit), and no need to learn *another* way of doing things (i.e. new developers: where should I put the documentation?  What format, maybe, do I have to follow to comply with the documentation parser?)

On presentation, I suggest having a builtin `help` function.  It'll keep the documentation fairly organized, while still being fairly easy to access from the terminal.  It'll be analogous to a `man` for builtin features (we could also just write man pages directly, but I'm not as much a fan of that because some builtins have name conflicts with common existing programs).  I don't think I really care about being able to access the help via `builtin-fn --help` (or, per Elvish function-calling syntax, maybe `builtin-fn &help=$true` or perhaps eventually `builtin-fn &help`), and I'm fine without it.  But if we really wanted to, it should be doable to "inject" the builtins with these optional `help` arguments when applying them.

**Comment by krader1961** [comment]
@kwshi Please note that documentation about the code meant for a developer is quite different than end user documentation. The fish shell uses Doxygen as its tool for generating end user documentation. The entire team, including me (I was the main committer for ~2 years), hates it. And that's without the problems introduced by embedding the documentation in a form that is syntactically valid for the language (C++ in the case of fish and C for ksh). The fish team is planning on switching to Sphinx.

I see no justification for making it harder to read or edit the documentation by embedding it in the elvish Go source code. Proximity to the implementation should not be relevant. There should already be appropriate comments associated with every non-trivial function, data structure or variable.

Please do not repeat the mistake the ksh team did. Consider the embedded documentation for the [`set` command](https://github.com/att/ast/blob/ededd1148984c7d47c216908140bdf8821574ddf/src/cmd/ksh93/data/builtins.c#L170). Ignore the idiosyncratic DSL which serves as a way to specify acceptable arguments to ksh's equivalent of `getopt()`. Just notice how the need to make it conform to C syntax makes it harder to read and modify the text.

**Comment by kwshi** [comment]
@krader1961 I'm not particularly familiar with Sphinx and Doxygen, so perhaps you'll clarify on why you hated Doxygen, and what about Sphinx resolves those problems?

On the other things:
- The concern about "needing to make it [the documentation] conform to C syntax" (or in our case, Go) is hardly relevant, because my suggestion is not that we embed the documentation *as Go code* but rather as Godoc *comments*, which, other than the leading `//`, do not impose any syntax constraints that limit readability.
- The [Godoc comment format](https://blog.golang.org/godoc-documenting-go-code) is really minimalist--it has practically no constraints on syntax.  The only syntactical feature of Godoc is that any line with a leading indent is interpreted as a `pre-formatted code block`.  That's really minimalist, and in terms of readability/legibility, it definitely does not make editing documentation harder.
- I would disagree that "proximity [of documentation] to the implementation should not be relevant."  Sure, it might not be _the most important_ deciding factor in how we do documentation, but I think there's definitely some benefit to be observed about having the documentation for a function sit right above the function it documents.  Say, for example, a developer of Elvish decides to modify the API usage of some built-in function, such as `to-json`.  This developer finds the Go implementation of `to-json`, and modifies its usage as they please.  Now, if the documentation for this function were located directly above the function, the developer would immediately notice and be reminded (implicitly) to update the documentation for the function correspondingly.  Meanwhile, if the documentation sat somewhere else in a different folder among different files, the developer would need to actively remember that every time they make some change, they *also* have to go into that different folder to modify the documentation.  Having documentation and code in separate places makes it easier for documentation and behavior to go out of sync; having them close to each other makes it easier to keep them in sync.
- It is true that developer-documentation is generally different than end-user documentation.  In this case, however, note that the functions being documented are merely *Go implementations of Elvish functions*.  The "end user" is someone writing Elvish code, who wants to know how to call these Elvish functions.  The only thing *Go* about the function is that it is written in Go, but it is really in purpose and in spirit an Elvish function.  *Developers of Elvish* (that is, people contributing to the Elvish project and modifying the behavior of Elvish itself) do not actually call these functions in the Go code that powers Elvish.  Hence, the documentation for these functions is really targeted at the Elvish user, because the Elvish user is the one calling these functions and needs to know the behavior of these functions.  The comments *inside* the function clarifying certain lines of code may be for the developer, but the API documentation written in Godoc for these functions really only needs to be for the user.

The main limitation to using Godoc for documenting Elvish functions is extracting the documentation from the code.  If the documentation were in a separate file, in an unambiguous format, or if each function had its own documentation file, then documentation would be trivial to generate.  On the other hand, having the documentation be in Godoc requires us to do just a little bit more work.  I really don't think this work is too much, though; the existing [Godoc command-line tool](https://godoc.org/golang.org/x/tools/cmd/godoc) probably can already be used to extract, parse, and generate the documentation.  This means that the documentation-generation step (i.e. extracting from source, and then outputting to various HTML/man/`help` formats), could easily be incorporated into a Makefile directive.

**Comment by xiaq** [comment]
Finally got the time to read through all your comments and formulate my thoughts. Anyway, thanks, @krader1961 and @kwshi for your thoughts.

I agree with @kwshi on most points. @krader1961, you are concerned about the following things:

* Having to write docs as string literals adds unnecessary formatting burden. Well, we don't have to keep them as string literals; having them as Go comments is fine. You add leading `//` to each line, which isn't too cumbersome.

* Having the *entire* documentation generated by something like Doxygen will not give us a user-friendly documentation layout. What I am considering is different from that in two aspects:

  * As stated in the title, I am only interested in having the documentations of builtin functions and variables generated.

  * We are not going to use existing tool to generate those docs, because we are documenting (as @kwshi pointed out) *Go implementations of Elvish functions*, not a Go library; which means existing tools (most likely just `godoc`) doesn't really satisfy our need. We need to build something new, which means that we have total control over the organization and layout. In fact, the end result should look just like what we have now (e.g. https://elv.sh/ref/builtin.html).

**Comment by krader1961** [comment]
I guess I'm still confused. Is this meant to be documentation for developers about internal APIs? Or is it mean to be documentation for end users about the behavior of elvish functions and variables that just happen to be implemented in Go? If the former then Doxygen or whatever is typically used by the Go community makes sense. If the latter then I still don't think embedding user documentation in the source is the right solution. Consider functions and variables that are implemented in Elvish rather than  Go. How are they documented?

Certainly embedding the text as comment blocks is less painful than literal strings. But it's still painful. And you then have the problem of distinguishing the comments about implementation details from comments about user visible behavior. Sure, you can use the common IDE convention of using `///` (triple slashes) or something similar. Depending on your editor that may make editing such text more difficult.

**Comment by xiaq** [comment]
We have several options for where to put the documentation sources.

We can have them as comments before the implementation functions, like godoc. For instance, the doc for `cd` will be comments before the Go function that implements it: https://github.com/elves/elvish/blob/6b873a401fe747c91db75c7091e87f9bf81e3a31/eval/builtin_fn_fs.go#L37

This sounds natural but has the following drawbacks:

* We now need to analyze which functions are implementations of builtin functions. This is not straightforward.

* In the case of `cd`, the Go function is unexported and it is only called from Elvish, not other Go code, so the function doesn't really need a godoc. This is not necessarily the case. We might as well have a function that can be called from both Go and Elvish, and the relevant docs for the two audiences are not necessarily the same.

* At the implementation site, we don't actually know the name of the function. In the case of `cd` the Go function has the same name, but it doesn't have to be the case.

Instead, we can have them as comments near the "declaration" points. For instance, the doc for `cd` will be comments within the `addBuiltinFns` call: https://github.com/elves/elvish/blob/6b873a401fe747c91db75c7091e87f9bf81e3a31/eval/builtin_fn_fs.go#L18-L21

At this place we have access to the (Elvish) name of the function, and have no danger of mixing up doc intended for Go callers and docs intended for Elvish callers. We still need a way to identify those docs. We *could* just look for `addBuiltinFns`, but that is too magical. Better have some special "marker comment" to mark a *block* of Elvish function declarations. For instance, the docs for `cd` and `dir-history` can be like this:

```go
//elvish:functions-begin [1]
addBuiltinFns(map[string]interface{}{
    // Directory commands. [2]

    // ```elvish
    // cd $dirname
    // ```
    //
    // Change directory.
    //
    // Note that Elvish's `cd` does not support `cd -`. [3]
    "cd":          cd,
    // ```elvish
    // dir-history
    // ```
    // 
    // Return a list containing the directory history. Each element is a map
    // with two keys: `path` and `score`. The list is sorted by descending
    // score.
    // 
    // Example:
    // 
    // ```elvish-transcript
    // ~> dir-history | take 1
    // ▶ [&path=/Users/foo/.elvish &score=96.79928]
    // ``` [4]
    "dir-history": dirs,
})
//elvish:functions-end [5]
```

Notes:

1. The `//elvish:functions-begin` comment marks the start of a block of Elvish function declarations. The comment does not have a space between the `//`: this emulates "magical comments" recognized by the Go toolchain, which all start with `//go:`.

2. This comment block is not going to be part of the generated doc because it is followed by an empty line.

3. This comment block becomes the doc for `cd` because it is followed by the declaration for `cd`. Now, defining "declarations" can be a bit tricky. We can start with the kind-of-hacky definition of "a line that starts with a string literal, and the string literal is the function name".

4. This comment block becomes the doc for `dir-history`, like 3.

5. The `//elvish:functions-end` comment marks the end of the block.

Writing Markdown in comments does feel a bit funny though, but it is not nearly as bad as having to write Markdown in string literals.

**Comment by xiaq** [comment]
@krader1961, I think my proposal addresses your questions:

* This is for docs for Elvish users. In the Go community, docs for internal APIs are written as comments before functions, types, or the `package` statement; this is known as "godoc", which is also the tool for collecting such comments into a webpage. You can see the godoc of Elvish's eval package at https://godoc.org/github.com/elves/elvish/eval as an example. My proposal keeps godoc and "elvish doc" apart.

* I think the explicit markers in my proposal, as well as "discarded comments" (see note 2 in my last comment), helps distinguishing comments on implementation details from those as user documentation.

**Comment by xiaq** [comment]
OK, I am actually opting for a much simpler approach: looking for isolated comment blocks whose first line starts with some special marker, say `//elvish:doc-fn`. Those comments can be placed anywhere, but most commonly before the godoc of the implementation function. For instance, the source code for `cd` can look like this:

```go
//elvish:doc-fn cd
//
// ```elvish
// cd $dirname
// ```
//
// Change directory.
//
// Note that Elvish's `cd` does not support `cd -`.

// Changes directory.
func cd(fm *Frame, args ...string) error {
    ...
}
```

There are two comment blocks: the first one will be collected by Elvish's API doc generator (and ignored by `godoc`), while the second one will be collected by `godoc`.

**Comment by xiaq** [comment]
I have committed a tool, `elvdoc` that extracts those API docs from the source code. I have also written some docs in this format in the `newedit` package. You can try it out by running (assuming you are at the repo root):

```sh
go run ./_tools/elvdoc newedit/*.go
```

This is not integrated into the current website building toolchain yet, but in future, the *functions* and *variables* sections of https://elv.sh/ref/builtin.html, https://elv.sh/ref/edit.html and several others should be auto-generated.

**Comment by krader1961** [comment]
@xiaq, Any reason not to close this? You've established a pattern, and supporting tools, for documenting user facing builtin elvish vars and functions. Specifically, via `cd website; make gen`. That would seem to resolve this issue.

I would have preferred such documentation to be external to the Go source files but I don't feel so strongly about the issue to argue for changing the current approach. Either approach can be used via `go generate` to convert the documentation to a form that would support `a_builtin --help` if and when the Elvish community decides that is a good idea (I'm ambivalent).

**Comment by xiaq** [comment]
Yes, this should have been closed when `elvdoc` was integrated into the website building toolchain, I just forgot to close it.
