### ISSUE TITLE
Confusing error message for `x~ = foo`

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#744]
Reported by @zzamboni:

```
> foo~ = hi
Exception: multiple errors: need !!<nil>, got string; need !!<nil>, got string
[tty], line 1: foo~ = hi
```

**Comment by krader1961** [comment]
The error message is now, as of the 0.14 release, a tiny bit more sane:

```
> foo~ = hi
Exception: wrong type: need nil, got string
[tty 1], line 1: foo~ = hi
```

The problem here is the "need nil" portion of the message. I've seen this in other contexts such as issue #1014 where the same confusing diagnostic message occurs. That example can be distilled  to this:

```
> each wtf
Exception: wrong type of 1'th argument: wrong type: need nil, got string
[tty 28], line 1: each wtf
```

Note that the `each` command requires a function/lambda.

**Comment by krader1961** [comment]
Another example of this problem that was mentioned on Gitter/IRC today:

```
> re: = (ns $nil)
Exception: wrong type of 1'th argument: wrong type: need nil, got nil
[tty 1], line 1: re: = (ns $nil)
```

While `nil` was the passed value the expected value is `map` (or `{&}`).

**Comment by krader1961** [comment]
See also #715. One of these is basically a dup of the other.

**Comment by xiaq** [comment]
Closing as dup of #715

**Comment by xiaq** [comment]
(Forgot to close earlier; this is a dup of #715.)
