### ISSUE TITLE
Add domain config to epm

### ISSUE THREAD

**Issue by skrps** [elves/elvish#745]
I created an Elvish package and I'm hosting it on https://sr.ht; unfortunately I can't fetch it because elvish doesn't support fetching packages from arbitrary domains.

I can contribute the necessary code to make it work; AFAIK, the domains seems to be hardcoded in `eval/bundled/epm.elv.go`, and one could add another entry in `-default-domain-config`.  But I'm not sure this is the only way to handle this problem; maybe I can add an external file to handle this?

Thoughts?

**Comment by zzamboni** [comment]
@skrps: you can configure custom domains for `epm`, you can see the documentation here: https://elv.sh/ref/epm.html#custom-package-domains

In short, you need to create the domain directory by hand, and create the file `epm-domain.cfg` in it, with the corresponding information. For example, to fetch your Elvish package from https://git.sr.ht/~skrps/elv, you need to create file `~/.elvish/lib/git.sr.ht/epm-domain.cfg`, with the following contents:

```
{
  "method": "git",
  "protocol": "https",
  "levels": "2"
}
```

Then you can install your package (I just tested it and it works):

```
[~]─> cd .elvish/lib/
[~/.e/lib]─[⎇ master]─> mkdir git.sr.ht
[~/.e/lib]─[⎇ master]─> cat > git.sr.ht/epm-domain.cfg
{
   "method" : "git",
   "protocol" : "https",
   "levels": "2"
}
[~/.e/lib]─[⎇ master]─> epm:install git.sr.ht/~skrps/elv
=> Installing git.sr.ht/~skrps/elv
Cloning into '/Users/taazadi1/.elvish/lib/git.sr.ht/~skrps/elv'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (5/5), done.
[~/.e/lib]─[⎇ master]─> epm:list
▶ git.sr.ht/~skrps/elv
▶ github.com/iwoloschin/elvish-packages
▶ github.com/muesli/elvish-libs
▶ github.com/tylerreckart/gondolin
▶ github.com/xiaq/edit.elv
▶ github.com/zzamboni/elvish-completions
▶ github.com/zzamboni/elvish-modules
▶ github.com/zzamboni/elvish-themes
[~/.e/lib]─[⎇ master]─> use git.sr.ht/~skrps/elv/ssh-agent
```

Hope this helps!

**Comment by zzamboni** [comment]
One more comment: note that you have to use the full URL (including the `~`) when you install and also when you load the package. The built-in `epm` git method does not have the capability to transform the package location when installing it. If you really wanted to do it, you could define your own installation method, which inserts the tilde when appropriate, but stores the package without it, so that you could use `git.sr.ht/skrps/elv` as the package name. I wouldn't recommend doing this because I think one of the benefits of the current scheme is that the package name tells you where to find it as well, but it would be a fairly trivial modification to the built-in `git` method from https://github.com/elves/elvish/blob/master/eval/bundled/epm.elv.go#L99-L120.

You could assign the new method directly into the `epm:-method-handler` variable, something like this:

```
use epm
epm:-method-handler[git.sr.ht] = [
  &src= [pkg dom-cfg]{ put $dom-cfg[protocol]"://"(replaces git.sr.ht/ 'git.sr.ht/~' $pkg) }
  &install= [pkg dom-cfg]{
      dest = (epm:dest $pkg)
      epm:-info "Installing "$pkg
      mkdir -p $dest
      git clone ($epm:-method-handler[git.sr.ht][src] $pkg $dom-cfg) $dest
    }
  &upgrade= $epm:-method-handler[git][upgrade]
]
```

After modifying `epm-domain.cfg` to specify `git.sr.ht` as the method, you can specify your package without the tilde:

```
[~]─> epm:install git.sr.ht/skrps/elv
=> Installing git.sr.ht/skrps/elv
Cloning into '/Users/taazadi1/.elvish/lib/git.sr.ht/skrps/elv'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 5 (delta 0), reused 0 (delta 0)
Unpacking objects: 100% (5/5), done.
[~]─> epm:list
...
▶ git.sr.ht/skrps/elv
```

**Comment by skrps** [comment]
> you can configure custom domains for epm, you can see the documentation here: https://elv.sh/ref/epm.html#custom-package-domains

Great!  I'll add this information to README, with a ref to this issue.

> I wouldn't recommend doing this because I think one of the benefits of the current scheme is that the package name tells you where to find it as well

I also think this way.

Next time I'll read the documentation more carefully.  Thanks for the help!
