### ISSUE TITLE
Wrong key parsing with non-US layout on Windows

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#752]
Reported by SitiSchu on Telegram: on a German keyboard you use AltGr + ß to type a backslash; but Elvish parses this as Ctrl-Alt-[ and complains that it is unbound.

**Comment by alshain** [comment]
Interestingly, elvish v.0.12 (Windows) even interprets keys without modifiers in strange fashions.
Keyboard layout: German (Switzerland)

The "ASCII alphabet" (a-z) works properly, even though this is a QWERTZ layout.
However, every letter is transformed into its upper case version.

Anyway, on the current elvish-HEAD.exe, the above problems went away.
`a` yields `a`, `shift-a` yields `A`.

The only keys that work strangely now are the following keys:

I have pressed the keys near the umlauts in sequence, then the same thing again with the shift modifier applied.

Because `¨` is a dead key, I also pressed the umlaut `o` after it. Elvish, however, printed `` ` `` as soon as I hit the dead key. If I hit `¨` the dead key twice, I would expect to receive `¨¨`, elvish, gives `` `¨¨ ``. To get a single `¨`, I would hit `¨<space>`, elvish interprets this as `` `¨ ``


![image](https://user-images.githubusercontent.com/349397/47993304-6ae50680-e0ef-11e8-8df1-3754efddb458.png)

| I typed        | ü | ¨ | o | ö | ä | $ |   |   |
|----------------|---|---|---|---|---|---|---|---|
| Elvish printed | ü | ` | ö | ö | ä | $ |   |   |


| I typed | Elvish printed   |
|---------|------------------|
| è       | Unbound: Shift-; |
| !       | !                |
| é       | Unbound: Shift-' |
| à       | Unbound: Shift-\ |
| £       | &lt;nothing&gt;        |

**Comment by radgeRayden** [comment]
This also happens with Brazillian Portuguese (ABNT2) keyboard.
