### ISSUE TITLE
pipeline arguments

### ISSUE THREAD

**Issue by aeosynth** [elves/elvish#761]
hi, i would like to pipe directly into a function, without going through `each`. eg:

    put [foo bar] | each [x]{ put $x[0] }

becomes

    put [foo bar] | [x]{ put $x[0] }

currently i can avoid `each` by using output capture:

    put (put [foo bar])[0]

but this would be awkward to use multiple times in a single pipeline

edit: many built-in commands are not pipeline-aware, for instance `explode`:

    put [foo bar] | explode
    Exception: want 1 arguments, got 0

the preceding is much nicer to write than

    put [foo bar] | each [x]{ explode $x }

**Comment by zzamboni** [comment]
Currently there is no way for functions to take arguments directly from the pipeline. This can be emulated, for example I have written the `util:optional-input` function: https://github.com/zzamboni/elvish-modules/blob/master/util.org#pipeline-or-argument-input.

I think the problem is that the desired behavior is hard to specify and can change from case to case. What you are asking (IIUC) is that the function get executed multiple times, each time with the argument being one of the values coming from the pipeline. But that's exactly what `each` is for! Also, a pipeline can produce no output (which is why `optional-input` operates based on rest arguments). I personally think using `each` makes the intention clear.

**Comment by xiaq** [comment]
The [`all`](https://elv.sh/ref/builtin.html#all) was added for exactly this purpose! :)
