### ISSUE TITLE
Cannot find elvish in setup with tmux

### ISSUE THREAD

**Issue by greenfork** [elves/elvish#787]
Upon opening the terminal I get the following error message:

Cannot connect to daemon: failed to spawn daemon: cannot find elvish: file does not exist
Daemon-related functions will likely not work.
Failed to initialize command history; disabled.

Plus when I press `Ctrl + tmux prefix key + [`, tmux displays [0/0] in its upper right corner with some output in terminal but it may work correctly later (when I query the list of passwords with `pass`, for example).

I have the following setup:

`st -e tmux` as a startup for virtual terminal and `set -g default-shell /usr/local/bin/elvish` in `.tmux.conf`.

Works perfectly if I:

- Start elvish from tmux session with ksh
- Start `st -e elvish`

How do I start terminal + tmux + elvish with ksh login shell?

OS: OpenBSD 6.4
tmux OpenBSD specific version
terminal: st v0.8.1
elvish v0.12
login shell: ksh OpenBSD specific version

**Comment by xiaq** [comment]
Try either of the following:

* Use `default-command` instead of `default-shell`.
* Make sure that /usr/local/bin is part of `PATH` in the environment that tmux runs.

The `default-shell` option causes tmux to run Elvish as the login shell, which means that argv[0] will be set to `-elvish` instead of the full path; while os.Executable [on OpenBSD](https://golang.org/src/os/executable_path.go) relies on either argv[0] being the full path or Elvish being in the `PATH`, neither of which seems true for you.
