### ISSUE TITLE
compilation error when you input echo $u

### ISSUE THREAD

**Issue by electricface** [elves/elvish#809]
```
echo $u                                                                                                       elf-3050@bc98109a8ac8
compilation error: 5-7 in [tty]: variable $u not found
compilation error: 5-7 in [tty]: variable $u not found
```

elvish --version
v0.12-431-g71d050b3

**Comment by zzamboni** [comment]
Not sure what the problem is here. This is an error produced by Elvish, telling you that your command cannot be compiled because you are using a non-existing variable. This is exactly the way it's supposed to work :)

**Comment by electricface** [comment]
This is the error I reported while I was typing the command, but my command has not been entered yet. It is normal to report an error after pressing the Enter key.

**Comment by SolitudeSF** [comment]
why? now you know that your command is wrong before even executing, so you're not doing useless action or polluting your command history.

**Comment by electricface** [comment]
The same error here was reported twice.
Other shells don't have this behavior.

**Comment by zzamboni** [comment]
@electricface Elvish does on-the-fly syntax checking as you type your commands. If there are any errors, the whole command is never executed. This results in much more predictable behavior - i.e. if you use a non-existing variable, you get an error instead of an empty string (as in other shells), which may result in problematic behavior when the command is executed.

You can find some more information about this in the documentation: [Phases of Code Execution](https://elv.sh/learn/unique-semantics.html#phases-of-code-execution) and [Scoping Rule](https://elv.sh/ref/language.html#scoping-rule).

The double-error might be a terminal artifact. Elvish prints/deletes errors as they occur or get fixed, so if the terminal is not updating properly, you might be leftovers. In my terminal, I see flashes of changing error messages as Elvish updates the character range in which they occur (5-6, 5-7, etc.), but they all get deleted afterwards. If you see this double-error consistently, it might be worth filing an issue about it.

Welcome to Elvish! It has some behaviors that are very different from other shells, but in my opinion, once you get used to them, you'll discover that they mostly make sense and result in a very pleasant experience. The community is friendly, many of us hang out in Telegram or IRC, feel free to drop by and ask further questions.

**Comment by xiaq** [comment]
The double reporting is a bug, but the reporting itself is not.

**Comment by electricface** [comment]
OS is Linux. Can someone fix this bug that reports two errors?

**Comment by xiaq** [comment]
That is now tracked in #813.
