### ISSUE TITLE
Autovar (shorthand syntax for lambdas)

### ISSUE THREAD

**Issue by tfga** [elves/elvish#855]
Similar to `_` in Scala or [`it` in Kotlin](https://kotlinlang.org/docs/reference/lambdas.html#it-implicit-name-of-a-single-parameter).

Example                 | Desugars to
----------------------- | -------------
`{ echo $ }`            | `[x]{ echo $x }`
`{ * $ $ }`             | `[x]{ * $x $x }`

Bonus: `$1`, `$2`, ...

Example                 | Desugars to
----------------------- | -------------
`{ * $1 $2 }`           | `[x y]{ * $x $y }`

**Comment by xiaq** [comment]
Elvish used to have that, but I removed the feature because the use of closures is very pervasive - for instance, loop bodies are closures. This easily leads to problems like:

```
fn f {
  if (eq $1 a) {
    put $2
  }
}
```

The `$2` refers to the second argument of the *if body*, which does not have any arguments, not the second argument of the function.

Unless there is a design change to not use closures for the bodies of control structures, this feature will remain removed.

**Comment by tfga** [comment]
> Unless there is a design change to not use closures for the bodies of control structures, this feature will remain removed.

Maybe we can have both?

The problem is not that the body of `if` is a closure: the problem is that the desugaring is wrong.  
E.g.:

```
{ 
    if (put $true) {

        echo $ 
    }
}
```

is being desugared to

```
{ 
    if (put $true) [x]{    # <= wrong lambda

        echo $x 
    }
}
```

when it should be

```
[x]{                       # <= right lambda :)
    if (put $true) {

        echo $x 
    }
}
```

When you come across a `$` in the code, it's not enough to look at the current lambda (it might belong to an `if` or a `while`, etc). In that case, you have to move higher up in the AST, until you find a suitable node (the "right lambda") to add/reference the formal parameter (`x`, in the example above).

Of course, I haven't looked at the code, so I don't know how complicated this would be in practice. I'm assuming that you have an actual AST in memory, there might be a problem with the order in which things are created...

**Comment by xiaq** [comment]
IIUC, you are proposing to mark the lambda of `if`, `for` and other control structures as not supporting autovars, and skip them when attaching autovars.

It will certainly work in this example but there are two problems:

* These two types of lambdas are not visually distinct, and can cause confusion, especially for beginners.

* A deeper problem is that whitelisting the builtin control structures will not be enough, because Elvish makes it very easy to build commands that behave like control structures. Consider the following two functions that behave like control structures:

    ```
    fn forever [body] { while $true { $body } }
    fn forever-x [body] { while $true { $body x } }
    ```

    Now in this code:

    ```
    fn f { forever { echo $1 } }
    fn g { forever-x { echo $1 } }
    ```

    How should `$1` be resolved in both cases? How should Elvish know?
