### ISSUE TITLE
buildinfo.GoRoot and buildinfo.GoPath purpose

### ISSUE THREAD

**Issue by dmgk** [elves/elvish#861]
Not a bug report, but a question. What is the reason for embedding build-time GOROOT and GOPATH in the executable in Makefile:12?

```
        go get -ldflags "-X github.com/elves/elvish/buildinfo.Version=$(VERSION) \
                -X github.com/elves/elvish/buildinfo.GoRoot=$(shell go env GOROOT) \
                -X github.com/elves/elvish/buildinfo.GoPath=$(shell go env GOPATH)" .
```

**Comment by xiaq** [comment]
This is because Go did not use to have byte-to-byte reproducible builds because it always encodes the full path of source files, so GOPATH and GOROOT function as the "fingerprints" of the build, so they were added for verifying binaries. The idea is that if you have two binaries built against the same `GOOS` and `GOARCH` and have the same `-buildinfo` output, they should be identical byte to byte.

On a side note, Elvish has two independent sources of prebuilt binaries, and they have their GOROOT and GOPATH set up to be identical. https://dl.elv.sh/linux-amd64/elvish-HEAD.sha256sum and https://dl2.elv.sh/linux-amd64/elvish-HEAD.sha256sum should be identical despite the fact that they are built on two different machines. (This is broken for now, however, because the version of Go on these two machines have drifted out of sync. I'm fixing that.)

Also, it seems that Go 1.13 actually supports byte-to-byte reproducible builds with the new `-trimpath` option, so these two fields will no longer be needed.

**Comment by dmgk** [comment]
@xiaq Thank you for the explanation.

**Comment by vendion** [comment]
As a follow up, moving forward when the minimum Go version for building Elvish is bumped to Go 1.13 will the `-trimpath` be set as the default in the effort to have reproducible builds?

**Comment by xiaq** [comment]
Yes :)

I intend to already do this for the prebuilt binaries, they are built using the latest version of Go.

**Comment by vendion** [comment]
Thanks for answering our questions.
