### ISSUE TITLE
How about adding more clear error message for some builtin functions?

### ISSUE THREAD

**Issue by 0x005c** [elves/elvish#867]
Now, `%` and `randint` just throw args error; it is difficult to understand why the function failed.
```
~/go/src/github.com/elves/elvish> % 2 0
Exception: args error
[tty], line 1: % 2 0
~/go/src/github.com/elves/elvish> randint 100 0
Exception: args error
[tty], line 1: randint 100 0
```

How about adding better error messages for them?

**Comment by xiaq** [comment]
Yes! I would like to have such errors be structured too, like:

```
type SingleArgError struct {
    Which int
    Want string
    Got string
}

func (err SingleArgError) Error() string {
    return fmt.Sprintf("error with argument #%d: want %s, got %s", err.Which, err.Want, err.Got)
}
```

Although `Want` and `Got` are now strings, in future they can potentially be structured too, as some kind of representation of types.

**Comment by krader1961** [comment]
See also the discussion in issue #966 for why introducing, and consistently using, Elvish structured error types rather than Go's `error` type is a good idea as it makes it easier to write robust unit tests and makes it easier to provide meaningful introspection of exceptions from elvish code.

**Comment by krader1961** [comment]
I believe this has been addressed by changes made since this issue was opened. Specifically, the two examples in the original problem description has been addressed:

```
> randint 100 0
Exception: bad value: high value must be larger than 100, but is 0
> % 2 0
Exception: bad value: divisor must be number other than exact 0, but is exact 0
```

There are undoubtedly other instances which would benefit from such improvements, but without specific examples it's hard to know what to do. I know that I've created several changes recently that replace general errors with specific errors. I recommend closing this issue as, at least mostly, resolved.
