### ISSUE TITLE
Warn user when using deprecated builtin features

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#898]
(Edit: see https://github.com/elves/elvish/issues/898#issuecomment-602282707 for the current thinking on how to implement.)

Implement a method on `*Frame` that shows a deprecation message:

```go
func (*Frame) Deprecate(reason string)
```

However, during the entire lifecycle of an `Evaler`, the same deprecation message should only be shown for the same source location once. For example, if you have a function that uses a deprecated feature, the same message should only be shown the first time the function is called.

Until this feature is implemented, deprecated feature will have a `TODO(#898): Formally deprecate feature X` attached to them in the Go code.

**Comment by krader1961** [comment]
I don't see how this proposal proactively tells users that a given feature is deprecated. They have to actually use the feature to see the deprecation message. Presumably you still intend to publish the deprecation, independent of this feature implementation, in a *CHANGELOG* file or similar mechanism.

What happens if the feature is used in a non-interactive context? If it occurs in a non-interactive context how does the deprecation message interact with the consumer of the output of the deprecated feature?

**Comment by xiaq** [comment]
@krader1961 you are right, deprecating a feature also requires documenting it properly. I changed the title of this issue to reflect it.

Let me elaborate a bit on why I closed #939 citing this issue; I consider this functionality to be a *prerequisite* to deprecating any feature. If we document that something is deprecated, people *can* proactively change their code to avoid deprecated features, but (1) it's easy for people to miss part of the release notes (2) humans are error-prone and may not find all uses. Instead, it's much better for a machine (in this case, the Elvish interpreter) to discover uses of deprecated features and warn the user.

Re. where the warning goes in a non-interactive context: the warning goes to stderr.

**Comment by xiaq** [comment]
On the technical side, a better way to implement this mechanism is during compilation instead of evaluation. This has a few advantages:

* The deprecation warning is shown even if the code that uses the deprecated function or variable is not executed

* Deprecation warnings are clustered - all deprecation warnings for the same source are shown at the same time, making it easier to fix in batch.

* There is no need to remember that a deprecation message has already been shown for a certain source location, since each source is compiled only once.

**Comment by krader1961** [comment]
> Re. where the warning goes in a non-interactive context: the warning goes to stderr.

The risk is that in a non-interactive context the deprecation warning, even when written to stderr rather than stdout, can break things. Other languages, such as Python, behave per your proposal; modulo Python's configurability with regard to this behavior. I've actually been bitten by this so am "gun shy" about introducing it in a new language. Yet I don't have a better proposal. 

Also, PR #939 did not say that the builtins would be removed after a specific release. It said that the features could be removed any time after that release. Including long in the future after this issue is resolved. It served to tell users that they should start future-proofing their programs. Not to mention hinting why there were two pairs of seemingly identical commands.

**Comment by xiaq** [comment]
Re writing warning to stderr can break things: care to elaborate how you were bitten?

Re when to remove features: you are right that we can document the deprecation first, and implement the warning mechanism after that. But I'd like to send a more consistent message to users on what "deprecation" means - which should be all of the following at the same time:

* Code that uses such feature will see warning when run
* Deprecation is documented
* Feature deprecated in release N will be removed in N+1
