### ISSUE TITLE
elvish "if" BUG (help needed)

### ISSUE THREAD

**Issue by enty8080** [elves/elvish#904]
```
fn godu [opt]{
           if [$opt == "ram"] {
               echo "ram"
           }
           if [$opt == "sda"] {
               echo "sda"
           }
       }
```
USER INPUT:
```
~> godu sda
```
OUTPUT:
```
ram
sda
```

**Comment by SolitudeSF** [comment]
that is not a correct syntax. read the reference https://elv.sh/ref/language.html#condition-if

**Comment by enty8080** [comment]
But how to use `if` without elif?

**Comment by SolitudeSF** [comment]
just dont use `elif`? what?

**Comment by enty8080** [comment]
Ok

**Comment by enty8080** [comment]
But I am got an error, can you give me example? 
![599C6821-9A1D-4E67-83D3-3EA5758594FE](https://user-images.githubusercontent.com/54115104/73107341-e7832100-3efd-11ea-8d0a-3d66d615c91c.jpeg)

**Comment by enty8080** [comment]
With `(` got this error:
![6482BCFE-E035-426D-A9E6-208B7F7F92B0](https://user-images.githubusercontent.com/54115104/73107803-11891300-3eff-11ea-9294-b88e2fcd3200.jpeg)

**Comment by enty8080** [comment]
Help me please

**Comment by enty8080** [comment]
Can you rewrite this code to the correct code?
![3B23A9F4-73E6-47C7-9F64-FA59864F5BAD](https://user-images.githubusercontent.com/54115104/73110632-747ea800-3f07-11ea-9a6a-59650a972e5f.jpeg)

**Comment by krader1961** [comment]
Please take a few minutes and read the documentation: https://elv.sh/learn/fundamentals.html, https://elv.sh/learn/effective-elvish.html, and https://elv.sh/learn/unique-semantics.html#predicates-and-if. Also: https://elv.sh/ref/builtin.html#s-s-s-s-s-s. Note that elvish is not a POSIX shell like bash. Elvish has very little in common with POSIX shells. Having said that I'd agree that the documentation for what a `if` "condition" is could be improved by including a few more typical examples (such as comparing strings for equality) and the term "condition" needs an explicit definition.

For your example you can use the `test` builtin or the `==s` function.

```
~> fn godu [opt]{
       if (==s $opt "ram") {
           echo "ram"
       }
       if (==s $opt "sda") {
           echo "sda"
       }
   }

~> godu ram
ram
~> godu sda
sda
~> godu xyx
~>
```

Or

```
~> fn godu [opt]{
       if ?(test $opt == "ram") {
           echo "ram"
       }
       if ?(test $opt == "sda") {
           echo "sda"
       }
   }

~> godu sda
sda
~> godu ram
ram
~> godu abc
~>
```

Notice that one of them uses `?(...)` and the other just `(...)`.

**Comment by enty8080** [comment]
Thank you very much!

**Comment by enty8080** [comment]
Why elvish don’t use just `==`, why `==s`?

**Comment by krader1961** [comment]
Elvish does have `==` but it does a numeric comparison. See https://elv.sh/ref/builtin.html#-----

**Comment by zzamboni** [comment]
As others have pointed out, it pays to read through the Elvish documentation, as its syntax is substantially different than what you may be used to from POSIX shells. To add a couple of additional pointers and explanations:

- In addition to the comparison operators already mentioned, there is also [eq](https://elv.sh/ref/builtin.html#eq), which determines "whether all $values are structurally equivalent" and is very commonly what one wants. Note that if you know you are going to do numerical comparisons, it's better to use the numeric operators. For example:
```
[~]─> eq 3 3
▶ $true
[~]─> eq 3 3.0
▶ $false
[~]─> == 3 3.0
▶ $true
```

- To explain why your initial example was always behaving as if the condition was true: the condition you were passing was an array, consisting of three values, e.g. `[$opt "==" "ram"]`. This is a booleanly true value for Elvish, which is why the statements were syntactically correct. You can see this more clearly like this:

```
[~]─> fn godu [opt]{                                                                                                                                                                   
        val = [$opt == "ram"]
        if $val {
          pprint $val
        }
      }
[~]─> godu foo
[
 foo
 '=='
 ram
]
[~]─> godu ram
[
 ram
 '=='
 ram
]
```

Hope this helps! Elvish takes a bit getting used to, but it's a really nice language, much more efficient than any other shell I have used.
