### ISSUE TITLE
Support comments everywhere newline is treated as whitespace

### ISSUE THREAD

**Issue by SitiSchu** [elves/elvish#924]
Currently this:
```
[
    value
    # comment
    value2
]
```

fails with: 
```
Multiple parse errors:
  should be ']'
    /home/sitischu/.elvish/lib/github.com/mojurasu/riku/test.elv, line 8:
          # comment
  unexpected rune ']'
    /home/sitischu/.elvish/lib/github.com/mojurasu/riku/test.elv, line 10:
      ]
```

**Comment by krader1961** [comment]
A variation on the above example:

```
~> put [x #y ]
parse error: 7-8 in [interactive]: should be ']'
parse error: should be ']'
[tty], line 1: put [x #y ]
```

That illustrates why such syntax is problematic. It's not enough to support comments on lines without any other expression of syntactically significant tokens. Note that even without the trailing `]` in that example it fails using current parsing behavior. Which is another road block to changing the behavior since doing so something that can only be done in a major release.

**Comment by SitiSchu** [comment]
Breaking changes should be fine since we're still below 1.0. Interestingly enough it behaves as expected with lambdas:

```
~> { put 1 # comment }
   }
▶ 1 
```

**Comment by xiaq** [comment]
@krader1961 I am not sure what's the problem with `put [x #y ]`. In this case, it is the same as `put [x`; the closing bracket needs to appear on a second line.

Currently having `#` inside lists is a syntax error. Making an invalid program valid does not break backward compatibility.

**Comment by krader1961** [comment]
@xiaq, Yes, you're right regarding backward compatibility. I was mislead by the failure of the `put [x #y ]` example. I expected it to be equivalent to `put ['x' '#y']` since I expected `#` to not be special inside a list.

**Comment by xiaq** [comment]
I widened the scope of the issue a bit. There are in fact more places where comments should be allowed but currently aren't, such as argument lists (in a lambda) and braced lists.
