### ISSUE TITLE
Support constructing map from pairs

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#943]
Transforming a map into a different one now requires mutating a map repeatedly. For example, to change all keys in a map to upper case:

```elvish
use str
m = [&foo=1 &bar=2 &lorem=3]
new-m = [&]
for k [(keys $m)] {
  new-m[(str:to-upper $k)] = $m[$k]
}
```

If we have a function, say `make-map`, that takes pairs and puts a map (inputs can be supplied [either via pipe or a list argument](https://elv.sh/ref/builtin.html#supplying-input)), the code becomes much simpler:

```
use str
m = [&foo=1 &bar=2 &lorem=3]
for k [(keys $m)] { put [(str:to-upper $k) $m[$k]] } | new-m = (make-map)
```

**Comment by krader1961** [comment]
For those wondering why this feature might be useful see the discussion about Elvish [persistent data structures](https://elv.sh/learn/unique-semantics.html#implementation-detail-persistent-data-structures). In functional programming languages, such as Haskell, such data structures are central to the design of the language. They therefore use very sophisticated solutions to the problem of cheaply mutating otherwise immutable lists or maps. Elvish currently uses the simplest, and typically least performant, solution for that problem: copy on write. See https://en.wikipedia.org/wiki/Persistent_data_structure.

Note that the

```
    new-m[(str:to-upper $k)] = $m[$k]
```

in the first example in the problem description actually creates a new map and binds it to the `new-m` variable name. It **does not** mutate the existing map bound to `new-m`. Which, given the copy on write semantics, is why that pattern is inefficient and something like the proposed `make-map` command is useful.
