### ISSUE TITLE
Add read-line command

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#975]
Currently `read-line` can be implemented in terms of `read-upto`, but it would be nice to have a dedicated `read-line` command too.

**Comment by krader1961** [comment]
Let me start by saying I haven't used MS Windows as a developer in more than two decades. So perhaps the rest of my comment is ill-informed regarding best practices for splitting text on line boundaries on MS Windows. In fact, I've found a few articles that talk about this. Such as https://www.theregister.co.uk/2018/05/08/windows_notepad_unix_linux_macos/ from two years ago which notes that Windows Notepad application finally does something reasonable when opening a file with UNIX line endings.

The problem with implementing `read-line` as a function built in terms of `read-upto` is that it seems impossible to make it work correctly on UNIX and MS Windows. Some of the difficulty in doing so was recently ameliorated by the introduction of the `$platform:is-unix` and `$platform:is-windows` variables. Those can be used to ignore `\r` on UNIX platforms.

The difficulty is how to handle the `\r\n` sequence with full fidelity on MS Windows if either char of the pair is missing. You can't just `read-upto` a `\n` then strip the `\r`, if any, that is in the returned string AFAIK to be strictly conforming with the MS Windows definition of a line. Perhaps being strictly conforming with old versions of MS Windows (and MS DOS) is no longer appropriate. And splitting on any of the chars individually, and the `\r\n` pair, is now acceptable and/or a best practice.

**Comment by krader1961** [comment]
I am inclined to recommend that Elvish implement a `read-line` that accepts `\r`, `\n` or `\r\n`. Furthermore, that implicit splitting of command byte output be done using the same criteria. Regardless of the platform. Where more control is needed the `read-upto` command should be used. Although that represents difficulties since if you do `x = (read-upto "\n")` you presumably don't won't any trailing `\r` that remains to be removed.

It seems like this ultimately boils down to how easily we want Elvish to be able to process arbitrary binary data without using mechanisms like the `slurp` command (which might also need to be special-cased).

**Comment by xiaq** [comment]
It is not possible to implement a command that accepts `\r` and `\r\n` at the same time (it wouldn't know whether to continue going after `\r`). None of the platforms supported by Elvish uses `\r`, so `read-line` will just support `\n` or `\r\n`.

**Comment by xiaq** [comment]
Adding this to 0.14 since `read-line` can replace use of `take 1` for reading a single line from byte input, and #923 is in 0.14.
