### ISSUE TITLE
Make \ a valid bareword character

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#979]
The backslash (`\`) is the preferred path separator on Windows [1].

I intend to make it Elvish a truly cross-platform shell, so being able to write paths without quoting is an important part of that goal.

Elvish now only uses backslashes for line continuations; everywhere else it triggers a parse error.  Elvish can use backticks (`` ` ``) for line continuation instead.

**Update**: the choice has been changed to use `^` for line continuation instead.

[1] The forward slash (/) actually works as a path separator on the Windows API level, but not all external programs support it.

**Comment by xiaq** [comment]
Hmm, PowerShell's choice of using `` ` `` for line continuation is actually [hated](https://powershell.org/2013/07/powershell-great-debate-backticks/) by some PowerShell users (power users? :), and some people even [go to great length](https://get-powershellblog.blogspot.com/2017/07/bye-bye-backtick-natural-line.html) to avoid them. The main argument is that it is really hard to see, especially at the end of the lines.

Elvish also reserves `^` now, and that seems to be a better choice. It is also used by DOS batch scripts as line continuation, a happy coincidence.

**Comment by hanche** [comment]
Would it be a viable option to make the bare backslash work as a line continuation character only if preceded by white space? Personally, I think it's bad style not to put white space before a trailing backslash anyhow. And I think people do it only rarely, if at all.

**Comment by Xjs** [comment]
ISTM that space backslash, i. e. `⌴\`, could work as line continuation string from a user perspective. +1

**Comment by krader1961** [comment]
> Would it be a viable option to make the bare backslash work as a line continuation character only if preceded by white space?

The corner case is when the final argument of a command is the root directory; i.e., a bare `\`. For example, `dir \`. That case has three workarounds: `'\'`, `"\\"` and `\.\`. But is likely to be a source of surprise even though it will be somewhat rare. I can't see any way to allow backslash as both a path separator and a line continuation marker without creating a source of friction that will cause pain. Which makes me a sad puppy since anyone used to the C language or the POSIX shell standard (notwithstanding all its flaws) expects backslash to "escape" the meaning of the next character. Which, in the case of a newline means ignore the newline.

> Elvish also reserves ^ now, and that seems to be a better choice.

Yes, but it's not obvious that means some of the other punctuation characters that currently have some special meaning could not be used. Couldn't any punctuation character that is otherwise illegal at the end of a line be used to signal line continuation? For example, couldn't a bare `$` (i.e., unquoted) as the final char on a line could also serve as a line continuation signal. That has its own problems, of course. But it seems unambiguous with regard to the Elvish parser.

**Comment by hanche** [comment]
That goes to show how little I know about Windows: I thought every path needed a drive letter, as in `C:\`. A trailing `$` seems like a perfectly fine choice to me.

**Comment by zzamboni** [comment]
> Couldn't any punctuation character that is otherwise illegal at the end of a line be used to signal line continuation? For example, couldn't a bare `$` (i.e., unquoted) as the final char on a line could also serve as a line continuation signal.

By this logic, why not continue using the backslash? A lone backslash at the end of the line could be a special case that signals a continuation.

WRT the backtick, wasn't this the initial Elvish continuation character, and then it got changed to the backslash?

**Comment by xiaq** [comment]
Replying to @zzamboni:

> By this logic, why not continue using the backslash? A lone backslash at the end of the line could be a special case that signals a continuation.

As pointed out by @krader1961, a bare `\` is a valid path in Windows and can appear at the end of a command. It refers to the root of the current drive.

> WRT the backtick, wasn't this the initial Elvish continuation character, and then it got changed to the backslash?

Yes, I changed my mind again :) but I'm not in favor of going back to backtick this time.

**Comment by xiaq** [comment]
@krader1961 Using `$` for line continuation is a clever idea. It *works*, in fact it seems to be the only metacharacter that works (everything else may be followed by a newline).

That said, `^` still feels better to my personal taste, and I reserve the right to use that as a factor in design decisions :)

----

Below I justify my personal taste, which I admit is more subjective than objective:

Elvish only has two metacharacter with two different meanings:

* `&`, marking both key-value pairs (from HTTP query parameters) and background pipeline (from sh)
* `{`, starting both braced list (`{foo bar}`, from sh) and closure (`{ echo }`, from C's block)

Both meanings of both characters have a source elsewhere that used it in the same or analogous.

`$` is used in regular expressions for end of lines, which is almost opposite to line continuation. Whereas `^` (1) is used for line continuation in batch files, and (2) has an original meaning of "insert more things here" in handwriting. It is also used in regex for line beginning, which I feel eludes to the next line, but that could be far-fetched for some.

**Comment by krader1961** [comment]
AFAICT, only `$`, `^` and backtick currently have no meaning when used as the last token of a line. Of those three I prefer the first two because they're more legible. A weak argument to prefer `$` is it leaves `^` for a future use.

I also considered using a punctuation char that is currently legal as a bare word token. Some of those chars are unlikely to appear as the final token of a line. For example, `%`. That could be used as the final token of a line to indicate continuation if we're willing to require any such use to quote the char; e.g. `echo %` would have to be written `echo '%'`. However, even suggesting such a thing makes me queasy as it introduces an ad-hoc rule.

**Comment by Xjs** [comment]
I would argue against `^`, I often run `git diff HEAD^` or something like that, which would break. Requiring a space character before the line continuation character seems a good idea to me, e. g. <space>^ would probably work for me as well (as would <space>\, still -- ISTM the `dir \` case is quite rare)

**Comment by xiaq** [comment]
@Xjs you already have to quote `HEAD^` in Elvish today; I reserved `^` and made it an invalid character outside quotes. I feel use of `^` is rare enough (except in `HEAD^`) and having to quote it is not a terrible inconvinience.

**Comment by Xjs** [comment]
@xiaq I know I have to. But an argument that was made against my suggestion of `<space>\` by @krader1961 was that it would break `dir \`, which is just as well not working without quotes as of now. Personally, I run git commands a lot more often than I list the root directory of a volume without being cd'd to it, so that's that.

You seem to be wanting to stick to a single character for line continuation. I wonder why that is. But of course, you have the final say about anything. I'm just giving feedback from my usage experience. :)

**Comment by krader1961** [comment]
> ...was that it would break `dir \`

Note that was simply an easily understood example. The problem is, obviously, more general in as much as any command that might take a path as its final argument is subject to the problem. For example, whatever the Windows equivalent of UNIX's `du /` is. I too execute many git commands every day. Yet, for whatever reason, I seldom use `HEAD^` (or similar constructs) so I haven't felt much pain from a bare `^` being illegal.

Having said all that I'm still inclined to predicate it's special meaning of eliding the following newline on the preceding character being a space or tab. That would make it possible to use `^` elsewhere without quoting it. Again, that introduces an ad-hoc rule but one that seems unlikely to cause problems and the benefits likely justify it.

**Comment by xiaq** [comment]
My current plan is to use `^` as the line continuation character, and make `\` a bareword character everywhere. Use of `^` outside line continuation is still reserved for future use.

My main design concern is mainly simplicity of rules rather than frequency of use cases: requiring a space to disambiguate line continuation is too subtle a rule. As I said, this does not mean the design choice is objectively better, but rather, it suits my taste better.

**Comment by xiaq** [comment]
Since making `\` a bareword character elsewhere breaks existing use of it for line continuation, this change will be introduced after the 0.14 release.

In 0.14 Elvish should produce deprecation warnings when `\` is used for line continuation.

**Comment by xiaq** [comment]
Moving this to 0.14 so that I don't forget to introduce the deprecation in 0.14; after that's done I'll move this back to 0.15.
