### ISSUE TITLE
Support using ^ for line continuation

### ISSUE THREAD

**Issue by xiaq** [elves/elvish#989]
See #979 for context. `^` is currently reserved, so this is a non-breaking change.

**Comment by xiaq** [comment]
Hmm, `^` is now allowed in command name; this is only used by the `^` command.

To make the parse rule simpler `^` should be disallowed in command names and the `^` command should be renamed first.

**Comment by krader1961** [comment]
Note that the `^` command isn't going to be used very often and should be moved to `math:pow`. The only reason I had not already implemented that command was due to the existence of `^`. But in light of this issue I'll go ahead and implement that as well as `math:pow10` which will defer to Go's `math.Pow10()` and is, presumably, an optimized form for a common case.

**Comment by xiaq** [comment]
Since `^` is allowed as a command name, this is technically a breaking change. The only code that has its behavior changed is a lone `^` invocation:

```
^
```

Since this will trigger an exception anyway (`^` requires two arguments), I am going to introduce this breaking change directly.
